package group

import (
	"fmt"
	"math/big"

	"github.com/vocdoni/davinci-dkg/types"
)

// bn254Q is the BN254 scalar field prime — the coordinate field of
// BabyJubJub in the reduced twisted-Edwards form used by gnark-crypto.
var bn254Q, _ = new(big.Int).SetString(
	"21888242871839275222246405745257275088548364400416034343698204186575808495617", 10,
)

// BaseField returns the BN254 scalar field modulus, i.e. the coordinate
// field of BabyJubJub and the field every Groth16 public input lives in.
func BaseField() *big.Int {
	return new(big.Int).Set(bn254Q)
}

// IsCanonical reports whether (x, y) are both reduced modulo the
// coordinate field prime Q. Non-canonical encodings are rejected to
// rule out aliased representations of the same logical point.
func IsCanonical(x, y *big.Int) bool {
	if x == nil || y == nil {
		return false
	}
	if x.Sign() < 0 || y.Sign() < 0 {
		return false
	}
	return x.Cmp(bn254Q) < 0 && y.Cmp(bn254Q) < 0
}

// IsIdentity reports whether (x, y) is the BabyJubJub identity (0, 1).
func IsIdentity(x, y *big.Int) bool {
	if x == nil || y == nil {
		return false
	}
	return x.Sign() == 0 && y.Cmp(bigOne) == 0
}

var bigOne = big.NewInt(1)

// IsOnCurve reports whether (x, y) satisfies the BabyJubJub curve equation
// in reduced twisted-Edwards form: -x² + y² = 1 + d·x²·y² (mod Q).
func IsOnCurve(x, y *big.Int) bool {
	if !IsCanonical(x, y) {
		return false
	}
	// Encode and try to decode; the decoder runs the curve-equation check.
	if _, err := Decode(types.CurvePoint{X: new(big.Int).Set(x), Y: new(big.Int).Set(y)}); err != nil {
		return false
	}
	return true
}

// IsInPrimeSubgroup reports whether (x, y) lies in the prime-order
// subgroup of BabyJubJub generated by the canonical generator G — i.e.
// `[L]·P == identity`. Off-subgroup points are on-curve but live in the
// 8-element cofactor subgroup; honest ElGamal ciphertexts always live
// in `<G>` because both `c1 = r·G` and `c2 = m·G + r·PK` are explicit
// scalar multiples of generators in `<G>`.
//
// Computing `[L]·P` costs one full BabyJubJub scalar multiplication; on
// commodity hardware this is a small fraction of a millisecond, but it
// is overwhelmingly more expensive than the on-curve / canonical checks.
// Callers should use `ValidateEncryptionPoint` to run the cheap checks
// first and short-circuit on the common rejection paths.
func IsInPrimeSubgroup(x, y *big.Int) bool {
	if !IsOnCurve(x, y) {
		return false
	}
	if IsIdentity(x, y) {
		return true // identity lies in every subgroup
	}
	p, err := Decode(types.CurvePoint{X: new(big.Int).Set(x), Y: new(big.Int).Set(y)})
	if err != nil {
		return false
	}
	// [L]·P == identity ?
	scaled := NewPoint()
	scaled.ScalarMult(p, p.Order())
	identity := NewPoint()
	identity.SetZero()
	return scaled.Equal(identity)
}

// ValidateEncryptionPoint runs the full validation pipeline a committee
// node MUST apply before treating (x, y) as a usable ciphertext component.
// The named `kind` is woven into every error so callers can correlate
// rejections back to a specific operand (e.g. "c1", "c2", "PK_org").
//
// THREAT MODEL (why every check matters)
//
//  1. Non-canonical coordinates (X or Y >= Q) — let an attacker register
//     two distinct calldata payloads that hash to different ciphertext
//     hashes but represent the same logical point modulo Q, defeating
//     write-once slot semantics and event-log dedupe assumptions.
//
//  2. Off-curve points — partial-decrypt `δ_i = sk_i · c1` is well-defined
//     for any (x, y) ∈ Q × Q under the EC group law, but the resulting
//     point would lie outside BabyJubJub. The combine SNARK requires
//     in-curve operands; the proof would never close. Worse, the
//     scalar mul could exhibit unexpected side-channel behaviour in
//     non-constant-time code paths.
//
//  3. Identity (0, 1) — `δ_i = sk_i · O = O` for every committee member.
//     Combine reduces to `M = c2 - O - T`. If c2 is also identity (or
//     the attacker chose c2 to embed a known plaintext), the recovered
//     plaintext is publicly computable WITHOUT any partial-decryption
//     work — the "decryption" is trivial. This breaks the protocol's
//     confidentiality guarantee for that ciphertext.
//
//  4. Off-prime-subgroup points (cofactor subgroup, order h | 8) —
//     `δ_i = sk_i · P` where P has small order h. The map
//     `sk_i ↦ δ_i` factors through `sk_i mod h`, so publishing δ_i
//     leaks `log₂(h) ≤ 3` bits of the participant's share. By Shamir
//     interpolation over `Z/hZ` the master secret leaks the same number
//     of bits — small in absolute terms, but a permanent on-chain
//     side-channel an adversary could exploit by submitting carefully
//     crafted ciphertexts. The on-chain `submitCiphertext` deliberately
//     does NOT enforce this check (it would cost ~0.17 M gas per
//     submission), so the off-chain enforcement here is the canonical
//     defence layer; node operators MUST run it.
//
// A point that survives all four checks lies in the prime-order subgroup
// of a well-formed BabyJubJub curve, and any partial decryption derived
// from it is information-theoretically safe to publish.
func ValidateEncryptionPoint(kind string, x, y *big.Int) error {
	if !IsCanonical(x, y) {
		return fmt.Errorf("%s: non-canonical coordinates (X or Y >= Q, or negative, or nil)", kind)
	}
	if IsIdentity(x, y) {
		return fmt.Errorf("%s: identity point (0, 1) is rejected — would trivialise decryption", kind)
	}
	if !IsOnCurve(x, y) {
		return fmt.Errorf("%s: point is not on BabyJubJub", kind)
	}
	if !IsInPrimeSubgroup(x, y) {
		return fmt.Errorf("%s: point is on-curve but outside the prime-order subgroup — would leak sk_i mod h", kind)
	}
	return nil
}

// ValidateCiphertext runs ValidateEncryptionPoint on both halves of an
// ElGamal ciphertext (c1 = r·G, c2 = m·G + r·PK). Returns the first
// rejection if either coordinate is invalid.
func ValidateCiphertext(c1, c2 types.CurvePoint) error {
	if err := ValidateEncryptionPoint("c1", c1.X, c1.Y); err != nil {
		return err
	}
	if err := ValidateEncryptionPoint("c2", c2.X, c2.Y); err != nil {
		return err
	}
	return nil
}
