// SPDX-License-Identifier: AGPL-3.0-or-later
pragma solidity 0.8.28;

import {Test, Vm} from "forge-std/Test.sol";
import {DKGRegistry} from "../src/DKGRegistry.sol";
import {DKGManager} from "../src/DKGManager.sol";
import {DKGAppManager} from "../src/DKGAppManager.sol";
import {IDKGManager} from "../src/interfaces/IDKGManager.sol";
import {IDKGAppManager} from "../src/interfaces/IDKGAppManager.sol";
import {DKGTypes} from "../src/libraries/DKGTypes.sol";
import {BRLC} from "../src/libraries/BRLC.sol";
import {MAX_N, MAX_K, MERKLE_DEPTH} from "../src/libraries/Sizes.sol";
import {BabyJubJub} from "../src/libraries/BabyJubJub.sol";
import {
    MockContributionVerifier,
    MockPartialDecryptVerifier,
    MockPoolKeyVerifier,
    MockDecryptCombineVerifier,
    TestHelpers
} from "./TestHelpers.t.sol";

contract DKGManagerTest is Test, TestHelpers {
    DKGRegistry public registry;
    MockContributionVerifier public verifier;
    MockPartialDecryptVerifier public partialVerifier;
    MockPoolKeyVerifier public poolKeyVerifier;
    MockDecryptCombineVerifier public decryptCombineVerifier;
    DKGManager public manager;
    DKGAppManager public appManager;

    uint64 internal constant INACTIVITY_WINDOW = 1_000;

    /// @dev Committee member 1 of every fixture epoch. Must be a plain
    ///      address with no code: submitContribution / activatePoolKey
    ///      reject contract callers (DirectCallRequired), and the test
    ///      contract itself is a contract, so it can never contribute.
    address internal alice = address(0xA11CE);

    /// @dev Every ciphertext in this suite lives under one registered
    ///      application: there is no epoch-key (aid = 0) path any more.
    bytes32 internal constant TEST_AID = bytes32(uint256(0xA1D));

    // Schnorr vectors generated by cmd/operator-schnorr-vectors. ALICE is
    // 0xA11CE (committee slot 0); BEEF is 0xBEEF (committee slot 1). Both
    // are codeless addresses, see `alice` above.
    uint256 internal constant ALICE_PUBX =
        14666979294172776374634275498241310759674509575452256743546893482427808967539;
    uint256 internal constant ALICE_PUBY =
        16568773859060023308888034681483224034881825787861296311803627274237556869649;
    uint256 internal constant ALICE_AX =
        206825796546323573150801242605652465781823711295602898923500400375891572685;
    uint256 internal constant ALICE_AY =
        14223109950820609858208501628131627333362274908883166606890781114024603385194;
    uint256 internal constant ALICE_Z =
        1415349030302839010594375480381656799266590814245522079555192493283473059241;
    uint256 internal constant BEEF_PUBX =
        10228722604559478181013548940833210623190136968531440936190496170400150013980;
    uint256 internal constant BEEF_PUBY =
        13886497050333420293068628977630539070604271411621054562122682889313139677221;
    uint256 internal constant BEEF_AX =
        14566234973743316386655481200503006158732416518867749191804063760238069794878;
    uint256 internal constant BEEF_AY =
        13078057343376780948266496972118389875598288245980415388506507934563371992806;
    uint256 internal constant BEEF_Z =
        855437853746059451716869189734643730464853812739723681978635195783451059776;

    function setUp() public {
        registry = new DKGRegistry(INACTIVITY_WINDOW);
        vm.prank(alice);
        registry.registerKey(ALICE_PUBX, ALICE_PUBY, ALICE_AX, ALICE_AY, ALICE_Z);
        vm.prank(address(0xBEEF));
        registry.registerKey(BEEF_PUBX, BEEF_PUBY, BEEF_AX, BEEF_AY, BEEF_Z);
        verifier = new MockContributionVerifier();
        partialVerifier = new MockPartialDecryptVerifier();
        poolKeyVerifier = new MockPoolKeyVerifier();
        decryptCombineVerifier = new MockDecryptCombineVerifier();
        manager = new DKGManager(
            31337,
            address(registry),
            address(verifier),
            address(partialVerifier),
            address(poolKeyVerifier),
            address(decryptCombineVerifier),
            0,  // epochDurationBlocks → DEFAULT (100)
            0,  // committeeSelectionBlocks → DEFAULT (25)
            0,  // keyAssemblyBlocks → DEFAULT (25)
            0,  // finalizeGapBlocks → DEFAULT (5)
            0, 0, 0 // policy floors → permissive defaults
        );
        // Wire the liveness callback so submitContribution can refresh
        // the contributor's lastActiveBlock on the registry.
        registry.setManager(address(manager));
        appManager = new DKGAppManager(address(manager));
        manager.setAppManager(address(appManager));
        // Operators only enter lotteries of epochs created after they registered.
        vm.roll(block.number + 1);
    }

    // ─── Lifecycle helpers ────────────────────────────────────────────────────

    function createSelectedRound() internal returns (bytes12 epochId) {
        epochId = _createLotteryRound();
        _claimAllSlots(epochId);
    }

    /// @dev Creates a epoch with a lottery threshold of "everyone passes" so the two
    /// registered test nodes (address(this) and 0xBEEF) are both eligible.
    /// All phase deadlines are derived from the contract's
    /// `EPOCH_DURATION_BLOCKS` (100 in the default-deploy test fixture).
    function _createLotteryRound() internal returns (bytes12 epochId) {
        // Permissionless cadence: roll forward to nextEpochStartBlock if
        // a previous epoch was just created in this same test.
        uint64 next = manager.nextEpochStartBlock();
        if (block.number < uint256(next)) vm.roll(uint256(next));
        // α = 1.0 (10000 bps), committeeSize = 2, registered = 2 → all pass.
        epochId = manager.createEpoch(2, 2, 2, 10000);
        // Advance past seedBlock so blockhash is available.
        vm.roll(block.number + 2);
    }

    function _claimAllSlots(bytes12 epochId) internal {
        vm.prank(alice);
        manager.claimSlot(epochId);
        vm.prank(address(0xBEEF));
        manager.claimSlot(epochId);
    }

    /// @dev Advance to a block at or after `liveNotBeforeBlock` for the epoch.
    function _advanceToFinalize(bytes12 epochId) internal {
        IDKGManager.Epoch memory r = manager.getEpoch(epochId);
        if (block.number < uint256(r.policy.liveNotBeforeBlock)) {
            vm.roll(uint256(r.policy.liveNotBeforeBlock));
        }
    }

    /// @dev Contributions must come from a direct EOA call: prank with
    ///      matching msg.sender/tx.origin (a single-arg prank leaves
    ///      tx.origin untouched and trips DirectCallRequired).
    function _submitContribution(bytes12 epochId, uint16 idx) internal {
        address who = idx == 2 ? address(0xBEEF) : alice;
        vm.prank(who, who);
        manager.submitContribution(
            epochId,
            idx,
            contributorCommitmentsHash(idx),
            contributorSharesHash(idx),
            contributionTranscript(2),
            contributionProof(),
            contributionInput(epochId, 2, 2, idx, contributorCommitmentsHash(idx), contributorSharesHash(idx))
        );
    }

    function _submitBothContributions(bytes12 epochId) internal {
        _submitContribution(epochId, 1);
        _submitContribution(epochId, 2);
    }

    /// @dev Prove pool key `keyIndex` of a Live epoch with two accepted
    ///      contributors out of a committee of two. Permissionless, but
    ///      still a direct EOA call (see _submitContribution).
    function _activateKey(bytes12 epochId, uint8 keyIndex) internal {
        vm.prank(alice, alice);
        manager.activatePoolKey(
            epochId,
            keyIndex,
            testTranscriptDigest(keyIndex),
            poolKeyTranscript(keyIndex, 2, 2),
            poolKeyProof(),
            poolKeyInput(epochId, 2, 2, 2, keyIndex)
        );
    }

    /// @dev `activatePoolKey` over an explicit (possibly tampered) word vector
    ///      with a consistent challenge and BRLC commitment.
    function _activateKeyWithWords(bytes12 epochId, uint8 keyIndex, uint256[] memory words) internal {
        bytes memory input = poolKeyInputForWords(epochId, 2, 2, 2, keyIndex, words);
        vm.prank(alice, alice);
        manager.activatePoolKey(
            epochId, keyIndex, testTranscriptDigest(keyIndex), abi.encodePacked(words), poolKeyProof(), input
        );
    }

    /// @dev An epoch driven all the way to Live with pool key 0 activated.
    function createLiveRound() internal returns (bytes12 epochId) {
        epochId = createSelectedRound();
        _submitBothContributions(epochId);
        _advanceToFinalize(epochId);
        manager.finalizeEpoch(epochId);
        _activateKey(epochId, 0);
    }

    /// @dev The canonical fixture: Live epoch, key 0 activated and claimed by
    ///      `TEST_AID` (an `OrganizerLocked` application whose secret is
    ///      already revealed, so partials and combines are open), one
    ///      ciphertext submitted at index 1.
    function createFinalizedRound() internal returns (bytes12 epochId) {
        epochId = createLiveRound();
        _registerTestApp(epochId, TEST_AID);
        appManager.revealOrganizerSecret(epochId, TEST_AID, TEST_ORG_SK);
        _submitTestCiphertext(epochId, TEST_AID);
    }

    /// @dev Register `aid` under the canonical test organizer key, with an
    ///      all-zero policy (which resolves the authorized submitter to the
    ///      caller — address(this) unless pranked).
    function _registerTestApp(bytes12 epochId, bytes32 aid) internal {
        (uint256 pkx, uint256 pky, uint256 ax, uint256 ay, uint256 z) = organizerPoP(epochId, aid);
        appManager.registerApplication(epochId, aid, _emptyAppPolicy(), pkx, pky, ax, ay, z);
    }

    function _emptyAppPolicy() internal pure returns (DKGTypes.AppPolicy memory) {
        return DKGTypes.AppPolicy({
            mode: DKGTypes.AppMode.OrganizerLocked,
            openSubmission: false,
            submitters: new address[](0),
            maxCiphertexts: 0,
            notBeforeBlock: 0,
            notAfterBlock: 0,
            decryptNotBefore: 0,
            decryptNotAfter: 0
        });
    }

    function _submitTestCiphertext(bytes12 epochId, bytes32 aid) internal returns (uint16) {
        return manager.submitCiphertext(epochId, aid, TEST_CT_C1X, TEST_CT_C1Y, TEST_CT_C2X, TEST_CT_C2Y);
    }

    function _submitPartial(bytes12 epochId, bytes32 aid, uint16 pIdx, uint16 ctIdx) internal {
        uint8 keyIndex = manager.getAppPoolIndex(epochId, aid);
        vm.prank(pIdx == 2 ? address(0xBEEF) : alice);
        manager.submitPartialDecryption(
            epochId, aid, pIdx, ctIdx,
            TEST_CT_C1X, TEST_CT_C1Y, TEST_CT_C2X, TEST_CT_C2Y,
            partialDecryptionHash(pIdx),
            partialDecryptionProof(),
            partialDecryptionInput(epochId, aid, pIdx, ctIdx, keyIndex),
            shareProofFor(keyIndex, 2, pIdx)
        );
    }

    /// @dev Both committee members post their partial decryption of
    ///      `ciphertextIndex` under `aid`.
    function _submitBothPartials(bytes12 epochId, bytes32 aid, uint16 ctIdx) internal {
        _submitPartial(epochId, aid, 1, ctIdx);
        _submitPartial(epochId, aid, 2, ctIdx);
    }

    // ─── Epoch creation and lottery ───────────────────────────────────────────

    function test_CreateEpoch_PersistsPolicy() public {
        // committeeSize=2, registered=2, α=1.0 → all eligible
        bytes12 epochId = manager.createEpoch(2, 2, 2, 10000);

        IDKGManager.Epoch memory epoch = manager.getEpoch(epochId);

        assertEq(epoch.organizer, address(this));
        assertEq(uint256(epoch.policy.threshold), 2);
        assertEq(uint256(epoch.policy.committeeSize), 2);
        assertEq(uint256(epoch.status), uint256(DKGTypes.EpochPhase.CommitteeSelection));
    }

    function test_ClaimSlot_RejectsBeforeSeedReady() public {
        bytes12 epochId = manager.createEpoch(2, 2, 2, 10000);
        // Don't roll forward — seed block has not been mined yet.
        vm.expectRevert(IDKGManager.SeedNotReady.selector);
        manager.claimSlot(epochId);
    }

    function test_ClaimSlot_RejectsDuplicates() public {
        bytes12 epochId = _createLotteryRound();
        vm.prank(alice);
        manager.claimSlot(epochId);
        vm.expectRevert(IDKGManager.AlreadyClaimed.selector);
        vm.prank(alice);
        manager.claimSlot(epochId);
    }

    function test_ClaimSlot_FillsCommitteeAndAdvancesPhase() public {
        bytes12 epochId = _createLotteryRound();
        _claimAllSlots(epochId);

        IDKGManager.Epoch memory epoch = manager.getEpoch(epochId);
        address[] memory selected = manager.selectedParticipants(epochId);

        assertEq(uint256(epoch.status), uint256(DKGTypes.EpochPhase.KeyAssembly));
        assertEq(selected.length, 2);
        assertEq(selected[0], alice);
        assertEq(selected[1], address(0xBEEF));
    }

    /// @dev Filling the committee publishes the members' keys in the
    ///      CommitteeSnapshot event: nodes build contribution witnesses
    ///      from that frozen view instead of the live registry, so a later
    ///      updateKey rotation cannot desync an honest contributor from the
    ///      on-chain prefix hash.
    function test_ClaimSlot_EmitsCommitteeSnapshot() public {
        vm.recordLogs();
        bytes12 epochId = createSelectedRound();

        bytes32 topic = keccak256("CommitteeSnapshot(bytes12,uint16,uint256[])");
        Vm.Log[] memory logs = vm.getRecordedLogs();
        bool found;
        for (uint256 i = 0; i < logs.length; i++) {
            if (logs[i].topics.length != 2 || logs[i].topics[0] != topic) continue;
            assertEq(logs[i].emitter, address(manager));
            assertEq(uint256(bytes32(bytes12(epochId))), uint256(logs[i].topics[1]));
            (uint16 committeeSize, uint256[] memory pubKeys) = abi.decode(logs[i].data, (uint16, uint256[]));
            assertEq(uint256(committeeSize), 2);
            assertEq(pubKeys.length, 4);
            assertEq(pubKeys[0], ALICE_PUBX);
            assertEq(pubKeys[1], ALICE_PUBY);
            assertEq(pubKeys[2], BEEF_PUBX);
            assertEq(pubKeys[3], BEEF_PUBY);
            found = true;
        }
        assertTrue(found);
    }

    function test_ClaimSlot_RejectsAfterSlotsFull() public {
        bytes12 epochId = _createLotteryRound();
        _claimAllSlots(epochId);
        // epoch.status is now KeyAssembly, so further claimSlot calls should revert
        // on phase, not on slots-full (we never reach the slots-full check).
        vm.prank(address(0xCAFE));
        vm.expectRevert(IDKGManager.InvalidPhase.selector);
        manager.claimSlot(epochId);
    }

    function test_GetContributionVerifierVKeyHash() public view {
        assertEq(uint256(manager.getContributionVerifierVKeyHash()), uint256(CONTRIBUTION_PROVING_KEY_HASH));
    }

    function test_GetPartialDecryptVerifierVKeyHash() public view {
        assertEq(uint256(manager.getPartialDecryptVerifierVKeyHash()), uint256(PARTIAL_DECRYPTION_PROVING_KEY_HASH));
    }

    function test_GetPoolKeyVerifierVKeyHash() public view {
        assertEq(uint256(manager.getPoolKeyVerifierVKeyHash()), uint256(POOLKEY_PROVING_KEY_HASH));
    }

    // ─── Contribution ─────────────────────────────────────────────────────────

    /// @dev The record now stores the Poseidon `commitmentsHash` (public input
    ///      4), which is exactly what `activatePoolKey` re-checks per row.
    function test_SubmitContribution_PersistsRecord() public {
        bytes12 epochId = createSelectedRound();
        _submitContribution(epochId, 1);

        DKGTypes.ContributionRecord memory record = manager.getContribution(epochId, alice);
        IDKGManager.Epoch memory epoch = manager.getEpoch(epochId);

        assertEq(uint256(record.contributorIndex), 1);
        assertEq(uint256(record.commitmentsHash), uint256(CONTRIBUTION_COMMITMENTS_HASH));
        assertTrue(record.accepted);
        assertEq(uint256(epoch.contributionCount), 1);
    }

    function test_SubmitContribution_RejectsUnselectedOperator() public {
        bytes12 epochId = createSelectedRound();

        vm.prank(address(0xCAFE), address(0xCAFE));
        vm.expectRevert(IDKGManager.NotSelectedParticipant.selector);
        manager.submitContribution(
            epochId, 1, contributorCommitmentsHash(1), contributorSharesHash(1),
            contributionTranscript(2), contributionProof(),
            contributionInput(epochId, 2, 2, 1, contributorCommitmentsHash(1), contributorSharesHash(1))
        );
    }

    function test_SubmitContribution_RejectsDuplicates() public {
        bytes12 epochId = createSelectedRound();
        _submitContribution(epochId, 1);

        vm.expectRevert(IDKGManager.AlreadyContributed.selector);
        vm.prank(alice, alice);
        manager.submitContribution(
            epochId, 1, contributorCommitmentsHash(1), contributorSharesHash(1),
            contributionTranscript(2), contributionProof(),
            contributionInput(epochId, 2, 2, 1, contributorCommitmentsHash(1), contributorSharesHash(1))
        );
    }

    function test_SubmitContribution_RejectsBadProofInput() public {
        bytes12 epochId = createSelectedRound();

        // The manager validates cheap public-input bindings before invoking
        // the verifier, so a tampered input vector reverts with the manager's
        // own InvalidProofInput rather than the verifier's.
        vm.expectRevert(IDKGManager.InvalidProofInput.selector);
        vm.prank(alice, alice);
        manager.submitContribution(
            epochId, 1, contributorCommitmentsHash(1), contributorSharesHash(1),
            contributionTranscript(2), contributionProof(),
            CONTRIBUTION_INPUT_BAD
        );
    }

    /// @dev The committee section of the transcript lives at
    ///      `[2KN, 2KN+3N)`; a transcript whose committee prefix does not match
    ///      the lottery snapshot is rejected regardless of the proof. The
    ///      challenge and BRLC commitment are recomputed over the altered
    ///      words so the call gets past Fiat–Shamir and the mock verifier and
    ///      it is the prefix check that rejects.
    function test_SubmitContribution_RejectsWrongCommitteePrefix() public {
        bytes12 epochId = createSelectedRound();
        uint256[] memory words = contributionWords(2);
        words[2 * MAX_K * MAX_N] = 7; // recipientIndexes[0] should be 1
        bytes memory input = contributionInputForWords(
            epochId, 2, 2, 1, contributorCommitmentsHash(1), contributorSharesHash(1), words
        );
        vm.expectRevert(IDKGManager.InvalidProofInput.selector);
        vm.prank(alice, alice);
        manager.submitContribution(
            epochId, 1, contributorCommitmentsHash(1), contributorSharesHash(1),
            abi.encodePacked(words), contributionProof(), input
        );
        // The same envelope with the honest prefix lands: nothing else was off.
        _submitContribution(epochId, 1);
        assertTrue(manager.getContribution(epochId, alice).accepted);
    }

    /// @dev A transcript word at or above the scalar-field modulus commits
    ///      exactly like its reduction, so the contract must refuse it rather
    ///      than store the raw value. Here a masked share carries `v + p`.
    function test_SubmitContribution_RejectsNonCanonicalWord() public {
        bytes12 epochId = createSelectedRound();
        uint256[] memory words = contributionWords(2);
        uint256 msBase = 2 * MAX_K * MAX_N + 5 * MAX_N;
        words[msBase] = words[msBase] + FR_MOD;
        bytes memory input = contributionInputForWords(
            epochId, 2, 2, 1, contributorCommitmentsHash(1), contributorSharesHash(1), words
        );
        vm.expectRevert(BRLC.TranscriptWordNotInField.selector);
        vm.prank(alice, alice);
        manager.submitContribution(
            epochId, 1, contributorCommitmentsHash(1), contributorSharesHash(1),
            abi.encodePacked(words), contributionProof(), input
        );
    }

    function test_SubmitContribution_RefreshesLastActiveBlock() public {
        bytes12 epochId = createSelectedRound();

        uint64 before = registry.getNode(alice).lastActiveBlock;
        vm.roll(block.number + 10);
        _submitContribution(epochId, 1);

        uint64 afterBlock = registry.getNode(alice).lastActiveBlock;
        assertEq(uint256(afterBlock), block.number);
        assertTrue(afterBlock > before);
    }

    // ─── Direct EOA-call gate ────────────────────────────────────────────────

    /// @dev A contract-relayed submitContribution reverts before any other
    ///      check: nodes and the SDK rebuild contributions from the outer
    ///      transaction calldata, which an internal call never carries. The
    ///      nonsense epoch and empty proof bytes prove the ordering — only
    ///      the caller is wrong.
    function test_SubmitContribution_RejectsContractCaller() public {
        DirectCallForwarder forwarder = new DirectCallForwarder();
        vm.expectRevert(IDKGManager.DirectCallRequired.selector);
        forwarder.submit(
            address(manager),
            bytes12(uint96(0xDEAD)),
            1,
            bytes32(0),
            bytes32(0),
            "",
            "",
            ""
        );
    }

    /// @dev Same gate on activatePoolKey, over a fully valid activation
    ///      envelope: only the caller is wrong.
    function test_ActivatePoolKey_RejectsContractCaller() public {
        bytes12 epochId = createLiveRound();
        DirectCallForwarder forwarder = new DirectCallForwarder();
        vm.expectRevert(IDKGManager.DirectCallRequired.selector);
        forwarder.activate(
            address(manager),
            epochId,
            1,
            testTranscriptDigest(1),
            poolKeyTranscript(1, 2, 2),
            poolKeyProof(),
            poolKeyInput(epochId, 2, 2, 2, 1)
        );
    }

    // ─── finalizeEpoch (proof-less) ──────────────────────────────────────────

    function test_FinalizeEpoch_SetsLive() public {
        bytes12 epochId = createSelectedRound();
        _submitBothContributions(epochId);
        _advanceToFinalize(epochId);
        manager.finalizeEpoch(epochId);

        IDKGManager.Epoch memory epoch = manager.getEpoch(epochId);
        assertEq(uint256(epoch.status), uint256(DKGTypes.EpochPhase.Live));
        assertEq(uint256(epoch.contributionCount), 2);
        // Nothing is activated or claimed yet.
        (uint8 nextIndex, uint8 activated) = manager.getPoolStatus(epochId);
        assertEq(uint256(nextIndex), 0);
        assertEq(uint256(activated), 0);
    }

    function test_FinalizeEpoch_RejectsTwice() public {
        bytes12 epochId = createLiveRound();
        vm.expectRevert(IDKGManager.AlreadyLive.selector);
        manager.finalizeEpoch(epochId);
    }

    function test_FinalizeEpoch_RejectsInsufficientContributions() public {
        bytes12 epochId = createSelectedRound();
        _submitContribution(epochId, 1);
        _advanceToFinalize(epochId);

        vm.expectRevert(IDKGManager.InsufficientContributions.selector);
        manager.finalizeEpoch(epochId);
    }

    function test_FinalizeEpoch_RejectsBeforeFinalizeNotBeforeBlock() public {
        bytes12 epochId = createSelectedRound();
        _submitBothContributions(epochId);

        // Both contributions in, threshold met — but liveNotBeforeBlock
        // not yet reached. Must revert with InvalidPhase (the gate reuses this
        // selector to keep the contract under the EIP-170 size limit).
        IDKGManager.Epoch memory r = manager.getEpoch(epochId);
        assertTrue(block.number < uint256(r.policy.liveNotBeforeBlock));

        vm.expectRevert(IDKGManager.InvalidPhase.selector);
        manager.finalizeEpoch(epochId);

        // Roll exactly to liveNotBeforeBlock — should succeed.
        vm.roll(uint256(r.policy.liveNotBeforeBlock));
        manager.finalizeEpoch(epochId);
        assertEq(uint256(manager.getEpoch(epochId).status), uint256(DKGTypes.EpochPhase.Live));
    }

    // ─── activatePoolKey ─────────────────────────────────────────────────────

    /// @dev The activation stores `aggregateCommitments[0]` as `P_j` and the
    ///      Merkle root over the committee's share commitments. The root is
    ///      recomputed independently by the test.
    function test_ActivatePoolKey_PersistsKeyAndShareRoot() public {
        bytes12 epochId = createSelectedRound();
        _submitBothContributions(epochId);
        _advanceToFinalize(epochId);
        manager.finalizeEpoch(epochId);

        _activateKey(epochId, 0);
        _activateKey(epochId, 3);

        (uint256 x0, uint256 y0) = manager.getPoolKey(epochId, 0);
        (uint256 e0x, uint256 e0y) = testPoolKey(0);
        assertEq(x0, e0x);
        assertEq(y0, e0y);
        (uint256 x3, uint256 y3) = manager.getPoolKey(epochId, 3);
        (uint256 e3x, uint256 e3y) = testPoolKey(3);
        assertEq(x3, e3x);
        assertEq(y3, e3y);

        assertEq(uint256(manager.getPoolShareRoot(epochId, 0)), uint256(expectedShareRoot(0, 2)));
        assertEq(uint256(manager.getPoolShareRoot(epochId, 3)), uint256(expectedShareRoot(3, 2)));
        // Distinct keys must produce distinct roots, or a partial decryption
        // for one application would verify against another's.
        assertTrue(manager.getPoolShareRoot(epochId, 0) != manager.getPoolShareRoot(epochId, 3));

        (uint8 nextIndex, uint8 activated) = manager.getPoolStatus(epochId);
        assertEq(uint256(nextIndex), 0);
        assertEq(uint256(activated), (1 << 0) | (1 << 3));
    }

    function test_ActivatePoolKey_RejectsTwice() public {
        bytes12 epochId = createLiveRound();
        vm.expectRevert(IDKGManager.PoolKeyAlreadyActive.selector);
        _activateKey(epochId, 0);
    }

    function test_ActivatePoolKey_RejectsKeyIndexOutOfRange() public {
        bytes12 epochId = createLiveRound();
        uint8 tooBig = uint8(MAX_K);
        bytes memory transcript = poolKeyTranscript(tooBig, 2, 2);
        bytes memory input = poolKeyInput(epochId, 2, 2, 2, tooBig);
        vm.expectRevert(IDKGManager.InvalidProofInput.selector);
        vm.prank(alice, alice);
        manager.activatePoolKey(epochId, tooBig, testTranscriptDigest(tooBig), transcript, poolKeyProof(), input);
    }

    function test_ActivatePoolKey_RejectsBeforeLive() public {
        bytes12 epochId = createSelectedRound();
        _submitBothContributions(epochId);
        bytes memory transcript = poolKeyTranscript(0, 2, 2);
        bytes memory input = poolKeyInput(epochId, 2, 2, 2, 0);
        vm.expectRevert(IDKGManager.InvalidPhase.selector);
        vm.prank(alice, alice);
        manager.activatePoolKey(epochId, 0, testTranscriptDigest(0), transcript, poolKeyProof(), input);
    }

    /// @dev A transcript with duplicated participant indexes ([1, 1] instead
    ///      of [1, 2]) must be rejected even though both contributions are
    ///      accepted: otherwise the proof aggregates over the wrong set.
    function test_ActivatePoolKey_RejectsDuplicateParticipantRows() public {
        bytes12 epochId = createSelectedRound();
        _submitBothContributions(epochId);
        _advanceToFinalize(epochId);
        manager.finalizeEpoch(epochId);

        uint256[] memory words = poolKeyWords(1, 2, 2);
        words[1] = 1;                                                 // participantIndexes = [1, 1]
        words[MAX_N + 1] = uint256(contributorCommitmentsHash(1));    // …with row 1's hash
        vm.expectRevert(IDKGManager.InvalidProofInput.selector);
        _activateKeyWithWords(epochId, 1, words);
    }

    /// @dev Each row must carry the contributor's own on-chain
    ///      `commitmentsHash`; swapping one in binds the activation to
    ///      commitments that were never accepted.
    function test_ActivatePoolKey_RejectsWrongContributionHash() public {
        bytes12 epochId = createLiveRound();

        uint256[] memory words = poolKeyWords(1, 2, 2);
        words[MAX_N] = uint256(contributorCommitmentsHash(1)) + 99;
        vm.expectRevert(IDKGManager.InvalidProofInput.selector);
        _activateKeyWithWords(epochId, 1, words);
    }

    function test_ActivatePoolKey_RejectsUnknownParticipantIndex() public {
        bytes12 epochId = createLiveRound();

        uint256[] memory words = poolKeyWords(1, 2, 2);
        words[0] = 3; // committeeSize is 2
        vm.expectRevert(IDKGManager.InvalidProofInput.selector);
        _activateKeyWithWords(epochId, 1, words);
    }

    function test_ActivatePoolKey_RejectsWrongTranscriptLength() public {
        bytes12 epochId = createLiveRound();
        bytes memory input = poolKeyInput(epochId, 2, 2, 2, 1);
        vm.expectRevert(IDKGManager.InvalidProofInput.selector);
        vm.prank(alice, alice);
        manager.activatePoolKey(epochId, 1, testTranscriptDigest(1), hex"1234", poolKeyProof(), input);
    }

    /// @dev Rows beyond `contributionCount` and share slots beyond
    ///      `committeeSize` must be blank. A stray participant index, a stray
    ///      contribution hash or a non-identity share commitment in an
    ///      inactive slot each reject the activation, even though the
    ///      challenge and BRLC commitment are consistent with the words.
    function test_ActivatePoolKey_RejectsNonZeroInactiveRow() public {
        bytes12 epochId = createLiveRound();

        uint256[] memory words = poolKeyWords(1, 2, 2);
        words[2] = 1; // participantIndexes[2], contributionCount is 2
        vm.expectRevert(IDKGManager.InvalidProofInput.selector);
        _activateKeyWithWords(epochId, 1, words);

        words = poolKeyWords(1, 2, 2);
        words[MAX_N + 2] = 1; // contributionHashes[2]
        vm.expectRevert(IDKGManager.InvalidProofInput.selector);
        _activateKeyWithWords(epochId, 1, words);

        words = poolKeyWords(1, 2, 2);
        words[4 * MAX_N + 2 * 2] = 1; // shareCommitments[2].x, committeeSize is 2
        vm.expectRevert(IDKGManager.InvalidProofInput.selector);
        _activateKeyWithWords(epochId, 1, words);

        words = poolKeyWords(1, 2, 2);
        words[4 * MAX_N + 2 * 2 + 1] = 0; // shareCommitments[2].y must be 1
        vm.expectRevert(IDKGManager.InvalidProofInput.selector);
        _activateKeyWithWords(epochId, 1, words);

        // The untouched vector still activates.
        _activateKeyWithWords(epochId, 1, poolKeyWords(1, 2, 2));
        assertEq(uint256(manager.getPoolShareRoot(epochId, 1)), uint256(expectedShareRoot(1, 2)));
    }

    /// @dev `acceptedCount` (public input 3) must equal the frozen
    ///      `contributionCount`: an activation aggregating over fewer rows
    ///      than were accepted would publish a key nobody holds shares of.
    function test_ActivatePoolKey_RejectsAcceptedCountMismatch() public {
        bytes12 epochId = createLiveRound(); // contributionCount == 2
        uint256[] memory words = poolKeyWords(1, 1, 2);
        bytes memory input = poolKeyInputForWords(epochId, 2, 2, 1, 1, words);
        vm.expectRevert(IDKGManager.InvalidProofInput.selector);
        vm.prank(alice, alice);
        manager.activatePoolKey(
            epochId, 1, testTranscriptDigest(1), abi.encodePacked(words), poolKeyProof(), input
        );
    }

    /// @dev The digest argument must be the proof's public input 5: it is
    ///      what the challenge anchor commits to.
    function test_ActivatePoolKey_RejectsDigestMismatch() public {
        bytes12 epochId = createLiveRound();
        bytes memory transcript = poolKeyTranscript(1, 2, 2);
        bytes memory input = poolKeyInput(epochId, 2, 2, 2, 1);
        bytes32 other = bytes32(uint256(testTranscriptDigest(1)) ^ 1);
        vm.expectRevert(IDKGManager.InvalidProofInput.selector);
        vm.prank(alice, alice);
        manager.activatePoolKey(epochId, 1, other, transcript, poolKeyProof(), input);
        // A challenge derived from the other digest is rejected just the same.
        bytes memory otherInput = poolKeyInputForDigest(epochId, 2, 2, 2, 1, other, poolKeyWords(1, 2, 2));
        vm.expectRevert(IDKGManager.InvalidProofInput.selector);
        vm.prank(alice, alice);
        manager.activatePoolKey(epochId, 1, testTranscriptDigest(1), transcript, poolKeyProof(), otherInput);
    }

    /// @dev `D_1.x + p` commits like `D_1.x` but would be hashed raw into the
    ///      share root, bricking the key for member 1. The activation must
    ///      refuse the non-canonical word outright.
    function test_ActivatePoolKey_RejectsNonCanonicalWord() public {
        bytes12 epochId = createLiveRound();
        uint256[] memory words = poolKeyWords(1, 2, 2);
        words[4 * MAX_N] = words[4 * MAX_N] + FR_MOD;
        vm.expectRevert(BRLC.TranscriptWordNotInField.selector);
        _activateKeyWithWords(epochId, 1, words);
    }

    function test_GetPoolKey_RevertsWhenNotActivated() public {
        bytes12 epochId = createLiveRound();
        vm.expectRevert(IDKGManager.PoolKeyNotActive.selector);
        manager.getPoolKey(epochId, 1);
    }

    // ─── Pool claim ──────────────────────────────────────────────────────────

    /// @dev Registrations take the epoch's keys in order, one each.
    function test_ClaimPoolKey_AssignsKeysInOrder() public {
        bytes12 epochId = createLiveRound();
        _activateKey(epochId, 1);
        _activateKey(epochId, 2);

        _registerTestApp(epochId, bytes32(uint256(101)));
        _registerTestApp(epochId, bytes32(uint256(102)));
        _registerTestApp(epochId, bytes32(uint256(103)));

        assertEq(uint256(manager.getAppPoolIndex(epochId, bytes32(uint256(101)))), 0);
        assertEq(uint256(manager.getAppPoolIndex(epochId, bytes32(uint256(102)))), 1);
        assertEq(uint256(manager.getAppPoolIndex(epochId, bytes32(uint256(103)))), 2);
        assertEq(uint256(appManager.getApplication(epochId, bytes32(uint256(103))).poolIndex), 2);

        (uint8 nextIndex,) = manager.getPoolStatus(epochId);
        assertEq(uint256(nextIndex), 3);
    }

    /// @dev The next key must be activated before it can be claimed: an
    ///      application must never hold a key nobody can decrypt under.
    function test_ClaimPoolKey_RejectsWhenNextKeyNotActivated() public {
        bytes12 epochId = createLiveRound(); // only key 0 is activated
        _registerTestApp(epochId, bytes32(uint256(201)));

        bytes32 aid = bytes32(uint256(202));
        (uint256 pkx, uint256 pky, uint256 ax, uint256 ay, uint256 z) = organizerPoP(epochId, aid);
        DKGTypes.AppPolicy memory policy = _emptyAppPolicy();
        vm.expectRevert(IDKGManager.PoolKeyNotActive.selector);
        appManager.registerApplication(epochId, aid, policy, pkx, pky, ax, ay, z);
    }

    /// @dev An epoch deals exactly MAX_K keys; the (MAX_K + 1)-th application
    ///      has to wait for the next epoch.
    function test_ClaimPoolKey_RejectsWhenPoolExhausted() public {
        bytes12 epochId = createLiveRound();
        for (uint8 j = 1; j < uint8(MAX_K); j++) {
            _activateKey(epochId, j);
        }
        DKGTypes.AppPolicy memory policy = _emptyAppPolicy();
        policy.mode = DKGTypes.AppMode.Automatic;
        for (uint256 i = 0; i < MAX_K; i++) {
            appManager.registerApplication(epochId, bytes32(0x300 + i), policy, 0, 0, 0, 0, 0);
        }
        (uint8 nextIndex,) = manager.getPoolStatus(epochId);
        assertEq(uint256(nextIndex), MAX_K);

        vm.expectRevert(IDKGManager.PoolExhausted.selector);
        appManager.registerApplication(epochId, bytes32(uint256(0x3FF)), policy, 0, 0, 0, 0, 0);
    }

    function test_ClaimPoolKey_RejectsDirectCall() public {
        bytes12 epochId = createLiveRound();
        vm.expectRevert(IDKGManager.Unauthorized.selector);
        manager.claimPoolKey(epochId, bytes32(uint256(1)));
    }

    function test_GetAppPoolIndex_RevertsForUnclaimedAid() public {
        bytes12 epochId = createLiveRound();
        vm.expectRevert(IDKGManager.PoolKeyNotActive.selector);
        manager.getAppPoolIndex(epochId, bytes32(uint256(0xDEAD)));
    }

    // ─── createEpoch cadence ─────────────────────────────────────────────────

    function test_CreateEpoch_RejectsBeforeNextEpochStartBlock() public {
        // First epoch goes through (cadence guard satisfied — no prior
        // epoch). Second call before nextEpochStartBlock() reverts.
        manager.createEpoch(2, 2, 2, 10000);
        // We are far before lastEpochStartBlock + EPOCH_DURATION_BLOCKS now.
        vm.expectRevert(IDKGManager.InvalidPhase.selector);
        manager.createEpoch(2, 2, 2, 10000);
        // Roll past the cadence threshold and try again — must succeed.
        vm.roll(uint256(manager.nextEpochStartBlock()));
        manager.createEpoch(2, 2, 2, 10000);
    }

    /// @dev With only one unclaimed key left the next epoch may be minted
    ///      ahead of the cadence, so registrations never stall.
    function test_CreateEpoch_AllowedEarlyWhenPoolNearlyExhausted() public {
        bytes12 epochId = createLiveRound();
        for (uint8 j = 1; j < uint8(MAX_K); j++) {
            _activateKey(epochId, j);
        }
        DKGTypes.AppPolicy memory policy = _emptyAppPolicy();
        policy.mode = DKGTypes.AppMode.Automatic;

        // MAX_K - 2 claims: still two keys left, the cadence still binds.
        for (uint256 i = 0; i < MAX_K - 2; i++) {
            appManager.registerApplication(epochId, bytes32(0x400 + i), policy, 0, 0, 0, 0, 0);
        }
        assertTrue(block.number < uint256(manager.nextEpochStartBlock()));
        vm.expectRevert(IDKGManager.InvalidPhase.selector);
        manager.createEpoch(2, 2, 2, 10000);

        // One more claim leaves a single key: createEpoch opens early.
        appManager.registerApplication(epochId, bytes32(uint256(0x4FF)), policy, 0, 0, 0, 0, 0);
        (uint8 nextIndex,) = manager.getPoolStatus(epochId);
        assertEq(uint256(nextIndex), MAX_K - 1);
        assertTrue(block.number < uint256(manager.nextEpochStartBlock()));
        manager.createEpoch(2, 2, 2, 10000);
    }

    /// @dev An aborted epoch serves nobody, so the next one may start at
    ///      once; an epoch still in preparation — even a provably dead one
    ///      nobody has aborted yet — keeps the cadence.
    function test_CreateEpoch_AllowedEarlyWhenNewestAborted() public {
        bytes12 epochId = manager.createEpoch(2, 2, 2, 10000);
        IDKGManager.Epoch memory epoch = manager.getEpoch(epochId);

        // Still in CommitteeSelection: forbidden.
        vm.roll(block.number + 2);
        assertTrue(block.number < uint256(manager.nextEpochStartBlock()));
        vm.expectRevert(IDKGManager.InvalidPhase.selector);
        manager.createEpoch(2, 2, 2, 10000);

        // Dead but not yet aborted: still forbidden.
        vm.roll(uint256(epoch.policy.committeeSelectionDeadlineBlock) + 1);
        assertTrue(block.number < uint256(manager.nextEpochStartBlock()));
        vm.expectRevert(IDKGManager.InvalidPhase.selector);
        manager.createEpoch(2, 2, 2, 10000);

        manager.abortEpoch(epochId);
        bytes12 next = manager.createEpoch(2, 2, 2, 10000);
        assertEq(uint256(manager.getEpoch(next).status), uint256(DKGTypes.EpochPhase.CommitteeSelection));
    }

    /// @dev A Live epoch with keys to spare keeps the cadence too (the
    ///      nearly-exhausted case is covered above).
    function test_CreateEpoch_RejectsEarlyWhileNewestLiveWithKeys() public {
        createLiveRound();
        assertTrue(block.number < uint256(manager.nextEpochStartBlock()));
        vm.expectRevert(IDKGManager.InvalidPhase.selector);
        manager.createEpoch(2, 2, 2, 10000);
    }

    function test_NextEpochStartBlock_AdvancesByDuration() public {
        uint64 dur = uint64(manager.EPOCH_DURATION_BLOCKS());
        // Before any epoch: nextEpochStartBlock() == current block.
        assertEq(uint256(manager.nextEpochStartBlock()), block.number);
        manager.createEpoch(2, 2, 2, 10000);
        assertEq(
            uint256(manager.nextEpochStartBlock()),
            uint256(manager.lastEpochStartBlock()) + uint256(dur)
        );
    }

    // ─── Partial decryption ──────────────────────────────────────────────────

    function test_SubmitPartialDecryption_PersistsRecord() public {
        bytes12 epochId = createFinalizedRound();
        _submitPartial(epochId, TEST_AID, 1, 1);

        DKGTypes.PartialDecryptionRecord memory record = manager.getPartialDecryption(epochId, TEST_AID, 1, 1);
        IDKGManager.Epoch memory epoch = manager.getEpoch(epochId);

        assertEq(uint256(record.participantIndex), 1);
        assertEq(uint256(record.ciphertextIndex), 1);
        assertTrue(record.accepted);
        assertEq(uint256(epoch.partialDecryptionCount), 1);
    }

    function test_SubmitPartialDecryption_RejectsBadProofInput() public {
        bytes12 epochId = createFinalizedRound();
        bytes32[] memory path = shareProofFor(0, 2, 1);

        vm.expectRevert(IDKGManager.InvalidProofInput.selector);
        vm.prank(alice);
        manager.submitPartialDecryption(
            epochId, TEST_AID, 1, 1,
            TEST_CT_C1X, TEST_CT_C1Y, TEST_CT_C2X, TEST_CT_C2Y,
            partialDecryptionHash(1),
            partialDecryptionProof(),
            PARTIAL_DECRYPTION_INPUT_BAD,
            path
        );
    }

    function test_SubmitPartialDecryption_RejectsBeforeFinalization() public {
        bytes12 epochId = createSelectedRound();
        bytes32[] memory path = shareProofFor(0, 2, 1);

        vm.expectRevert(IDKGManager.InvalidPhase.selector);
        vm.prank(alice);
        manager.submitPartialDecryption(
            epochId, TEST_AID, 1, 1,
            TEST_CT_C1X, TEST_CT_C1Y, TEST_CT_C2X, TEST_CT_C2Y,
            partialDecryptionHash(1),
            partialDecryptionProof(),
            partialDecryptionInput(epochId, TEST_AID, 1, 1, 0),
            path
        );
    }

    function test_SubmitPartialDecryption_RejectsDuplicates() public {
        bytes12 epochId = createFinalizedRound();
        _submitPartial(epochId, TEST_AID, 1, 1);

        bytes32[] memory path = shareProofFor(0, 2, 1);
        vm.expectRevert(IDKGManager.AlreadyPartiallyDecrypted.selector);
        vm.prank(alice);
        manager.submitPartialDecryption(
            epochId, TEST_AID, 1, 1,
            TEST_CT_C1X, TEST_CT_C1Y, TEST_CT_C2X, TEST_CT_C2Y,
            partialDecryptionHash(1),
            partialDecryptionProof(),
            partialDecryptionInput(epochId, TEST_AID, 1, 1, 0),
            path
        );
    }

    function test_SubmitPartialDecryption_AllowsDistinctCiphertexts() public {
        bytes12 epochId = createFinalizedRound();
        _submitTestCiphertext(epochId, TEST_AID); // index 2

        _submitPartial(epochId, TEST_AID, 1, 1);
        _submitPartial(epochId, TEST_AID, 1, 2);

        assertEq(uint256(manager.getPartialDecryption(epochId, TEST_AID, 1, 1).ciphertextIndex), 1);
        assertEq(uint256(manager.getPartialDecryption(epochId, TEST_AID, 1, 2).ciphertextIndex), 2);
    }

    /// @dev The Merkle path pins the member to the share it was dealt for THIS
    ///      application's pool key. A path built for a different key — or one
    ///      of the wrong length, or a sibling flipped — is rejected.
    function test_SubmitPartialDecryption_RejectsBadShareProof() public {
        bytes12 epochId = createFinalizedRound();

        // Path from another pool key.
        bytes32[] memory wrongKey = shareProofFor(1, 2, 1);
        vm.expectRevert(IDKGManager.InvalidProofInput.selector);
        vm.prank(alice);
        manager.submitPartialDecryption(
            epochId, TEST_AID, 1, 1,
            TEST_CT_C1X, TEST_CT_C1Y, TEST_CT_C2X, TEST_CT_C2Y,
            partialDecryptionHash(1), partialDecryptionProof(),
            partialDecryptionInput(epochId, TEST_AID, 1, 1, 0), wrongKey
        );

        // Right key, tampered sibling.
        bytes32[] memory tampered = shareProofFor(0, 2, 1);
        tampered[2] = bytes32(uint256(tampered[2]) ^ 1);
        vm.expectRevert(IDKGManager.InvalidProofInput.selector);
        vm.prank(alice);
        manager.submitPartialDecryption(
            epochId, TEST_AID, 1, 1,
            TEST_CT_C1X, TEST_CT_C1Y, TEST_CT_C2X, TEST_CT_C2Y,
            partialDecryptionHash(1), partialDecryptionProof(),
            partialDecryptionInput(epochId, TEST_AID, 1, 1, 0), tampered
        );

        // Wrong length.
        bytes32[] memory short = new bytes32[](MERKLE_DEPTH - 1);
        vm.expectRevert(IDKGManager.InvalidProofInput.selector);
        vm.prank(alice);
        manager.submitPartialDecryption(
            epochId, TEST_AID, 1, 1,
            TEST_CT_C1X, TEST_CT_C1Y, TEST_CT_C2X, TEST_CT_C2Y,
            partialDecryptionHash(1), partialDecryptionProof(),
            partialDecryptionInput(epochId, TEST_AID, 1, 1, 0), short
        );

        // …and the honest one still lands.
        _submitPartial(epochId, TEST_AID, 1, 1);
        assertTrue(manager.getPartialDecryption(epochId, TEST_AID, 1, 1).accepted);
    }

    /// @dev A member cannot submit another member's share commitment: the leaf
    ///      index is derived from `participantIndex`, not from the proof, so
    ///      participant 2's `D` never sits at leaf 0 — whichever path comes
    ///      with it.
    function test_SubmitPartialDecryption_RejectsShareOfAnotherParticipant() public {
        bytes12 epochId = createFinalizedRound();
        (uint256 d2x, uint256 d2y) = testShareCommitment(0, 2);
        // Participant 2's D with participant 1's path, submitted at index 1.
        bytes memory input = partialDecryptionInputWithShare(epochId, TEST_AID, 1, 1, d2x, d2y);
        bytes32[] memory ownPath = shareProofFor(0, 2, 1);
        vm.expectRevert(IDKGManager.InvalidProofInput.selector);
        vm.prank(alice);
        manager.submitPartialDecryption(
            epochId, TEST_AID, 1, 1,
            TEST_CT_C1X, TEST_CT_C1Y, TEST_CT_C2X, TEST_CT_C2Y,
            partialDecryptionHash(1), partialDecryptionProof(), input, ownPath
        );
        // …and with participant 2's own (valid, for leaf 1) path.
        bytes32[] memory theirPath = shareProofFor(0, 2, 2);
        vm.expectRevert(IDKGManager.InvalidProofInput.selector);
        vm.prank(alice);
        manager.submitPartialDecryption(
            epochId, TEST_AID, 1, 1,
            TEST_CT_C1X, TEST_CT_C1Y, TEST_CT_C2X, TEST_CT_C2Y,
            partialDecryptionHash(1), partialDecryptionProof(), input, theirPath
        );
    }

    /// @dev A share dealt for another pool key is useless for this
    ///      application, self-consistent path or not: the application's root
    ///      is the one activated for ITS key.
    function test_SubmitPartialDecryption_RejectsShareFromAnotherKey() public {
        bytes12 epochId = createLiveRound();
        _activateKey(epochId, 1);
        _registerTestApp(epochId, TEST_AID); // claims key 0
        appManager.revealOrganizerSecret(epochId, TEST_AID, TEST_ORG_SK);
        _submitTestCiphertext(epochId, TEST_AID);
        assertEq(uint256(manager.getAppPoolIndex(epochId, TEST_AID)), 0);

        (uint256 dx, uint256 dy) = testShareCommitment(1, 1);
        bytes memory input = partialDecryptionInputWithShare(epochId, TEST_AID, 1, 1, dx, dy);
        // D from key 1 with key 1's (internally valid) path.
        bytes32[] memory pathKey1 = shareProofFor(1, 2, 1);
        vm.expectRevert(IDKGManager.InvalidProofInput.selector);
        vm.prank(alice);
        manager.submitPartialDecryption(
            epochId, TEST_AID, 1, 1,
            TEST_CT_C1X, TEST_CT_C1Y, TEST_CT_C2X, TEST_CT_C2Y,
            partialDecryptionHash(1), partialDecryptionProof(), input, pathKey1
        );
        // D from key 1 with key 0's path.
        bytes32[] memory pathKey0 = shareProofFor(0, 2, 1);
        vm.expectRevert(IDKGManager.InvalidProofInput.selector);
        vm.prank(alice);
        manager.submitPartialDecryption(
            epochId, TEST_AID, 1, 1,
            TEST_CT_C1X, TEST_CT_C1Y, TEST_CT_C2X, TEST_CT_C2Y,
            partialDecryptionHash(1), partialDecryptionProof(), input, pathKey0
        );
        // The share of key 0 lands.
        _submitPartial(epochId, TEST_AID, 1, 1);
    }

    /// @dev Leaves and internal nodes live in separate hash domains (tags
    ///      0x00 / 0x01): a path whose internal levels were folded with the
    ///      leaf tag — i.e. leaf hashes standing in for nodes — does not reach
    ///      the stored root.
    function test_SubmitPartialDecryption_RejectsLeafHashAsInternalNode() public {
        bytes12 epochId = createFinalizedRound();
        bytes32[] memory leafTagged = shareProofWithNodeTag(0, 2, 1, 0);
        bytes32[] memory honest = shareProofFor(0, 2, 1);
        // Level 0 is a sibling leaf in both; the difference starts at level 1.
        assertEq(uint256(leafTagged[0]), uint256(honest[0]));
        assertTrue(leafTagged[1] != honest[1]);
        bytes memory input = partialDecryptionInput(epochId, TEST_AID, 1, 1, 0);
        vm.expectRevert(IDKGManager.InvalidProofInput.selector);
        vm.prank(alice);
        manager.submitPartialDecryption(
            epochId, TEST_AID, 1, 1,
            TEST_CT_C1X, TEST_CT_C1Y, TEST_CT_C2X, TEST_CT_C2Y,
            partialDecryptionHash(1), partialDecryptionProof(), input, leafTagged
        );
    }

    /// @dev Every committee member has a leaf, contributor or not: a member
    ///      that never contributed still holds shares of every key and its
    ///      partial decryption is accepted.
    function test_SubmitPartialDecryption_NonContributingMemberSucceeds() public {
        uint64 next = manager.nextEpochStartBlock();
        if (block.number < uint256(next)) vm.roll(uint256(next));
        // t = 1, n = 2, one valid contribution is enough.
        bytes12 epochId = manager.createEpoch(1, 2, 1, 10000);
        vm.roll(block.number + 2);
        _claimAllSlots(epochId);
        vm.prank(alice, alice);
        manager.submitContribution(
            epochId, 1, contributorCommitmentsHash(1), contributorSharesHash(1),
            contributionTranscript(2), contributionProof(),
            contributionInput(epochId, 1, 2, 1, contributorCommitmentsHash(1), contributorSharesHash(1))
        );
        _advanceToFinalize(epochId);
        manager.finalizeEpoch(epochId);
        assertEq(uint256(manager.getEpoch(epochId).contributionCount), 1);

        // One accepted row, two share slots.
        vm.prank(alice, alice);
        manager.activatePoolKey(
            epochId, 0, testTranscriptDigest(0), poolKeyTranscript(0, 1, 2), poolKeyProof(),
            poolKeyInput(epochId, 1, 2, 1, 0)
        );
        assertEq(uint256(manager.getPoolShareRoot(epochId, 0)), uint256(expectedShareRoot(0, 2)));

        DKGTypes.AppPolicy memory policy = _emptyAppPolicy();
        policy.mode = DKGTypes.AppMode.Automatic;
        appManager.registerApplication(epochId, TEST_AID, policy, 0, 0, 0, 0, 0);
        _submitTestCiphertext(epochId, TEST_AID);

        // Member 2 (0xBEEF) never contributed but is on the committee.
        assertFalse(manager.getContribution(epochId, address(0xBEEF)).accepted);
        _submitPartial(epochId, TEST_AID, 2, 1);
        assertTrue(manager.getPartialDecryption(epochId, TEST_AID, 2, 1).accepted);
        _submitPartial(epochId, TEST_AID, 1, 1);
        assertTrue(manager.getPartialDecryption(epochId, TEST_AID, 1, 1).accepted);
    }

    function test_SubmitPartialDecryption_RejectsCiphertextIndexTooLarge() public {
        bytes12 epochId = createFinalizedRound();
        bytes32[] memory path = shareProofFor(0, 2, 1);

        vm.expectRevert(IDKGManager.InvalidPartialDecryption.selector);
        vm.prank(alice);
        manager.submitPartialDecryption(
            epochId, TEST_AID, 1,
            257, // > MAX_CIPHERTEXT_INDEX (256)
            TEST_CT_C1X, TEST_CT_C1Y, TEST_CT_C2X, TEST_CT_C2Y,
            partialDecryptionHash(1), partialDecryptionProof(),
            partialDecryptionInput(epochId, TEST_AID, 1, 1, 0), path
        );
    }

    function test_SubmitPartialDecryption_RejectsWhenCiphertextNotSubmitted() public {
        bytes12 epochId = createFinalizedRound();
        bytes32[] memory path = shareProofFor(0, 2, 1);

        // createFinalizedRound submits index 1, so use index 2.
        vm.expectRevert(IDKGManager.CiphertextNotSubmitted.selector);
        vm.prank(alice);
        manager.submitPartialDecryption(
            epochId, TEST_AID, 1, 2,
            TEST_CT_C1X, TEST_CT_C1Y, TEST_CT_C2X, TEST_CT_C2Y,
            partialDecryptionHash(1), partialDecryptionProof(),
            partialDecryptionInput(epochId, TEST_AID, 1, 2, 0), path
        );
    }

    // ─── Combine ─────────────────────────────────────────────────────────────

    function test_CombineDecryption_PersistsRecord() public {
        bytes12 epochId = createFinalizedRound();
        _submitBothPartials(epochId, TEST_AID, 1);

        uint256 plaintext = uint256(COMBINED_PLAINTEXT_HASH);
        CombineFixture memory f =
            combineFixture(epochId, TEST_AID, 1, 2, 2, COMBINED_DECRYPTION_HASH, plaintext);
        manager.combineDecryption(
            epochId, TEST_AID, 1, COMBINED_DECRYPTION_HASH, plaintext,
            combineTranscript(f), decryptCombineProof(), combineInput(f)
        );

        DKGTypes.CombinedDecryptionRecord memory record = manager.getCombinedDecryption(epochId, TEST_AID, 1);
        assertTrue(record.completed);
        assertEq(record.plaintext, plaintext);
        assertEq(manager.getPlaintext(epochId, TEST_AID, 1), plaintext);
    }

    /// @dev A locked application accepts ciphertexts from the start but no
    ///      partial and no combine until the organizer publishes `sk_org`:
    ///      `t` partials alone would already fix `P_j`'s half of the
    ///      decryption. After the reveal both go through unchanged in shape —
    ///      the secret is a private witness of the circuit.
    function test_LockedApp_DecryptionRequiresReveal() public {
        bytes12 epochId = createLiveRound();
        bytes32 aid = bytes32(uint256(0x5A1));
        _registerTestApp(epochId, aid);
        _submitTestCiphertext(epochId, aid);
        assertEq(appManager.getApplication(epochId, aid).organizerSecret, 0);

        vm.expectRevert(IDKGAppManager.OrganizerSecretNotRevealed.selector);
        appManager.requireDecryptionOpen(epochId, aid);

        bytes memory input = partialDecryptionInput(epochId, aid, 1, 1, 0);
        bytes32[] memory path = shareProofFor(0, 2, 1);
        vm.expectRevert(IDKGAppManager.OrganizerSecretNotRevealed.selector);
        vm.prank(alice);
        manager.submitPartialDecryption(
            epochId, aid, 1, 1,
            TEST_CT_C1X, TEST_CT_C1Y, TEST_CT_C2X, TEST_CT_C2Y,
            partialDecryptionHash(1), partialDecryptionProof(), input, path
        );
        uint256 plaintext = uint256(COMBINED_PLAINTEXT_HASH);
        CombineFixture memory f = combineFixture(epochId, aid, 1, 2, 2, COMBINED_DECRYPTION_HASH, plaintext);
        bytes memory transcript = combineTranscript(f);
        bytes memory combineIn = combineInput(f);
        vm.expectRevert(IDKGAppManager.OrganizerSecretNotRevealed.selector);
        manager.combineDecryption(
            epochId, aid, 1, COMBINED_DECRYPTION_HASH, plaintext, transcript, decryptCombineProof(), combineIn
        );

        appManager.revealOrganizerSecret(epochId, aid, TEST_ORG_SK);
        assertEq(appManager.getApplication(epochId, aid).organizerSecret, TEST_ORG_SK);
        appManager.requireDecryptionOpen(epochId, aid);
        _submitBothPartials(epochId, aid, 1);
        manager.combineDecryption(
            epochId, aid, 1, COMBINED_DECRYPTION_HASH, plaintext, transcript, decryptCombineProof(), combineIn
        );
        assertEq(manager.getPlaintext(epochId, aid, 1), plaintext);
    }

    /// @dev An `Automatic` application carries the identity as `PK_org`, so
    ///      the very same transcript shape covers it.
    function test_CombineDecryption_AutomaticApp() public {
        bytes12 epochId = createLiveRound();
        bytes32 aid = bytes32(uint256(0x6A1));
        DKGTypes.AppPolicy memory policy = _emptyAppPolicy();
        policy.mode = DKGTypes.AppMode.Automatic;
        appManager.registerApplication(epochId, aid, policy, 0, 0, 0, 0, 0);
        (uint256 pkx, uint256 pky) = appManager.getOrganizerPK(epochId, aid);
        assertEq(pkx, 0);
        assertEq(pky, 1);

        _submitTestCiphertext(epochId, aid);
        _submitBothPartials(epochId, aid, 1);

        uint256 plaintext = uint256(COMBINED_PLAINTEXT_HASH);
        CombineFixture memory f =
            combineFixtureAutomatic(epochId, aid, 1, 2, 2, COMBINED_DECRYPTION_HASH, plaintext);
        manager.combineDecryption(
            epochId, aid, 1, COMBINED_DECRYPTION_HASH, plaintext,
            combineTranscript(f), decryptCombineProof(), combineInput(f)
        );
        assertEq(manager.getPlaintext(epochId, aid, 1), plaintext);
    }

    /// @dev The organizer key in the transcript must be the registered one:
    ///      otherwise a combiner could prove the statement against a key it
    ///      owns and skip the organizer's half entirely.
    function test_CombineDecryption_RejectsOrganizerKeyMismatch() public {
        bytes12 epochId = createFinalizedRound();
        _submitBothPartials(epochId, TEST_AID, 1);

        uint256 plaintext = uint256(COMBINED_PLAINTEXT_HASH);
        CombineFixture memory f =
            combineFixture(epochId, TEST_AID, 1, 2, 2, COMBINED_DECRYPTION_HASH, plaintext);
        // A different, perfectly valid BabyJubJub key.
        (f.pkOrgX, f.pkOrgY) = BabyJubJub.scalarMulBase(TEST_ORG_SK + 1);
        bytes memory transcript = combineTranscript(f);
        bytes memory input = combineInput(f);
        vm.expectRevert(IDKGManager.InvalidProofInput.selector);
        manager.combineDecryption(
            epochId, TEST_AID, 1, COMBINED_DECRYPTION_HASH, plaintext,
            transcript, decryptCombineProof(), input
        );
    }

    function test_CombineDecryption_RejectsInsufficientPartials() public {
        bytes12 epochId = createFinalizedRound();
        _submitPartial(epochId, TEST_AID, 1, 1);

        uint256 plaintext = uint256(COMBINED_PLAINTEXT_HASH);
        CombineFixture memory f =
            combineFixture(epochId, TEST_AID, 1, 2, 2, COMBINED_DECRYPTION_HASH, plaintext);
        bytes memory transcript = combineTranscript(f);
        bytes memory input = combineInput(f);
        vm.expectRevert(IDKGManager.InsufficientPartialDecryptions.selector);
        manager.combineDecryption(
            epochId, TEST_AID, 1, COMBINED_DECRYPTION_HASH, plaintext,
            transcript, decryptCombineProof(), input
        );
    }

    function test_CombineDecryption_RejectsTwice() public {
        bytes12 epochId = createFinalizedRound();
        _submitBothPartials(epochId, TEST_AID, 1);

        uint256 plaintext = uint256(COMBINED_PLAINTEXT_HASH);
        CombineFixture memory f =
            combineFixture(epochId, TEST_AID, 1, 2, 2, COMBINED_DECRYPTION_HASH, plaintext);
        bytes memory transcript = combineTranscript(f);
        bytes memory input = combineInput(f);
        manager.combineDecryption(
            epochId, TEST_AID, 1, COMBINED_DECRYPTION_HASH, plaintext,
            transcript, decryptCombineProof(), input
        );
        vm.expectRevert(IDKGManager.AlreadyCombined.selector);
        manager.combineDecryption(
            epochId, TEST_AID, 1, COMBINED_DECRYPTION_HASH, plaintext,
            transcript, decryptCombineProof(), input
        );
    }

    /// @dev The per-partial hash binding still bites at the new transcript
    ///      offsets. First with a fully consistent envelope (ρ and the BRLC
    ///      commitment recomputed over the tampered words), so the only thing
    ///      left to catch a swapped δ is the stored per-partial hash; then
    ///      with the ρ-preserving maul the older transcript tests use.
    function test_CombineDecryption_RejectsMauledPartials() public {
        bytes12 epochId = createFinalizedRound();
        _submitBothPartials(epochId, TEST_AID, 1);

        uint256 plaintext = uint256(COMBINED_PLAINTEXT_HASH);
        CombineFixture memory f =
            combineFixture(epochId, TEST_AID, 1, 2, 2, COMBINED_DECRYPTION_HASH, plaintext);

        // δ_1.x lives at word 6+N.
        uint256[] memory words = combineWords(f);
        words[6 + MAX_N] = words[6 + MAX_N] + 4242;
        bytes memory mauledInput = combineInputForWords(f, words);
        vm.expectRevert(IDKGManager.InvalidProofInput.selector);
        manager.combineDecryption(
            epochId, TEST_AID, 1, COMBINED_DECRYPTION_HASH, plaintext,
            abi.encodePacked(words), decryptCombineProof(), mauledInput
        );

        // Same swap hidden in an unused participant slot so the BRLC
        // commitment of the honest input still matches.
        bytes memory honest = combineTranscript(f);
        bytes memory honestInput = combineInput(f);
        uint256 rho = BRLC.deriveChallenge(
            epochId,
            DECRYPT_COMBINE_TRANSCRIPT_DOMAIN,
            keccak256(abi.encodePacked(
                COMBINED_DECRYPTION_HASH, bytes32(plaintext), keccak256(honest)
            ))
        );
        bytes memory mauled = _maulPreservingBrlc(honest, rho, 6 + MAX_N, 6 + MAX_N - 1, 4242);
        vm.expectRevert(IDKGManager.InvalidProofInput.selector);
        manager.combineDecryption(
            epochId, TEST_AID, 1, COMBINED_DECRYPTION_HASH, plaintext,
            mauled, decryptCombineProof(), honestInput
        );
    }

    /// @dev `δ_1.x + p` commits like `δ_1.x`; the combine must refuse the
    ///      non-canonical word before anything else looks at it.
    function test_CombineDecryption_RejectsNonCanonicalWord() public {
        bytes12 epochId = createFinalizedRound();
        _submitBothPartials(epochId, TEST_AID, 1);

        uint256 plaintext = uint256(COMBINED_PLAINTEXT_HASH);
        CombineFixture memory f =
            combineFixture(epochId, TEST_AID, 1, 2, 2, COMBINED_DECRYPTION_HASH, plaintext);
        uint256[] memory words = combineWords(f);
        words[6 + MAX_N] = words[6 + MAX_N] + FR_MOD;
        bytes memory input = combineInputForWords(f, words);
        vm.expectRevert(BRLC.TranscriptWordNotInField.selector);
        manager.combineDecryption(
            epochId, TEST_AID, 1, COMBINED_DECRYPTION_HASH, plaintext,
            abi.encodePacked(words), decryptCombineProof(), input
        );
    }

    function test_CombineDecryption_RejectsCiphertextIndexTooLarge() public {
        bytes12 epochId = createFinalizedRound();

        uint256 plaintext = uint256(COMBINED_PLAINTEXT_HASH);
        CombineFixture memory f =
            combineFixture(epochId, TEST_AID, 257, 2, 2, COMBINED_DECRYPTION_HASH, plaintext);
        bytes memory transcript = combineTranscript(f);
        bytes memory input = combineInput(f);
        vm.expectRevert(IDKGManager.InvalidCombinedDecryption.selector);
        manager.combineDecryption(
            epochId, TEST_AID,
            257, // > MAX_CIPHERTEXT_INDEX (256)
            COMBINED_DECRYPTION_HASH, plaintext,
            transcript, decryptCombineProof(), input
        );
    }

    // ─── liveness integration ────────────────────────────────────────────────

    function test_CreateEpoch_UsesActiveCountAsDenominator() public {
        // Register a third node that we'll reap before the epoch is created.
        address ghost = address(0xdEaD);
        vm.prank(ghost);
        // DEAD vector from cmd/operator-schnorr-vectors.
        registry.registerKey(
            3602709693320481933414169817753642284358154248428933830091019302946389143220,
            19404998569400271134603777992322348196323180940366382216870830366803640744216,
            17932491275164157352977794940779755814592019455495863353086623153818614395728,
            11035761025934598318827129374247438153606368675015247802966920305427212653389,
            1940997602491403806671742881110463830588755899359470939853733010309975750617
        );
        assertEq(registry.activeCount(), 3);
        assertEq(registry.nodeCount(), 3);

        // Age the ghost out and reap.
        vm.roll(block.number + INACTIVITY_WINDOW + 1);
        registry.reap(ghost);
        assertEq(registry.activeCount(), 2);
        assertEq(registry.nodeCount(), 3);

        // Epoch created now sees registered = activeCount = 2, not 3.
        bytes12 epochId = _createLotteryRound();

        // With α=1.0 and active=2, the threshold should be uint256.max
        // (numerator 20000 ≥ 10000) — same as the vanilla 2-node setup.
        IDKGManager.Epoch memory epoch = manager.getEpoch(epochId);
        assertEq(epoch.lotteryThreshold, type(uint256).max);
    }

    function test_ClaimSlot_RejectsReapedNode() public {
        // Reap address(0xBEEF) (one of the two registered test nodes).
        vm.roll(block.number + INACTIVITY_WINDOW + 1);
        registry.reap(address(0xBEEF));

        uint64 next = manager.nextEpochStartBlock();
        if (block.number < uint256(next)) vm.roll(uint256(next));
        bytes12 epochId = manager.createEpoch(1, 1, 1, 10000);
        vm.roll(block.number + 2);

        vm.prank(address(0xBEEF));
        vm.expectRevert(IDKGManager.NotRegistered.selector);
        manager.claimSlot(epochId);

        // The still-active node can.
        vm.prank(alice);
        manager.claimSlot(epochId);
    }

    // ─── abortEpoch ──────────────────────────────────────────────────────────

    function test_AbortEpoch_PersistsAbortedStatus() public {
        bytes12 epochId = manager.createEpoch(2, 2, 2, 10000);
        // Nobody may abort while the committee can still fill.
        vm.expectRevert(IDKGManager.InvalidPhase.selector);
        manager.abortEpoch(epochId);

        vm.roll(uint256(manager.getEpoch(epochId).policy.committeeSelectionDeadlineBlock) + 1);
        vm.prank(address(0xCAFE)); // permissionless once dead
        manager.abortEpoch(epochId);

        IDKGManager.Epoch memory epoch = manager.getEpoch(epochId);
        assertEq(uint256(epoch.status), uint256(DKGTypes.EpochPhase.Aborted));
    }

    function test_AbortEpoch_RejectsFinalized() public {
        bytes12 epochId = createFinalizedRound();

        vm.expectRevert(IDKGManager.InvalidPhase.selector);
        manager.abortEpoch(epochId);
    }

    function test_AbortEpoch_AnyoneAfterKeyAssemblyDeadline() public {
        bytes12 epochId = manager.createEpoch(2, 2, 2, 10000);
        IDKGManager.Epoch memory epoch = manager.getEpoch(epochId);

        vm.prank(address(0xCAFE));
        vm.expectRevert(IDKGManager.InvalidPhase.selector);
        manager.abortEpoch(epochId);

        vm.roll(uint256(epoch.policy.keyAssemblyDeadlineBlock) + 1);
        vm.prank(address(0xCAFE));
        manager.abortEpoch(epochId);
        assertEq(uint256(manager.getEpoch(epochId).status), uint256(DKGTypes.EpochPhase.Aborted));
    }

    /// @dev A finalizable epoch can never be aborted, not even in the gap.
    function test_AbortEpoch_RejectsHealthyEpochDuringFinalizeGap() public {
        bytes12 epochId = createSelectedRound();
        _submitBothContributions(epochId);
        IDKGManager.Epoch memory epoch = manager.getEpoch(epochId);
        // Inside the gap between the key-assembly deadline and liveNotBefore.
        vm.roll(uint256(epoch.policy.keyAssemblyDeadlineBlock) + 1);
        vm.expectRevert(IDKGManager.InvalidPhase.selector);
        manager.abortEpoch(epochId); // creator
        vm.prank(address(0xCAFE));
        vm.expectRevert(IDKGManager.InvalidPhase.selector);
        manager.abortEpoch(epochId); // anyone
    }

    // ─── Constructor validation ──────────────────────────────────────────────

    function test_Constructor_RejectsZeroRegistry() public {
        vm.expectRevert(IDKGManager.InvalidAddress.selector);
        new DKGManager(
            31337,
            address(0), // zero registry
            address(verifier),
            address(partialVerifier),
            address(poolKeyVerifier),
            address(decryptCombineVerifier),
            0, 0, 0, 0, 0, 0, 0
        );
    }

    function test_Constructor_RejectsWrongChainId() public {
        vm.expectRevert(IDKGManager.InvalidChainId.selector);
        new DKGManager(
            1, // mainnet — not the test chain (31337)
            address(registry),
            address(verifier),
            address(partialVerifier),
            address(poolKeyVerifier),
            address(decryptCombineVerifier),
            0, 0, 0, 0, 0, 0, 0
        );
    }

    // ─── submitCiphertext ────────────────────────────────────────────────────

    function test_SubmitCiphertext_StoresHashAndIncrementsCount() public {
        bytes12 epochId = createFinalizedRound();
        // index 1 already submitted by createFinalizedRound; submit
        // another at index 2 to exercise the storage / counter path.
        bytes32 expected = keccak256(abi.encode(TEST_CT_C1X, TEST_CT_C1Y, TEST_CT_C2X, TEST_CT_C2Y));

        _submitTestCiphertext(epochId, TEST_AID);

        assertEq(uint256(manager.getCiphertextHash(epochId, TEST_AID, 2)), uint256(expected));
        assertEq(uint256(manager.getEpoch(epochId).ciphertextCount), 2);
    }

    function test_SubmitCiphertext_RejectsBeforeFinalized() public {
        bytes12 epochId = _createLotteryRound();

        vm.expectRevert(IDKGManager.InvalidPhase.selector);
        manager.submitCiphertext(epochId, TEST_AID, TEST_CT_C1X, TEST_CT_C1Y, TEST_CT_C2X, TEST_CT_C2Y);
    }

    /// @dev There is no epoch-key path: a ciphertext must name a registered
    ///      application, and aid = 0 can never be registered.
    function test_SubmitCiphertext_RejectsUnregisteredApplication() public {
        bytes12 epochId = createFinalizedRound();

        vm.expectRevert(IDKGAppManager.InvalidApplication.selector);
        manager.submitCiphertext(epochId, bytes32(0), TEST_CT_C1X, TEST_CT_C1Y, TEST_CT_C2X, TEST_CT_C2Y);

        vm.expectRevert(IDKGAppManager.InvalidApplication.selector);
        manager.submitCiphertext(
            epochId, bytes32(uint256(0xDEAD)), TEST_CT_C1X, TEST_CT_C1Y, TEST_CT_C2X, TEST_CT_C2Y
        );
    }

    /// @dev The policy's authorized submitter defaults to the registrant, so
    ///      an unrelated address cannot occupy the application's slots.
    function test_SubmitCiphertext_RejectsUnauthorizedSubmitter() public {
        bytes12 epochId = createFinalizedRound();

        vm.prank(address(0xCAFE));
        vm.expectRevert(IDKGAppManager.NotOwner.selector);
        manager.submitCiphertext(epochId, TEST_AID, TEST_CT_C1X, TEST_CT_C1Y, TEST_CT_C2X, TEST_CT_C2Y);
    }

    function test_SubmitCiphertext_RejectsOffCurvePoint() public {
        bytes12 epochId = createFinalizedRound();

        // (7001, 8001) does NOT satisfy a·x² + y² = 1 + d·x²·y² (mod Q).
        vm.expectRevert(IDKGManager.InvalidCiphertext.selector);
        manager.submitCiphertext(epochId, TEST_AID, 7001, 8001, 0, 1);

        // Canonical-range but off-curve: e.g. (1, 1).
        vm.expectRevert(IDKGManager.InvalidCiphertext.selector);
        manager.submitCiphertext(epochId, TEST_AID, 1, 1, 0, 1);

        // Bad c2 with valid c1 also reverts.
        vm.expectRevert(IDKGManager.InvalidCiphertext.selector);
        manager.submitCiphertext(epochId, TEST_AID, 0, 1, 1, 1);

        // Coordinates ≥ Q (non-canonical) rejected even if they'd be on-curve post-reduction.
        uint256 Q = 21888242871839275222246405745257275088548364400416034343698204186575808495617;
        vm.expectRevert(IDKGManager.InvalidCiphertext.selector);
        manager.submitCiphertext(epochId, TEST_AID, Q, 1, 0, 1);
    }

    /// @dev The on-chain prime-subgroup check of C_1 was dropped: it cost
    ///      ~2 M gas and a cofactor point cannot yield a valid combine proof.
    ///      Committee nodes subgroup-check before they release δ_i, which is
    ///      what protects their shares. Pin the (deliberate) acceptance here.
    function test_SubmitCiphertext_AcceptsSmallOrderC1() public {
        bytes12 epochId = createFinalizedRound();
        uint256 Q = 21888242871839275222246405745257275088548364400416034343698204186575808495617;
        // (0, -1) is on the curve, is not the identity and has order 2.
        uint16 idx = manager.submitCiphertext(epochId, TEST_AID, 0, Q - 1, TEST_CT_C2X, TEST_CT_C2Y);
        assertEq(uint256(idx), 2);
    }

    function test_SubmitCiphertext_AssignsSequentialIndices() public {
        bytes12 epochId = createFinalizedRound(); // the fixture already submitted one ciphertext
        uint16 before = manager.ciphertextCount(epochId, TEST_AID);
        uint16 first = _submitTestCiphertext(epochId, TEST_AID);
        uint16 second = _submitTestCiphertext(epochId, TEST_AID);
        assertEq(uint256(first), uint256(before) + 1);
        assertEq(uint256(second), uint256(before) + 2);
        assertEq(uint256(manager.ciphertextCount(epochId, TEST_AID)), uint256(before) + 2);
        assertEq(uint256(manager.getEpoch(epochId).ciphertextCount), uint256(before) + 2);
    }

    // ─── Lottery threshold ───────────────────────────────────────────────────

    function test_CreateEpoch_LotteryThresholdScalesWithActiveSet() public {
        // registered = 2 (ALICE + BEEF), committeeSize = 1, α = 1.0
        // → α·n = 1 < registered → threshold = 2^256 · 1 / 2.
        bytes12 epochId = manager.createEpoch(1, 1, 1, 10000);
        IDKGManager.Epoch memory epoch = manager.getEpoch(epochId);
        uint256 expected = (type(uint256).max / 20000) * 10000;
        assertEq(epoch.lotteryThreshold, expected);
        assertTrue(epoch.lotteryThreshold < type(uint256).max);
    }

    function test_CreateEpoch_LotteryThresholdIsMaxWhenOversubscribed() public {
        // α·n = 1.5 · 2 = 3 ≥ registered = 2 → everyone passes.
        bytes12 epochId = manager.createEpoch(2, 2, 2, 15000);
        assertEq(manager.getEpoch(epochId).lotteryThreshold, type(uint256).max);
    }

    /// @dev The contract must enforce keccak(seed ‖ op) < threshold exactly as
    ///      documented. Across several seeds at least one registered operator
    ///      must be turned away when only half the hash space is admissible.
    function test_ClaimSlot_EnforcesLotteryRule() public {
        address[2] memory ops = [alice, address(0xBEEF)];
        uint256 rejected;
        for (uint256 round = 0; round < 6; round++) {
            uint64 next = manager.nextEpochStartBlock();
            if (block.number < uint256(next)) vm.roll(uint256(next));
            bytes12 epochId = manager.createEpoch(1, 1, 1, 10000);
            IDKGManager.Epoch memory epoch = manager.getEpoch(epochId);
            vm.roll(uint256(epoch.seedBlock) + 1);
            bytes32 seed = blockhash(uint256(epoch.seedBlock));
            bool filled;
            for (uint256 i = 0; i < ops.length; i++) {
                bool eligible = uint256(keccak256(abi.encodePacked(seed, ops[i]))) < epoch.lotteryThreshold;
                if (filled) {
                    vm.expectRevert(IDKGManager.InvalidPhase.selector);
                } else if (!eligible) {
                    vm.expectRevert(IDKGManager.NotEligible.selector);
                    rejected++;
                }
                vm.prank(ops[i]);
                manager.claimSlot(epochId);
                if (eligible && !filled) filled = true;
            }
        }
        assertTrue(rejected > 0);
    }

    function test_CreateEpoch_DoesNotEvictOldEpochs() public {
        bytes12 first = manager.createEpoch(2, 2, 2, 10000);
        for (uint256 i = 0; i < 70; i++) {
            vm.roll(uint256(manager.nextEpochStartBlock()));
            manager.createEpoch(2, 2, 2, 10000);
        }
        assertEq(manager.getEpoch(first).organizer, address(this));
    }

    function test_CreateEpoch_EnforcesDeploymentPolicyFloors() public {
        DKGManager bounded = new DKGManager(
            31337, address(registry), address(verifier), address(partialVerifier),
            address(poolKeyVerifier), address(decryptCombineVerifier),
            0, 0, 0, 0,
            2,      // minThreshold
            3,      // minCommitteeSize
            20000   // maxLotteryAlphaBps (α ≤ 2.0)
        );
        vm.expectRevert(IDKGManager.InvalidPolicy.selector);
        bounded.createEpoch(1, 3, 3, 15000); // t below floor
        vm.expectRevert(IDKGManager.InvalidPolicy.selector);
        bounded.createEpoch(2, 2, 2, 15000); // n below floor
        vm.expectRevert(IDKGManager.InvalidPolicy.selector);
        bounded.createEpoch(2, 3, 3, 30000); // α above ceiling
        bounded.createEpoch(2, 3, 3, 20000);
    }

    // ─── Lottery snapshot ────────────────────────────────────────────────────

    function test_ClaimSlot_RejectsOperatorRegisteredAfterEpochCreation() public {
        bytes12 epochId = manager.createEpoch(1, 1, 1, 65535);
        address late = address(0xdEaD);
        vm.prank(late);
        registry.registerKey(
            3602709693320481933414169817753642284358154248428933830091019302946389143220,
            19404998569400271134603777992322348196323180940366382216870830366803640744216,
            17932491275164157352977794940779755814592019455495863353086623153818614395728,
            11035761025934598318827129374247438153606368675015247802966920305427212653389,
            1940997602491403806671742881110463830588755899359470939853733010309975750617
        );
        vm.roll(uint256(manager.getEpoch(epochId).seedBlock) + 1);
        vm.prank(late);
        vm.expectRevert(IDKGManager.NotInSnapshot.selector);
        manager.claimSlot(epochId);
    }

    function test_ClaimSlot_RejectsDormantOperatorReactivatedAfterEpochCreation() public {
        address dormant = address(0xBEEF);
        vm.roll(block.number + INACTIVITY_WINDOW + 1);
        registry.reap(dormant);
        bytes12 epochId = manager.createEpoch(1, 1, 1, 65535);
        vm.prank(dormant);
        registry.reactivate();
        vm.roll(uint256(manager.getEpoch(epochId).seedBlock) + 1);
        vm.prank(dormant);
        vm.expectRevert(IDKGManager.NotInSnapshot.selector);
        manager.claimSlot(epochId);
    }

    // ─── Calldata transcripts must be bound by a challenge the prover cannot
    //     know before the calldata is fixed ─────────────────────────────────

    uint256 internal constant FR_MOD = 21888242871839275222246405745257275088548364400416034343698204186575808495617;

    function _modInv(uint256 a) internal pure returns (uint256 result) {
        result = 1;
        uint256 base = a % FR_MOD;
        uint256 e = FR_MOD - 2;
        while (e > 0) {
            if (e & 1 == 1) result = mulmod(result, base, FR_MOD);
            base = mulmod(base, base, FR_MOD);
            e >>= 1;
        }
    }

    /// @dev Adds `delta` to word `a` and compensates word `b` so that
    ///      Σ ρ^(i+1)·v_i is unchanged: a prover who knows ρ can do this.
    function _maulPreservingBrlc(bytes memory transcript, uint256 rho, uint256 a, uint256 b, uint256 delta)
        internal pure returns (bytes memory)
    {
        uint256 factor = 1; // ρ^(a-b), or inv(ρ)^(b-a)
        uint256 step = a > b ? rho : _modInv(rho);
        uint256 dist = a > b ? a - b : b - a;
        for (uint256 i = 0; i < dist; i++) factor = mulmod(factor, step, FR_MOD);
        uint256 db = FR_MOD - mulmod(delta, factor, FR_MOD);
        uint256 va;
        uint256 vb;
        assembly {
            va := mload(add(transcript, add(32, mul(a, 32))))
            vb := mload(add(transcript, add(32, mul(b, 32))))
        }
        va = addmod(va, delta, FR_MOD);
        vb = addmod(vb, db, FR_MOD);
        assembly {
            mstore(add(transcript, add(32, mul(a, 32))), va)
            mstore(add(transcript, add(32, mul(b, 32))), vb)
        }
        return transcript;
    }

    /// @dev Swapping two masked shares (recipients 1 and 2 would decrypt
    ///      garbage) while preserving the BRLC commitment still fails: the
    ///      challenge is Fiat–Shamir over the calldata itself.
    function test_SubmitContribution_RejectsMauledTranscript() public {
        bytes12 epochId = createSelectedRound();
        bytes memory honest = contributionTranscript(2);
        uint256 msBase = 2 * MAX_K * MAX_N + 5 * MAX_N;
        uint256 rho = BRLC.deriveChallenge(
            epochId, CONTRIBUTION_TRANSCRIPT_DOMAIN,
            keccak256(abi.encodePacked(
                contributorCommitmentsHash(1), contributorSharesHash(1), keccak256(honest)
            ))
        );
        bytes memory mauled = _maulPreservingBrlc(honest, rho, msBase, msBase + 1, 12345);
        vm.expectRevert(IDKGManager.InvalidProofInput.selector);
        vm.prank(alice, alice);
        manager.submitContribution(
            epochId, 1, contributorCommitmentsHash(1), contributorSharesHash(1),
            mauled, contributionProof(),
            contributionInput(epochId, 2, 2, 1, contributorCommitmentsHash(1), contributorSharesHash(1))
        );
    }

    /// @dev Rewriting `P_j` (aggregate[0], word 2N) and hiding the change in an
    ///      unused participant-index padding word is caught the same way.
    function test_ActivatePoolKey_RejectsMauledTranscript() public {
        bytes12 epochId = createLiveRound();
        bytes memory honest = poolKeyTranscript(1, 2, 2);
        bytes memory input = poolKeyInput(epochId, 2, 2, 2, 1);
        uint256 rho = BRLC.deriveChallenge(
            epochId, POOLKEY_TRANSCRIPT_DOMAIN,
            keccak256(abi.encodePacked(testTranscriptDigest(1), keccak256(honest)))
        );
        bytes memory mauled = _maulPreservingBrlc(honest, rho, 2 * MAX_N, MAX_N - 1, 777);
        vm.expectRevert(IDKGManager.InvalidProofInput.selector);
        vm.prank(alice, alice);
        manager.activatePoolKey(epochId, 1, testTranscriptDigest(1), mauled, poolKeyProof(), input);
    }
}

/// @title DirectCallForwarder
/// @notice Minimal relayer standing in for any contract-account caller
///         (contract wallet, batcher, EIP-7702 delegate): the DKG call
///         becomes an internal call, so the outer transaction calldata is
///         no longer the DKG calldata that nodes and the SDK recover
///         transcripts from.
contract DirectCallForwarder {
    function submit(
        address mgr,
        bytes12 epochId,
        uint16 contributorIndex,
        bytes32 commitmentsHash,
        bytes32 encryptedSharesHash,
        bytes calldata transcript,
        bytes calldata proof,
        bytes calldata input
    ) external {
        IDKGManager(mgr).submitContribution(
            epochId, contributorIndex, commitmentsHash, encryptedSharesHash, transcript, proof, input
        );
    }

    function activate(
        address mgr,
        bytes12 epochId,
        uint8 keyIndex,
        bytes32 transcriptDigest,
        bytes calldata transcript,
        bytes calldata proof,
        bytes calldata input
    ) external {
        IDKGManager(mgr).activatePoolKey(epochId, keyIndex, transcriptDigest, transcript, proof, input);
    }
}
