// SPDX-License-Identifier: AGPL-3.0-or-later
pragma solidity 0.8.28;

import {Test} from "forge-std/Test.sol";
import {DKGRegistry} from "../src/DKGRegistry.sol";
import {DKGManager} from "../src/DKGManager.sol";
import {DKGAppManager} from "../src/DKGAppManager.sol";
import {IDKGManager} from "../src/interfaces/IDKGManager.sol";
import {IDKGAppManager} from "../src/interfaces/IDKGAppManager.sol";
import {DKGTypes} from "../src/libraries/DKGTypes.sol";
import {
    MockContributionVerifier,
    MockPartialDecryptVerifier,
    MockFinalizeVerifier,
    MockDecryptCombineVerifier,
    TestHelpers
} from "./TestHelpers.t.sol";

/// @title DKGManagerAppTest
/// @notice Tests for the per-application registration surface added in P8.
///         Mode-0 (public derivation) verifies the S-tag derivation and the
///         storage shape; mode-1 (organizer co-decryption) verifies the
///         Schnorr proof of knowledge of `sk_org`.
///
///         Setup: we shortcut the epoch lifecycle by writing directly into
///         the manager's storage slots — these tests exercise the application
///         entry points only, not the epoch finalization path (which is
///         covered by the broader DKGManagerTest suite).
contract DKGManagerAppTest is Test, TestHelpers {
    DKGRegistry public registry;
    DKGManager public manager;
    DKGAppManager public appManager;

    // Schnorr operator vectors (THIS / BEEF), copied from DKGManager.t.sol.
    uint256 internal constant THIS_PUBX =
        17765672829315743641357949553430354448961270408100494783209553303687184365803;
    uint256 internal constant THIS_PUBY =
        13591243454297365848719372676992908085762757043204242277513940025707896351954;
    uint256 internal constant THIS_AX =
        8735331066154608227876753674818247062971894554643955333501578253334124637538;
    uint256 internal constant THIS_AY =
        21272836954776476886917169960736847641993451090581680169106828110848349153636;
    uint256 internal constant THIS_Z =
        1369885591156151396853044744701991591603236518469391786750891091614769051717;
    uint256 internal constant BEEF_PUBX =
        10228722604559478181013548940833210623190136968531440936190496170400150013980;
    uint256 internal constant BEEF_PUBY =
        13886497050333420293068628977630539070604271411621054562122682889313139677221;
    uint256 internal constant BEEF_AX =
        14566234973743316386655481200503006158732416518867749191804063760238069794878;
    uint256 internal constant BEEF_AY =
        13078057343376780948266496972118389875598288245980415388506507934563371992806;
    uint256 internal constant BEEF_Z =
        855437853746059451716869189734643730464853812739723681978635195783451059776;

    // Organizer Schnorr vector for mode-1 tests, generated by the snippet
    // in P8's test setup (epochId="epoch-1", aid=7, secret=12345, witness=67890).
    bytes12 internal constant TEST_EID = bytes12("epoch-1\x00\x00\x00\x00\x00");
    bytes32 internal constant TEST_AID = bytes32(uint256(7));
    uint256 internal constant ORG_PUBX =
        19918712023960437102123786886411468478902094248734671506464346041569881874462;
    uint256 internal constant ORG_PUBY =
        13276557205153692030187527501273228448057533426731746626187331221465573305487;
    uint256 internal constant ORG_AX =
        12287997016850389469110242969064293751829629564460909843947225860072336518462;
    uint256 internal constant ORG_AY =
        11610694160704858701950599566691828874575930603037515361903555914794501850944;
    uint256 internal constant ORG_Z =
        1478945188110262673260477393893016777614807243365946083947099966421615439229;

    function setUp() public {
        registry = new DKGRegistry(1_000);
        registry.registerKey(THIS_PUBX, THIS_PUBY, THIS_AX, THIS_AY, THIS_Z);
        vm.prank(address(0xBEEF));
        registry.registerKey(BEEF_PUBX, BEEF_PUBY, BEEF_AX, BEEF_AY, BEEF_Z);
        address partialDecryptVerifier = address(new MockPartialDecryptVerifier());
        manager = new DKGManager(
            31337,
            address(registry),
            address(new MockContributionVerifier()),
            partialDecryptVerifier,
            address(new MockFinalizeVerifier()),
            address(new MockDecryptCombineVerifier())
        );
        registry.setManager(address(manager));
        appManager = new DKGAppManager(address(manager), partialDecryptVerifier);
        manager.setAppManager(address(appManager));
    }

    // Helper: build a finalized-enough epoch by going through the full
    // lifecycle (createEpoch → claimSlot → submitContribution × 2 →
    // finalizeEpoch). For application-registration tests we only need the
    // resulting `_collectiveKey[eid]` to be non-identity. The mocks accept
    // anything proof-shaped, so this shortcuts neatly.
    function _finalizedEpoch() internal returns (bytes12 epochId) {
        epochId = manager.createEpoch(
            2, 2, 2, 10000, 1,
            uint64(block.number + 5),
            uint64(block.number + 20),
            uint64(block.number + 21),
            _emptyDecryptionPolicy()
        );
        vm.roll(block.number + 2);
        manager.claimSlot(epochId);
        vm.prank(address(0xBEEF));
        manager.claimSlot(epochId);

        manager.submitContribution(
            epochId, 1,
            CONTRIBUTION_COMMITMENTS_HASH,
            CONTRIBUTION_ENCRYPTED_SHARES_HASH,
            contributionTranscript(2),
            contributionProof(),
            contributionInput(epochId, 2, 2, 1, CONTRIBUTION_COMMITMENTS_HASH, CONTRIBUTION_ENCRYPTED_SHARES_HASH)
        );
        vm.prank(address(0xBEEF));
        manager.submitContribution(
            epochId, 2,
            bytes32(uint256(CONTRIBUTION_COMMITMENTS_HASH) + 1),
            bytes32(uint256(CONTRIBUTION_ENCRYPTED_SHARES_HASH) + 1),
            contributionTranscript(2),
            contributionProof(),
            contributionInput(
                epochId,
                2,
                2,
                2,
                bytes32(uint256(CONTRIBUTION_COMMITMENTS_HASH) + 1),
                bytes32(uint256(CONTRIBUTION_ENCRYPTED_SHARES_HASH) + 1)
            )
        );
        IDKGManager.Epoch memory r = manager.getEpoch(epochId);
        if (block.number < uint256(r.policy.finalizeNotBeforeBlock)) {
            vm.roll(uint256(r.policy.finalizeNotBeforeBlock));
        }
        manager.finalizeEpoch(
            epochId,
            FINALIZED_AGGREGATE_COMMITMENTS_HASH,
            FINALIZED_COLLECTIVE_PUBLIC_KEY_HASH,
            FINALIZED_SHARE_COMMITMENT_HASH,
            finalizeTranscript(2),
            finalizeProof(),
            finalizeInput(
                epochId, 2, 2, 2,
                FINALIZED_AGGREGATE_COMMITMENTS_HASH,
                FINALIZED_COLLECTIVE_PUBLIC_KEY_HASH,
                FINALIZED_SHARE_COMMITMENT_HASH
            )
        );
    }

    function _emptyAppPolicy() internal pure returns (DKGTypes.AppPolicy memory) {
        return DKGTypes.AppPolicy({
            authorizedSubmitter: address(0),
            maxCiphertexts: 0,
            notBeforeBlock: 0,
            notAfterBlock: 0
        });
    }

    // ─── Mode 0: public derivation ─────────────────────────────────────────

    function test_RegisterApplication_PersistsRecord() public {
        bytes12 epochId = _finalizedEpoch();
        bytes32 aid = bytes32(uint256(42));
        appManager.registerApplication(epochId, aid, _emptyAppPolicy());

        DKGTypes.Application memory app = appManager.getApplication(epochId, aid);
        assertEq(app.creator, address(this));
        assertEq(uint256(app.mode), uint256(DKGTypes.AppMode.PublicDerivation));
        // S = keccak256(eid || PK_ep || aid) % L. Just verify it is nonzero.
        assertTrue(app.derivationS != 0);
        assertEq(app.organizerPK.x, 0);
        assertEq(app.organizerPK.y, 1);
        assertTrue(app.exists);
    }

    function test_RegisterApplication_RejectsZeroAid() public {
        bytes12 epochId = _finalizedEpoch();
        vm.expectRevert(IDKGAppManager.InvalidApplication.selector);
        appManager.registerApplication(epochId, bytes32(0), _emptyAppPolicy());
    }

    function test_RegisterApplication_RejectsDuplicate() public {
        bytes12 epochId = _finalizedEpoch();
        bytes32 aid = bytes32(uint256(42));
        appManager.registerApplication(epochId, aid, _emptyAppPolicy());
        vm.expectRevert(IDKGAppManager.ApplicationAlreadyExists.selector);
        appManager.registerApplication(epochId, aid, _emptyAppPolicy());
    }

    function test_RegisterApplication_RejectsUnknownEpoch() public {
        vm.expectRevert(IDKGManager.InvalidEpoch.selector);
        appManager.registerApplication(bytes12(uint96(0xdead)), bytes32(uint256(1)), _emptyAppPolicy());
    }

    // ─── Mode 1: organizer co-decryption ───────────────────────────────────
    //
    // The Schnorr vector binds (epochId="epoch-1", aid=7), but the manager
    // generates fresh epoch ids per-test via the lottery. End-to-end mode-1
    // happy-path testing therefore requires either a freshly-generated
    // organizer Schnorr vector for each test (expensive), or a Foundry
    // FFI hook that calls `cmd/operator-schnorr-vectors` style code from
    // the test runner. Both are deferred to S1 (cross-impl vector pipeline);
    // the on-chain Schnorr verification math itself is exercised by
    // DKGRegistrySchnorrTest in the operator path (same primitive,
    // different transcript domain).
    //
    // For P8 we cover the negative path: registering with mode-1 against
    // an unknown epoch should revert before reaching the Schnorr check,
    // ensuring the access-control prelude is correctly wired.

    function test_RegisterApplicationCoDec_RejectsUnknownEpoch() public {
        vm.expectRevert(IDKGManager.InvalidEpoch.selector);
        appManager.registerApplicationCoDec(
            bytes12(uint96(0xfeed)),
            bytes32(uint256(1)),
            _emptyAppPolicy(),
            ORG_PUBX, ORG_PUBY,
            ORG_AX, ORG_AY, ORG_Z
        );
    }

    function test_RegisterApplicationCoDec_RejectsBeforeFinalization() public {
        bytes12 epochId = manager.createEpoch(
            2, 2, 2, 10000, 1,
            uint64(block.number + 5),
            uint64(block.number + 20),
            uint64(block.number + 21),
            _emptyDecryptionPolicy()
        );
        vm.expectRevert(IDKGManager.InvalidPhase.selector);
        appManager.registerApplicationCoDec(
            epochId,
            bytes32(uint256(1)),
            _emptyAppPolicy(),
            ORG_PUBX, ORG_PUBY,
            ORG_AX, ORG_AY, ORG_Z
        );
    }
}
