// SPDX-License-Identifier: AGPL-3.0-or-later
pragma solidity 0.8.28;

import {Test} from "forge-std/Test.sol";
import {DKGRegistry} from "../src/DKGRegistry.sol";
import {DKGManager} from "../src/DKGManager.sol";
import {IDKGManager} from "../src/interfaces/IDKGManager.sol";
import {DKGTypes} from "../src/libraries/DKGTypes.sol";
import {
    MockContributionVerifier,
    MockPartialDecryptVerifier,
    MockFinalizeVerifier,
    MockDecryptCombineVerifier,
    TestHelpers
} from "./TestHelpers.t.sol";

contract DKGManagerTest is Test, TestHelpers {
    DKGRegistry public registry;
    MockContributionVerifier public verifier;
    MockPartialDecryptVerifier public partialVerifier;
    MockFinalizeVerifier public finalizeVerifier;
    MockDecryptCombineVerifier public decryptCombineVerifier;
    DKGManager public manager;

    uint64 internal constant INACTIVITY_WINDOW = 1_000;

    // Schnorr vectors generated by cmd/operator-schnorr-vectors. THIS is the
    // Foundry default test address; BEEF is 0xBEEF (used for the second
    // committee member in the lottery tests).
    uint256 internal constant THIS_PUBX =
        17765672829315743641357949553430354448961270408100494783209553303687184365803;
    uint256 internal constant THIS_PUBY =
        13591243454297365848719372676992908085762757043204242277513940025707896351954;
    uint256 internal constant THIS_AX =
        8735331066154608227876753674818247062971894554643955333501578253334124637538;
    uint256 internal constant THIS_AY =
        21272836954776476886917169960736847641993451090581680169106828110848349153636;
    uint256 internal constant THIS_Z =
        1369885591156151396853044744701991591603236518469391786750891091614769051717;
    uint256 internal constant BEEF_PUBX =
        10228722604559478181013548940833210623190136968531440936190496170400150013980;
    uint256 internal constant BEEF_PUBY =
        13886497050333420293068628977630539070604271411621054562122682889313139677221;
    uint256 internal constant BEEF_AX =
        14566234973743316386655481200503006158732416518867749191804063760238069794878;
    uint256 internal constant BEEF_AY =
        13078057343376780948266496972118389875598288245980415388506507934563371992806;
    uint256 internal constant BEEF_Z =
        855437853746059451716869189734643730464853812739723681978635195783451059776;

    function setUp() public {
        registry = new DKGRegistry(INACTIVITY_WINDOW);
        registry.registerKey(THIS_PUBX, THIS_PUBY, THIS_AX, THIS_AY, THIS_Z);
        vm.prank(address(0xBEEF));
        registry.registerKey(BEEF_PUBX, BEEF_PUBY, BEEF_AX, BEEF_AY, BEEF_Z);
        verifier = new MockContributionVerifier();
        partialVerifier = new MockPartialDecryptVerifier();
        finalizeVerifier = new MockFinalizeVerifier();
        decryptCombineVerifier = new MockDecryptCombineVerifier();
        manager = new DKGManager(
            31337,
            address(registry),
            address(verifier),
            address(partialVerifier),
            address(finalizeVerifier),
            address(decryptCombineVerifier),
            0,  // epochDurationBlocks → DEFAULT (100)
            0,  // committeeSelectionBlocks → DEFAULT (25)
            0,  // keyAssemblyBlocks → DEFAULT (25)
            0   // finalizeGapBlocks → DEFAULT (5)
        );
        // Wire the liveness callback so submitContribution can refresh
        // the contributor's lastActiveBlock on the registry.
        registry.setManager(address(manager));
    }

    function createSelectedRound() internal returns (bytes12 epochId) {
        epochId = _createLotteryRound();
        _claimAllSlots(epochId);
    }

    /// @dev Creates a epoch with a lottery threshold of "everyone passes" so the two
    /// registered test nodes (address(this) and 0xBEEF) are both eligible.
    /// All phase deadlines are derived from the contract's
    /// `EPOCH_DURATION_BLOCKS` (100 in the default-deploy test fixture):
    /// regDeadline=+5, contribDeadline=+20, finalizeNotBefore=+25.
    function _createLotteryRound() internal returns (bytes12 epochId) {
        // Permissionless cadence: roll forward to nextEpochStartBlock if
        // a previous epoch was just created in this same test.
        uint64 next = manager.nextEpochStartBlock();
        if (block.number < uint256(next)) vm.roll(uint256(next));
        // α = 1.0 (10000 bps), committeeSize = 2, registered = 2 → all pass.
        epochId = manager.createEpoch(
            2,                         // threshold
            2,                         // committeeSize
            2,                         // minValidContributions
            10000,                     // lotteryAlphaBps (α = 1.0)
            _emptyDecryptionPolicy()
        );
        // Advance past seedBlock so blockhash is available.
        vm.roll(block.number + 2);
    }

    function _claimAllSlots(bytes12 epochId) internal {
        manager.claimSlot(epochId);
        vm.prank(address(0xBEEF));
        manager.claimSlot(epochId);
    }

    /// @dev Advance to a block at or after `liveNotBeforeBlock` for the epoch.
    function _advanceToFinalize(bytes12 epochId) internal {
        IDKGManager.Epoch memory r = manager.getEpoch(epochId);
        if (block.number < uint256(r.policy.liveNotBeforeBlock)) {
            vm.roll(uint256(r.policy.liveNotBeforeBlock));
        }
    }

    function createFinalizedRound() internal returns (bytes12 epochId) {
        epochId = createSelectedRound();

        manager.submitContribution(
            epochId,
            1,
            CONTRIBUTION_COMMITMENTS_HASH,
            CONTRIBUTION_ENCRYPTED_SHARES_HASH,            contributionTranscript(2),
            contributionProof(),
            contributionInput(epochId, 2, 2, 1, CONTRIBUTION_COMMITMENTS_HASH, CONTRIBUTION_ENCRYPTED_SHARES_HASH)
        );

        vm.prank(address(0xBEEF));
        manager.submitContribution(
            epochId,
            2,
            bytes32(uint256(CONTRIBUTION_COMMITMENTS_HASH) + 1),
            bytes32(uint256(CONTRIBUTION_ENCRYPTED_SHARES_HASH) + 1),            contributionTranscript(2),
            contributionProof(),
            contributionInput(
                epochId,
                2,
                2,
                2,
                bytes32(uint256(CONTRIBUTION_COMMITMENTS_HASH) + 1),
                bytes32(uint256(CONTRIBUTION_ENCRYPTED_SHARES_HASH) + 1)
            )
        );

        _advanceToFinalize(epochId);
        manager.finalizeEpoch(
            epochId,
            FINALIZED_AGGREGATE_COMMITMENTS_HASH,
            FINALIZED_COLLECTIVE_PUBLIC_KEY_HASH,
            FINALIZED_SHARE_COMMITMENT_HASH,
            finalizeTranscript(2),
            finalizeProof(),
            finalizeInput(
                epochId,
                2,
                2,
                2,
                FINALIZED_AGGREGATE_COMMITMENTS_HASH,
                FINALIZED_COLLECTIVE_PUBLIC_KEY_HASH,
                FINALIZED_SHARE_COMMITMENT_HASH
            )
        );

        // submitPartialDecryption requires the ciphertext to exist on-chain
        // so it can bind C1 into the proof's
        // public inputs. Most test paths drive the partial-decrypt flow
        // against ciphertextIndex=1, so submit it as part of the
        // canonical "finalized" fixture. Tests that need an unsubmitted
        // ciphertext use a different index.
        manager.submitCiphertext(epochId, bytes32(0), 1, TEST_CT_C1X, TEST_CT_C1Y, TEST_CT_C2X, TEST_CT_C2Y);
    }

    function test_CreateEpoch_PersistsPolicy() public {
        // committeeSize=2, registered=2, α=1.0 → all eligible
        bytes12 epochId = manager.createEpoch(2, 2, 2, 10000, _emptyDecryptionPolicy());

        IDKGManager.Epoch memory epoch = manager.getEpoch(epochId);

        assertEq(epoch.organizer, address(this));
        assertEq(uint256(epoch.policy.threshold), 2);
        assertEq(uint256(epoch.policy.committeeSize), 2);
        assertEq(uint256(epoch.status), uint256(DKGTypes.EpochPhase.CommitteeSelection));
    }

    function test_ClaimSlot_RejectsBeforeSeedReady() public {
        bytes12 epochId =
            manager.createEpoch(2, 2, 2, 10000, _emptyDecryptionPolicy());
        // Don't roll forward — seed block has not been mined yet.
        vm.expectRevert(IDKGManager.SeedNotReady.selector);
        manager.claimSlot(epochId);
    }

    function test_ClaimSlot_RejectsDuplicates() public {
        bytes12 epochId = _createLotteryRound();
        manager.claimSlot(epochId);
        vm.expectRevert(IDKGManager.AlreadyClaimed.selector);
        manager.claimSlot(epochId);
    }

    function test_ClaimSlot_FillsCommitteeAndAdvancesPhase() public {
        bytes12 epochId = _createLotteryRound();
        _claimAllSlots(epochId);

        IDKGManager.Epoch memory epoch = manager.getEpoch(epochId);
        address[] memory selected = manager.selectedParticipants(epochId);

        assertEq(uint256(epoch.status), uint256(DKGTypes.EpochPhase.KeyAssembly));
        assertEq(selected.length, 2);
        assertEq(selected[0], address(this));
        assertEq(selected[1], address(0xBEEF));
    }

    function test_ClaimSlot_RejectsAfterSlotsFull() public {
        bytes12 epochId = _createLotteryRound();
        _claimAllSlots(epochId);
        // epoch.status is now Contribution, so further claimSlot calls should revert
        // on phase, not on slots-full (we never reach the slots-full check).
        vm.prank(address(0xCAFE));
        vm.expectRevert(IDKGManager.InvalidPhase.selector);
        manager.claimSlot(epochId);
    }

    function test_GetContributionVerifierVKeyHash() public view {
        assertEq(uint256(manager.getContributionVerifierVKeyHash()), uint256(CONTRIBUTION_PROVING_KEY_HASH));
    }

    function test_SubmitContribution_PersistsRecord() public {
        bytes12 epochId = createSelectedRound();

        manager.submitContribution(
            epochId,
            1,
            CONTRIBUTION_COMMITMENTS_HASH,
            CONTRIBUTION_ENCRYPTED_SHARES_HASH,            contributionTranscript(2),
            contributionProof(),
            contributionInput(epochId, 2, 2, 1, CONTRIBUTION_COMMITMENTS_HASH, CONTRIBUTION_ENCRYPTED_SHARES_HASH)
        );

        DKGTypes.ContributionRecord memory record = manager.getContribution(epochId, address(this));
        IDKGManager.Epoch memory epoch = manager.getEpoch(epochId);

        // contributor / commitmentsHash / encryptedSharesHash are no longer persisted
        // (they live in the ContributionSubmitted event); only the fields the contract
        // itself needs at finalize time remain in storage.
        assertEq(uint256(record.contributorIndex), 1);
        assertEq(record.accepted ? uint256(1) : uint256(0), 1);
        assertEq(uint256(epoch.contributionCount), 1);
    }

    function test_SubmitContribution_RejectsUnselectedOperator() public {
        bytes12 epochId = createSelectedRound();

        vm.prank(address(0xCAFE));
        vm.expectRevert(IDKGManager.NotSelectedParticipant.selector);
        manager.submitContribution(
            epochId,
            1,
            CONTRIBUTION_COMMITMENTS_HASH,
            CONTRIBUTION_ENCRYPTED_SHARES_HASH,            contributionTranscript(2),
            contributionProof(),
            contributionInput(epochId, 2, 2, 1, CONTRIBUTION_COMMITMENTS_HASH, CONTRIBUTION_ENCRYPTED_SHARES_HASH)
        );
    }

    function test_SubmitContribution_RejectsDuplicates() public {
        bytes12 epochId = createSelectedRound();

        manager.submitContribution(
            epochId,
            1,
            CONTRIBUTION_COMMITMENTS_HASH,
            CONTRIBUTION_ENCRYPTED_SHARES_HASH,            contributionTranscript(2),
            contributionProof(),
            contributionInput(epochId, 2, 2, 1, CONTRIBUTION_COMMITMENTS_HASH, CONTRIBUTION_ENCRYPTED_SHARES_HASH)
        );

        vm.expectRevert(IDKGManager.AlreadyContributed.selector);
        manager.submitContribution(
            epochId,
            1,
            CONTRIBUTION_COMMITMENTS_HASH,
            CONTRIBUTION_ENCRYPTED_SHARES_HASH,            contributionTranscript(2),
            contributionProof(),
            contributionInput(epochId, 2, 2, 1, CONTRIBUTION_COMMITMENTS_HASH, CONTRIBUTION_ENCRYPTED_SHARES_HASH)
        );
    }

    function test_SubmitContribution_RejectsBadProofInput() public {
        bytes12 epochId = createSelectedRound();

        // The manager validates cheap public-input bindings before invoking
        // the verifier, so a tampered input vector reverts with the manager's
        // own InvalidProofInput rather than the verifier's.
        vm.expectRevert(IDKGManager.InvalidProofInput.selector);
        manager.submitContribution(
            epochId,
            1,
            CONTRIBUTION_COMMITMENTS_HASH,
            CONTRIBUTION_ENCRYPTED_SHARES_HASH,            contributionTranscript(2),
            contributionProof(),
            CONTRIBUTION_INPUT_BAD
        );
    }

    function test_GetPartialDecryptVerifierVKeyHash() public view {
        assertEq(uint256(manager.getPartialDecryptVerifierVKeyHash()), uint256(PARTIAL_DECRYPTION_PROVING_KEY_HASH));
    }

    function test_FinalizeEpoch_PersistsHashes() public {
        bytes12 epochId = createFinalizedRound();

        IDKGManager.Epoch memory epoch = manager.getEpoch(epochId);

        // The three commitment hashes are no longer stored; consumers read them from
        // the EpochLive event.
        assertEq(uint256(epoch.status), uint256(DKGTypes.EpochPhase.Live));
    }

    function test_FinalizeEpoch_RejectsInsufficientContributions() public {
        bytes12 epochId = createSelectedRound();

        manager.submitContribution(
            epochId,
            1,
            CONTRIBUTION_COMMITMENTS_HASH,
            CONTRIBUTION_ENCRYPTED_SHARES_HASH,            contributionTranscript(2),
            contributionProof(),
            contributionInput(epochId, 2, 2, 1, CONTRIBUTION_COMMITMENTS_HASH, CONTRIBUTION_ENCRYPTED_SHARES_HASH)
        );

        _advanceToFinalize(epochId);
        vm.expectRevert(IDKGManager.InsufficientContributions.selector);
        manager.finalizeEpoch(
            epochId,
            FINALIZED_AGGREGATE_COMMITMENTS_HASH,
            FINALIZED_COLLECTIVE_PUBLIC_KEY_HASH,
            FINALIZED_SHARE_COMMITMENT_HASH,
            finalizeTranscript(1),
            finalizeProof(),
            finalizeInput(
                epochId,
                2,
                2,
                1,
                FINALIZED_AGGREGATE_COMMITMENTS_HASH,
                FINALIZED_COLLECTIVE_PUBLIC_KEY_HASH,
                FINALIZED_SHARE_COMMITMENT_HASH
            )
        );
    }

    function test_FinalizeEpoch_RejectsBeforeFinalizeNotBeforeBlock() public {
        bytes12 epochId = createSelectedRound();

        manager.submitContribution(
            epochId, 1, CONTRIBUTION_COMMITMENTS_HASH, CONTRIBUTION_ENCRYPTED_SHARES_HASH,
            contributionTranscript(2), contributionProof(),
            contributionInput(epochId, 2, 2, 1, CONTRIBUTION_COMMITMENTS_HASH, CONTRIBUTION_ENCRYPTED_SHARES_HASH)
        );
        vm.prank(address(0xBEEF));
        manager.submitContribution(
            epochId, 2,
            bytes32(uint256(CONTRIBUTION_COMMITMENTS_HASH) + 1),
            bytes32(uint256(CONTRIBUTION_ENCRYPTED_SHARES_HASH) + 1),
            contributionTranscript(2), contributionProof(),
            contributionInput(
                epochId,
                2,
                2,
                2,
                bytes32(uint256(CONTRIBUTION_COMMITMENTS_HASH) + 1),
                bytes32(uint256(CONTRIBUTION_ENCRYPTED_SHARES_HASH) + 1)
            )
        );

        // Both contributions in, threshold met — but liveNotBeforeBlock
        // not yet reached. Must revert with InvalidPhase (the gate reuses this
        // selector to keep the contract under the EIP-170 size limit).
        IDKGManager.Epoch memory r = manager.getEpoch(epochId);
        assertTrue(block.number < uint256(r.policy.liveNotBeforeBlock));

        vm.expectRevert(IDKGManager.InvalidPhase.selector);
        manager.finalizeEpoch(
            epochId,
            FINALIZED_AGGREGATE_COMMITMENTS_HASH,
            FINALIZED_COLLECTIVE_PUBLIC_KEY_HASH,
            FINALIZED_SHARE_COMMITMENT_HASH,
            finalizeTranscript(2), finalizeProof(),
            finalizeInput(
                epochId, 2, 2, 2,
                FINALIZED_AGGREGATE_COMMITMENTS_HASH,
                FINALIZED_COLLECTIVE_PUBLIC_KEY_HASH,
                FINALIZED_SHARE_COMMITMENT_HASH
            )
        );

        // Roll exactly to liveNotBeforeBlock — should succeed.
        vm.roll(uint256(r.policy.liveNotBeforeBlock));
        manager.finalizeEpoch(
            epochId,
            FINALIZED_AGGREGATE_COMMITMENTS_HASH,
            FINALIZED_COLLECTIVE_PUBLIC_KEY_HASH,
            FINALIZED_SHARE_COMMITMENT_HASH,
            finalizeTranscript(2), finalizeProof(),
            finalizeInput(
                epochId, 2, 2, 2,
                FINALIZED_AGGREGATE_COMMITMENTS_HASH,
                FINALIZED_COLLECTIVE_PUBLIC_KEY_HASH,
                FINALIZED_SHARE_COMMITMENT_HASH
            )
        );
        IDKGManager.Epoch memory after_ = manager.getEpoch(epochId);
        assertEq(uint256(after_.status), uint256(DKGTypes.EpochPhase.Live));
    }

    /// A finalize transcript with duplicated participant indexes
    /// ([1, 1] instead of [1, 2]) must be rejected even when both
    /// contributions are accepted, since otherwise the proof can finalize an
    /// aggregate disjoint from the on-chain accumulated `_collectiveKey`.
    function test_FinalizeEpoch_RejectsDuplicateParticipantRows() public {
        bytes12 epochId = createSelectedRound();

        manager.submitContribution(
            epochId, 1, CONTRIBUTION_COMMITMENTS_HASH, CONTRIBUTION_ENCRYPTED_SHARES_HASH,
            contributionTranscript(2), contributionProof(),
            contributionInput(epochId, 2, 2, 1, CONTRIBUTION_COMMITMENTS_HASH, CONTRIBUTION_ENCRYPTED_SHARES_HASH)
        );
        vm.prank(address(0xBEEF));
        manager.submitContribution(
            epochId, 2,
            bytes32(uint256(CONTRIBUTION_COMMITMENTS_HASH) + 1),
            bytes32(uint256(CONTRIBUTION_ENCRYPTED_SHARES_HASH) + 1),
            contributionTranscript(2), contributionProof(),
            contributionInput(
                epochId,
                2,
                2,
                2,
                bytes32(uint256(CONTRIBUTION_COMMITMENTS_HASH) + 1),
                bytes32(uint256(CONTRIBUTION_ENCRYPTED_SHARES_HASH) + 1)
            )
        );

        _advanceToFinalize(epochId);

        vm.expectRevert(IDKGManager.InvalidProofInput.selector);
        manager.finalizeEpoch(
            epochId,
            FINALIZED_AGGREGATE_COMMITMENTS_HASH,
            FINALIZED_COLLECTIVE_PUBLIC_KEY_HASH,
            FINALIZED_SHARE_COMMITMENT_HASH,
            finalizeTranscriptWithDuplicateRows(),
            finalizeProof(),
            finalizeInputWithDuplicateRows(
                epochId,
                FINALIZED_AGGREGATE_COMMITMENTS_HASH,
                FINALIZED_COLLECTIVE_PUBLIC_KEY_HASH,
                FINALIZED_SHARE_COMMITMENT_HASH
            )
        );
    }

    // `test_CreateEpoch_RejectsFinalizeNotBeforeAtOrBelowContribution` was
    // removed when phase deadlines moved from caller-supplied params to
    // contract-derived offsets. The constructor enforces that all per-phase
    // offsets are strictly positive, so the inversion the old test guarded
    // against is now structurally impossible.

    function test_CreateEpoch_RejectsBeforeNextEpochStartBlock() public {
        // First epoch goes through (cadence guard satisfied — no prior
        // epoch). Second call before nextEpochStartBlock() reverts.
        manager.createEpoch(2, 2, 2, 10000, _emptyDecryptionPolicy());
        // We are far before lastEpochStartBlock + EPOCH_DURATION_BLOCKS now.
        vm.expectRevert(IDKGManager.InvalidPhase.selector);
        manager.createEpoch(2, 2, 2, 10000, _emptyDecryptionPolicy());
        // Roll past the cadence threshold and try again — must succeed.
        vm.roll(uint256(manager.nextEpochStartBlock()));
        manager.createEpoch(2, 2, 2, 10000, _emptyDecryptionPolicy());
    }

    function test_NextEpochStartBlock_AdvancesByDuration() public {
        uint64 dur = uint64(manager.EPOCH_DURATION_BLOCKS());
        // Before any epoch: nextEpochStartBlock() == current block.
        assertEq(uint256(manager.nextEpochStartBlock()), block.number);
        manager.createEpoch(2, 2, 2, 10000, _emptyDecryptionPolicy());
        assertEq(
            uint256(manager.nextEpochStartBlock()),
            uint256(manager.lastEpochStartBlock()) + uint256(dur)
        );
    }

    function test_SubmitPartialDecryption_PersistsRecord() public {
        bytes12 epochId = createFinalizedRound();

        manager.submitPartialDecryption(
            epochId,
            bytes32(0),
            1,
            1,
            TEST_CT_C1X, TEST_CT_C1Y, TEST_CT_C2X, TEST_CT_C2Y,
            partialDecryptionHash(1),
            partialDecryptionProof(),
            partialDecryptionInput(epochId, 1, partialDecryptionHash(1))
        );

        DKGTypes.PartialDecryptionRecord memory record = manager.getPartialDecryption(epochId, bytes32(0), 1, 1);
        IDKGManager.Epoch memory epoch = manager.getEpoch(epochId);

        // `participant` and `deltaHash` are no longer persisted; off-chain consumers
        // read those from the PartialDecryptionSubmitted event.
        assertEq(uint256(record.participantIndex), 1);
        assertEq(uint256(record.ciphertextIndex), 1);
        assertEq(record.accepted ? uint256(1) : uint256(0), 1);
        assertEq(uint256(epoch.partialDecryptionCount), 1);
    }

    function test_SubmitPartialDecryption_RejectsBadProofInput() public {
        bytes12 epochId = createFinalizedRound();

        vm.expectRevert(IDKGManager.InvalidProofInput.selector);
        manager.submitPartialDecryption(
            epochId,
            bytes32(0),
            1,
            1,
            TEST_CT_C1X, TEST_CT_C1Y, TEST_CT_C2X, TEST_CT_C2Y,
            partialDecryptionHash(1),
            partialDecryptionProof(),
            PARTIAL_DECRYPTION_INPUT_BAD
        );
    }

    function test_SubmitPartialDecryption_RejectsBeforeFinalization() public {
        bytes12 epochId = createSelectedRound();

        vm.expectRevert(IDKGManager.InvalidPhase.selector);
        manager.submitPartialDecryption(
            epochId,
            bytes32(0),
            1,
            1,
            TEST_CT_C1X, TEST_CT_C1Y, TEST_CT_C2X, TEST_CT_C2Y,
            partialDecryptionHash(1),
            partialDecryptionProof(),
            partialDecryptionInput(epochId, 1, partialDecryptionHash(1))
        );
    }

    function test_SubmitPartialDecryption_RejectsDuplicates() public {
        bytes12 epochId = createFinalizedRound();

        manager.submitPartialDecryption(
            epochId,
            bytes32(0),
            1,
            1,
            TEST_CT_C1X, TEST_CT_C1Y, TEST_CT_C2X, TEST_CT_C2Y,
            partialDecryptionHash(1),
            partialDecryptionProof(),
            partialDecryptionInput(epochId, 1, partialDecryptionHash(1))
        );

        vm.expectRevert(IDKGManager.AlreadyPartiallyDecrypted.selector);
        manager.submitPartialDecryption(
            epochId,
            bytes32(0),
            1,
            1,
            TEST_CT_C1X, TEST_CT_C1Y, TEST_CT_C2X, TEST_CT_C2Y,
            partialDecryptionHash(1),
            partialDecryptionProof(),
            partialDecryptionInput(epochId, 1, partialDecryptionHash(1))
        );
    }

    function test_SubmitPartialDecryption_AllowsDistinctCiphertexts() public {
        bytes12 epochId = createFinalizedRound();
        // ciphertext 2 must also exist on-chain.
        manager.submitCiphertext(epochId, bytes32(0), 2, TEST_CT_C1X, TEST_CT_C1Y, TEST_CT_C2X, TEST_CT_C2Y);

        manager.submitPartialDecryption(
            epochId,
            bytes32(0),
            1,
            1,
            TEST_CT_C1X, TEST_CT_C1Y, TEST_CT_C2X, TEST_CT_C2Y,
            partialDecryptionHash(1),
            partialDecryptionProof(),
            partialDecryptionInput(epochId, 1, partialDecryptionHash(1))
        );
        manager.submitPartialDecryption(
            epochId,
            bytes32(0),
            1,
            2,
            TEST_CT_C1X, TEST_CT_C1Y, TEST_CT_C2X, TEST_CT_C2Y,
            partialDecryptionHash(1),
            partialDecryptionProof(),
            partialDecryptionInputCt(epochId, 1, 2, partialDecryptionHash(1))
        );

        DKGTypes.PartialDecryptionRecord memory first = manager.getPartialDecryption(epochId, bytes32(0), 1, 1);
        DKGTypes.PartialDecryptionRecord memory second = manager.getPartialDecryption(epochId, bytes32(0), 1, 2);

        assertEq(uint256(first.ciphertextIndex), 1);
        assertEq(uint256(second.ciphertextIndex), 2);
    }

    function test_CombineDecryption_PersistsRecord() public {
        bytes12 epochId = createFinalizedRound();
        // ciphertext index 1 already submitted by createFinalizedRound

        manager.submitPartialDecryption(
            epochId,
            bytes32(0),
            1,
            1,
            TEST_CT_C1X, TEST_CT_C1Y, TEST_CT_C2X, TEST_CT_C2Y,
            partialDecryptionHash(1),
            partialDecryptionProof(),
            partialDecryptionInput(epochId, 1, partialDecryptionHash(1))
        );
        vm.prank(address(0xBEEF));
        manager.submitPartialDecryption(
            epochId,
            bytes32(0),
            2,
            1,
            TEST_CT_C1X, TEST_CT_C1Y, TEST_CT_C2X, TEST_CT_C2Y,
            partialDecryptionHash(2),
            partialDecryptionProof(),
            partialDecryptionInput(epochId, 2, partialDecryptionHash(2))
        );

        uint256 plaintext = uint256(COMBINED_PLAINTEXT_HASH);
        manager.combineDecryption(
            epochId,
            bytes32(0),
            1,
            COMBINED_DECRYPTION_HASH,
            plaintext,
            decryptCombineTranscript(2),
            decryptCombineProof(),
            decryptCombineInput(epochId, 2, 2, COMBINED_DECRYPTION_HASH, plaintext)
        );

        DKGTypes.CombinedDecryptionRecord memory record = manager.getCombinedDecryption(epochId, bytes32(0), 1);
        assertEq(record.completed ? uint256(1) : uint256(0), 1);
        assertEq(record.plaintext, plaintext);
        assertEq(manager.getPlaintext(epochId, bytes32(0), 1), plaintext);
    }


    // ── liveness integration ───────────────────────────────────────────────

    function test_CreateEpoch_UsesActiveCountAsDenominator() public {
        // Register a third node that we'll reap before the epoch is created.
        address ghost = address(0xdEaD);
        vm.prank(ghost);
        // DEAD vector from cmd/operator-schnorr-vectors.
        registry.registerKey(
            3602709693320481933414169817753642284358154248428933830091019302946389143220,
            19404998569400271134603777992322348196323180940366382216870830366803640744216,
            17932491275164157352977794940779755814592019455495863353086623153818614395728,
            11035761025934598318827129374247438153606368675015247802966920305427212653389,
            1940997602491403806671742881110463830588755899359470939853733010309975750617
        );
        assertEq(registry.activeCount(), 3);
        assertEq(registry.nodeCount(), 3);

        // Age the ghost out and reap.
        vm.roll(block.number + INACTIVITY_WINDOW + 1);
        registry.reap(ghost);
        assertEq(registry.activeCount(), 2);
        assertEq(registry.nodeCount(), 3);

        // Epoch created now sees registered = activeCount = 2, not 3.
        bytes12 epochId = _createLotteryRound();

        // With α=1.0 and active=2, the threshold should be uint256.max
        // (numerator 20000 ≥ 10000) — same as the vanilla 2-node setup.
        IDKGManager.Epoch memory epoch = manager.getEpoch(epochId);
        assertEq(epoch.lotteryThreshold, type(uint256).max);
    }

    function test_ClaimSlot_RejectsReapedNode() public {
        // Reap address(0xBEEF) (one of the two registered test nodes).
        vm.roll(block.number + INACTIVITY_WINDOW + 1);
        registry.reap(address(0xBEEF));

        // Start a fresh epoch with activeCount = 1.
        // Need to wait for nextEpochStartBlock if a previous epoch was just created.
        uint64 next = manager.nextEpochStartBlock();
        if (block.number < uint256(next)) vm.roll(uint256(next));
        bytes12 epochId = manager.createEpoch(
            1,
            1,
            1,
            10000,
            _emptyDecryptionPolicy()
        );
        vm.roll(block.number + 2);

        // Reaped node cannot claim — the existing status check in claimSlot
        // now triggers because the registry flipped them to INACTIVE.
        vm.prank(address(0xBEEF));
        vm.expectRevert(IDKGManager.NotRegistered.selector);
        manager.claimSlot(epochId);

        // The still-active node can.
        manager.claimSlot(epochId);
    }

    function test_SubmitContribution_RefreshesLastActiveBlock() public {
        bytes12 epochId = createSelectedRound();

        // Record the pre-contribution lastActiveBlock for address(this).
        uint64 before = registry.getNode(address(this)).lastActiveBlock;

        // Advance a few blocks so the SSTORE actually changes value.
        vm.roll(block.number + 10);

        manager.submitContribution(
            epochId,
            1,
            CONTRIBUTION_COMMITMENTS_HASH,
            CONTRIBUTION_ENCRYPTED_SHARES_HASH,            contributionTranscript(2),
            contributionProof(),
            contributionInput(epochId, 2, 2, 1, CONTRIBUTION_COMMITMENTS_HASH, CONTRIBUTION_ENCRYPTED_SHARES_HASH)
        );

        uint64 afterBlock = registry.getNode(address(this)).lastActiveBlock;
        assertEq(uint256(afterBlock), block.number);
        assertTrue(afterBlock > before);
    }

    function test_AbortEpoch_PersistsAbortedStatus() public {
        bytes12 epochId = manager.createEpoch(2, 2, 2, 10000, _emptyDecryptionPolicy());

        manager.abortEpoch(epochId);

        IDKGManager.Epoch memory epoch = manager.getEpoch(epochId);
        assertEq(uint256(epoch.status), uint256(DKGTypes.EpochPhase.Aborted));
    }

    // ── M-01: abortEpoch cannot abort a Finalized epoch ───────────────────

    function test_AbortEpoch_RejectsFinalized() public {
        bytes12 epochId = createFinalizedRound();

        vm.expectRevert(IDKGManager.InvalidPhase.selector);
        manager.abortEpoch(epochId);
    }

    // ── M-03/M-04: constructor validation ─────────────────────────────────
    // (extendRegistration tests removed — function no longer exists in the
    // auto-cadence model.)


    function test_Constructor_RejectsZeroRegistry() public {
        vm.expectRevert(IDKGManager.InvalidAddress.selector);
        new DKGManager(
            31337,
            address(0), // zero registry
            address(verifier),
            address(partialVerifier),
            address(finalizeVerifier),
            address(decryptCombineVerifier),
            0, 0, 0, 0
        );
    }

    function test_Constructor_RejectsWrongChainId() public {
        vm.expectRevert(IDKGManager.InvalidChainId.selector);
        new DKGManager(
            1, // mainnet — not the test chain (31337)
            address(registry),
            address(verifier),
            address(partialVerifier),
            address(finalizeVerifier),
            address(decryptCombineVerifier),
            0, 0, 0, 0
        );
    }

    // ── L-02: ciphertextIndex upper bound ─────────────────────────────────

    function test_SubmitPartialDecryption_RejectsCiphertextIndexTooLarge() public {
        bytes12 epochId = createFinalizedRound();

        vm.expectRevert(IDKGManager.InvalidPartialDecryption.selector);
        manager.submitPartialDecryption(
            epochId,
            bytes32(0),
            1,
            257, // > MAX_CIPHERTEXT_INDEX (256)
            TEST_CT_C1X, TEST_CT_C1Y, TEST_CT_C2X, TEST_CT_C2Y,
            partialDecryptionHash(1),
            partialDecryptionProof(),
            partialDecryptionInput(epochId, 1, partialDecryptionHash(1))
        );
    }

    function test_CombineDecryption_RejectsCiphertextIndexTooLarge() public {
        bytes12 epochId = createFinalizedRound();

        uint256 plaintext = uint256(COMBINED_PLAINTEXT_HASH);
        vm.expectRevert(IDKGManager.InvalidCombinedDecryption.selector);
        manager.combineDecryption(
            epochId,
            bytes32(0),
            257, // > MAX_CIPHERTEXT_INDEX (256)
            COMBINED_DECRYPTION_HASH,
            plaintext,
            decryptCombineTranscript(2),
            decryptCombineProof(),
            decryptCombineInput(epochId, 2, 2, COMBINED_DECRYPTION_HASH, plaintext)
        );
    }

    // ── submitCiphertext + DecryptionPolicy ──────────────────────────────────

    function test_SubmitCiphertext_StoresHashAndIncrementsCount() public {
        bytes12 epochId = createFinalizedRound();
        // index 1 already submitted by createFinalizedRound; submit
        // another at index 2 to exercise the storage / counter path.
        bytes32 expected = keccak256(abi.encode(TEST_CT_C1X, TEST_CT_C1Y, TEST_CT_C2X, TEST_CT_C2Y));

        manager.submitCiphertext(epochId, bytes32(0), 2, TEST_CT_C1X, TEST_CT_C1Y, TEST_CT_C2X, TEST_CT_C2Y);

        assertEq(uint256(manager.getCiphertextHash(epochId, bytes32(0), 2)), uint256(expected));
        assertEq(uint256(manager.getEpoch(epochId).ciphertextCount), 2);
    }

    function test_SubmitCiphertext_RejectsDuplicateIndex() public {
        bytes12 epochId = createFinalizedRound();
        // ciphertext 1 already submitted by createFinalizedRound. The
        // duplicate submission at the same index must be rejected by
        // the write-once guard.
        vm.expectRevert(IDKGManager.CiphertextAlreadySubmitted.selector);
        manager.submitCiphertext(epochId, bytes32(0), 1, TEST_CT_C1X, TEST_CT_C1Y, TEST_CT_C2X, TEST_CT_C2Y);
    }

    function test_SubmitCiphertext_RejectsBeforeFinalized() public {
        bytes12 epochId = _createLotteryRound();

        vm.expectRevert(IDKGManager.InvalidPhase.selector);
        manager.submitCiphertext(epochId, bytes32(0), 1, TEST_CT_C1X, TEST_CT_C1Y, TEST_CT_C2X, TEST_CT_C2Y);
    }

    function test_SubmitCiphertext_OwnerOnly_BlocksOthers() public {
        bytes12 epochId = _createRoundWithDecryptionPolicy(
            DKGTypes.DecryptionPolicy({
                ownerOnly: true,
                maxDecryptions: 0,
                notBeforeBlock: 0, notBeforeTimestamp: 0,
                notAfterBlock: 0, notAfterTimestamp: 0
            })
        );

        vm.prank(address(0xCAFE));
        vm.expectRevert(IDKGManager.NotOwner.selector);
        manager.submitCiphertext(epochId, bytes32(0), 1, TEST_CT_C1X, TEST_CT_C1Y, TEST_CT_C2X, TEST_CT_C2Y);

        // Owner can submit.
        manager.submitCiphertext(epochId, bytes32(0), 1, TEST_CT_C1X, TEST_CT_C1Y, TEST_CT_C2X, TEST_CT_C2Y);
    }

    function test_SubmitCiphertext_NotBeforeBlock_Blocks() public {
        uint64 unlockBlock = uint64(block.number + 1000);
        bytes12 epochId = _createRoundWithDecryptionPolicy(
            DKGTypes.DecryptionPolicy({
                ownerOnly: false,
                maxDecryptions: 0,
                notBeforeBlock: unlockBlock,
                notBeforeTimestamp: 0,
                notAfterBlock: 0,
                notAfterTimestamp: 0
            })
        );

        vm.expectRevert(IDKGManager.DecryptionNotYetAllowed.selector);
        manager.submitCiphertext(epochId, bytes32(0), 1, TEST_CT_C1X, TEST_CT_C1Y, TEST_CT_C2X, TEST_CT_C2Y);

        vm.roll(uint256(unlockBlock));
        manager.submitCiphertext(epochId, bytes32(0), 1, TEST_CT_C1X, TEST_CT_C1Y, TEST_CT_C2X, TEST_CT_C2Y);
    }

    // Note: timestamp-based gates (notBeforeTimestamp / notAfterTimestamp) share the
    // same revert paths as the block-based gates tested here; the minimal forge-std
    // shim in this repo does not expose vm.warp, so timestamp cases are exercised via
    // the Go integration suite (cmd/davinci-dkg-node tests) rather than here.

    function test_SubmitCiphertext_NotAfterBlock_Blocks() public {
        uint64 cutoff = uint64(block.number + 50);
        bytes12 epochId = _createRoundWithDecryptionPolicy(
            DKGTypes.DecryptionPolicy({
                ownerOnly: false,
                maxDecryptions: 0,
                notBeforeBlock: 0,
                notBeforeTimestamp: 0,
                notAfterBlock: cutoff,
                notAfterTimestamp: 0
            })
        );

        vm.roll(uint256(cutoff) + 1);
        vm.expectRevert(IDKGManager.DecryptionExpired.selector);
        manager.submitCiphertext(epochId, bytes32(0), 1, TEST_CT_C1X, TEST_CT_C1Y, TEST_CT_C2X, TEST_CT_C2Y);
    }

    function test_SubmitCiphertext_MaxDecryptions_Caps() public {
        bytes12 epochId = _createRoundWithDecryptionPolicy(
            DKGTypes.DecryptionPolicy({
                ownerOnly: false,
                maxDecryptions: 2,
                notBeforeBlock: 0, notBeforeTimestamp: 0,
                notAfterBlock: 0, notAfterTimestamp: 0
            })
        );

        // The cap check doesn't care about distinct coordinates, only the
        // submission count, but the well-formedness check rejects identity
        // — use the prime-subgroup test vectors.
        manager.submitCiphertext(epochId, bytes32(0), 1, TEST_CT_C1X, TEST_CT_C1Y, TEST_CT_C2X, TEST_CT_C2Y);
        manager.submitCiphertext(epochId, bytes32(0), 2, TEST_CT_C1X, TEST_CT_C1Y, TEST_CT_C2X, TEST_CT_C2Y);

        vm.expectRevert(IDKGManager.DecryptionLimitReached.selector);
        manager.submitCiphertext(epochId, bytes32(0), 3, TEST_CT_C1X, TEST_CT_C1Y, TEST_CT_C2X, TEST_CT_C2Y);
    }

    function test_SubmitCiphertext_RejectsOffCurvePoint() public {
        bytes12 epochId = createFinalizedRound();

        // (7001, 8001) does NOT satisfy a·x² + y² = 1 + d·x²·y² (mod Q).
        vm.expectRevert(IDKGManager.InvalidCiphertext.selector);
        manager.submitCiphertext(epochId, bytes32(0), 1, 7001, 8001, 0, 1);

        // Canonical-range but off-curve: e.g. (1, 1) — 168700 + 1 = 168701; 1 + 168696 = 168697.
        vm.expectRevert(IDKGManager.InvalidCiphertext.selector);
        manager.submitCiphertext(epochId, bytes32(0), 1, 1, 1, 0, 1);

        // Bad c2 with valid c1 also reverts.
        vm.expectRevert(IDKGManager.InvalidCiphertext.selector);
        manager.submitCiphertext(epochId, bytes32(0), 1, 0, 1, 1, 1);

        // Coordinates ≥ Q (non-canonical) rejected even if they'd be on-curve post-reduction.
        uint256 Q = 21888242871839275222246405745257275088548364400416034343698204186575808495617;
        vm.expectRevert(IDKGManager.InvalidCiphertext.selector);
        manager.submitCiphertext(epochId, bytes32(0), 1, Q, 1, 0, 1);
    }

    function test_CreateEpoch_RejectsInvalidDecryptionPolicyWindow() public {
        // notAfterBlock <= notBeforeBlock is a degenerate window.
        DKGTypes.DecryptionPolicy memory bad = DKGTypes.DecryptionPolicy({
            ownerOnly: false,
            maxDecryptions: 0,
            notBeforeBlock: 100,
            notBeforeTimestamp: 0,
            notAfterBlock: 100, // equal → empty window
            notAfterTimestamp: 0
        });

        vm.expectRevert(IDKGManager.InvalidDecryptionPolicy.selector);
        manager.createEpoch(2, 2, 2, 10000, bad);
    }

    function test_SubmitPartialDecryption_RejectsWhenCiphertextNotSubmitted() public {
        bytes12 epochId = createFinalizedRound();

        // The gate is enforced at submitPartialDecryption itself: the
        // proof can only bind to an existing on-chain ciphertext.
        // createFinalizedRound submits index 1, so use index 2 which
        // was never submitted.
        vm.expectRevert(IDKGManager.CiphertextNotSubmitted.selector);
        manager.submitPartialDecryption(
            epochId,
            bytes32(0), 1, 2,
            TEST_CT_C1X, TEST_CT_C1Y, TEST_CT_C2X, TEST_CT_C2Y,
            partialDecryptionHash(1),
            partialDecryptionProof(), partialDecryptionInputCt(epochId, 1, 2, partialDecryptionHash(1))
        );
    }

    /// @dev Build a finalized epoch with a custom DecryptionPolicy.
    function _createRoundWithDecryptionPolicy(DKGTypes.DecryptionPolicy memory dp)
        internal
        returns (bytes12 epochId)
    {
        uint64 next = manager.nextEpochStartBlock();
        if (block.number < uint256(next)) vm.roll(uint256(next));
        epochId = manager.createEpoch(2, 2, 2, 10000, dp);
        vm.roll(block.number + 2);
        _claimAllSlots(epochId);

        manager.submitContribution(
            epochId, 1, CONTRIBUTION_COMMITMENTS_HASH, CONTRIBUTION_ENCRYPTED_SHARES_HASH,
            contributionTranscript(2), contributionProof(),
            contributionInput(epochId, 2, 2, 1, CONTRIBUTION_COMMITMENTS_HASH, CONTRIBUTION_ENCRYPTED_SHARES_HASH)
        );
        vm.prank(address(0xBEEF));
        manager.submitContribution(
            epochId, 2,
            bytes32(uint256(CONTRIBUTION_COMMITMENTS_HASH) + 1),
            bytes32(uint256(CONTRIBUTION_ENCRYPTED_SHARES_HASH) + 1),
            contributionTranscript(2), contributionProof(),
            contributionInput(
                epochId,
                2,
                2,
                2,
                bytes32(uint256(CONTRIBUTION_COMMITMENTS_HASH) + 1),
                bytes32(uint256(CONTRIBUTION_ENCRYPTED_SHARES_HASH) + 1)
            )
        );
        _advanceToFinalize(epochId);
        manager.finalizeEpoch(
            epochId,
            FINALIZED_AGGREGATE_COMMITMENTS_HASH,
            FINALIZED_COLLECTIVE_PUBLIC_KEY_HASH,
            FINALIZED_SHARE_COMMITMENT_HASH,
            finalizeTranscript(2), finalizeProof(),
            finalizeInput(
                epochId, 2, 2, 2,
                FINALIZED_AGGREGATE_COMMITMENTS_HASH,
                FINALIZED_COLLECTIVE_PUBLIC_KEY_HASH,
                FINALIZED_SHARE_COMMITMENT_HASH
            )
        );
    }
}
