// SPDX-License-Identifier: AGPL-3.0-or-later
pragma solidity 0.8.28;

import {Test} from "forge-std/Test.sol";
import {DKGRegistry} from "../src/DKGRegistry.sol";
import {IDKGRegistry} from "../src/interfaces/IDKGRegistry.sol";

/// @title DKGRegistrySchnorrTest
/// @notice Targeted Schnorr-PoK verification tests for the DKGRegistry.
///         Vectors generated by `cmd/operator-schnorr-vectors`; secrets:
///
///           this:  4096 (witness 8192)
///           BEEF:  4113 (witness 8215)
///           CAFE:  4130 (witness 8238)
///
///         The Foundry default `address(this)` is
///         0xb4c79daB8f259C7Aee6E5b2Aa729821864227e84.
///
///         Cross-impl agreement with Go is the foundation here: any drift
///         in the Poseidon parameter set, the BabyJubJub scalar mul, or
///         the transcript layout breaks the registry.
contract DKGRegistrySchnorrTest is Test {
    DKGRegistry public registry;

    // ─── Vectors generated from cmd/operator-schnorr-vectors ──────────────────
    uint256 internal constant THIS_PUBX =
        17765672829315743641357949553430354448961270408100494783209553303687184365803;
    uint256 internal constant THIS_PUBY =
        13591243454297365848719372676992908085762757043204242277513940025707896351954;
    uint256 internal constant THIS_AX =
        8735331066154608227876753674818247062971894554643955333501578253334124637538;
    uint256 internal constant THIS_AY =
        21272836954776476886917169960736847641993451090581680169106828110848349153636;
    uint256 internal constant THIS_Z =
        634991905351915179466021589793371740337503603889079247266319766701163909122;

    uint256 internal constant BEEF_PUBX =
        10228722604559478181013548940833210623190136968531440936190496170400150013980;
    uint256 internal constant BEEF_PUBY =
        13886497050333420293068628977630539070604271411621054562122682889313139677221;
    uint256 internal constant BEEF_AX =
        14566234973743316386655481200503006158732416518867749191804063760238069794878;
    uint256 internal constant BEEF_AY =
        13078057343376780948266496972118389875598288245980415388506507934563371992806;
    uint256 internal constant BEEF_Z =
        38399935749416834248216881218311558175518919460029821342996644512919061006;

    function setUp() public {
        registry = new DKGRegistry(1_000);
    }

    function test_RegisterKey_AcceptsValidProof() public {
        registry.registerKey(THIS_PUBX, THIS_PUBY, THIS_AX, THIS_AY, THIS_Z);
        IDKGRegistry.NodeKey memory n = registry.getNode(address(this));
        assertEq(n.pubX, THIS_PUBX);
        assertEq(n.pubY, THIS_PUBY);
        assertEq(uint256(n.status), uint256(IDKGRegistry.NodeStatus.ACTIVE));
        assertEq(uint256(registry.activeCount()), 1);
        assertEq(uint256(registry.nodeCount()), 1);
    }

    function test_RegisterKey_AcceptsValidProof_FromBEEF() public {
        vm.prank(address(0xBEEF));
        registry.registerKey(BEEF_PUBX, BEEF_PUBY, BEEF_AX, BEEF_AY, BEEF_Z);
        IDKGRegistry.NodeKey memory n = registry.getNode(address(0xBEEF));
        assertEq(n.pubX, BEEF_PUBX);
        assertEq(n.pubY, BEEF_PUBY);
    }

    function test_RegisterKey_RejectsTamperedZ() public {
        vm.expectRevert(IDKGRegistry.InvalidSchnorrProof.selector);
        registry.registerKey(THIS_PUBX, THIS_PUBY, THIS_AX, THIS_AY, THIS_Z + 1);
    }

    function test_RegisterKey_RejectsWrongA() public {
        // Substitute BEEF's nonce point (still on-curve, so passes the
        // canonical / on-curve check) but the Schnorr response is THIS's.
        // The verification z·G == A + c·PK_op fails because c is computed
        // from the wrong A, the LHS and RHS no longer match.
        vm.expectRevert(IDKGRegistry.InvalidSchnorrProof.selector);
        registry.registerKey(THIS_PUBX, THIS_PUBY, BEEF_AX, BEEF_AY, THIS_Z);
    }

    function test_RegisterKey_RejectsCrossOperatorReplay() public {
        // Use BEEF's vector but call from address(this). The Schnorr
        // challenge binds the operator address, so the proof must fail.
        vm.expectRevert(IDKGRegistry.InvalidSchnorrProof.selector);
        registry.registerKey(BEEF_PUBX, BEEF_PUBY, BEEF_AX, BEEF_AY, BEEF_Z);
    }

    /// DEEPSEEK §4.4 hardening: a Schnorr PoK built for the organizer
    /// transcript (poseidon4(domain_org, eid, pkX, pkY) → poseidon4(...))
    /// must NOT verify against the operator transcript
    /// (poseidon5(domain_op, addr, pkX, pkY, ax) → poseidon2(inner, ay)).
    /// The two domain digests are distinct, so the recomputed challenge
    /// differs and z·G ≠ A + c·PK. Vectors taken verbatim from
    /// `tests/vectors/schnorr.json`'s `organizer[0]` ("basic") row.
    function test_RegisterKey_RejectsCrossProtocolOrganizerReplay() public {
        uint256 ORG_PKX =
            2551376366345596520668104989253144960410630608926530650066884627713896730967;
        uint256 ORG_PKY =
            14727786028764125722551859086294511396595193815411622622802560272781335271382;
        uint256 ORG_AX =
            5002352452212114768463826499411425210834813468446571301155136898290987671594;
        uint256 ORG_AY =
            15091619694907097646422829955403775793029803448055800751664011379476921319041;
        uint256 ORG_Z =
            2135262704773283848579120976154005381065501210301413341792482791354350470252;
        vm.expectRevert(IDKGRegistry.InvalidSchnorrProof.selector);
        registry.registerKey(ORG_PKX, ORG_PKY, ORG_AX, ORG_AY, ORG_Z);
    }

    function test_RegisterKey_RejectsIdentityPubKey() public {
        vm.expectRevert(IDKGRegistry.PointIsIdentity.selector);
        registry.registerKey(0, 1, THIS_AX, THIS_AY, THIS_Z);
    }

    function test_RegisterKey_RejectsOffCurvePubKey() public {
        // Increment x by 1 — no longer satisfies curve equation.
        vm.expectRevert(IDKGRegistry.PointNotOnCurve.selector);
        registry.registerKey(THIS_PUBX + 1, THIS_PUBY, THIS_AX, THIS_AY, THIS_Z);
    }

    function test_RegisterKey_RejectsDuplicate() public {
        registry.registerKey(THIS_PUBX, THIS_PUBY, THIS_AX, THIS_AY, THIS_Z);
        vm.expectRevert(IDKGRegistry.AlreadyRegistered.selector);
        registry.registerKey(THIS_PUBX, THIS_PUBY, THIS_AX, THIS_AY, THIS_Z);
    }

    function test_UpdateKey_RequiresProof() public {
        registry.registerKey(THIS_PUBX, THIS_PUBY, THIS_AX, THIS_AY, THIS_Z);
        // Update with the same key + proof works.
        registry.updateKey(THIS_PUBX, THIS_PUBY, THIS_AX, THIS_AY, THIS_Z);
        // Tampered z should fail.
        vm.expectRevert(IDKGRegistry.InvalidSchnorrProof.selector);
        registry.updateKey(THIS_PUBX, THIS_PUBY, THIS_AX, THIS_AY, THIS_Z + 1);
    }

    function test_UpdateKey_FailsForUnregistered() public {
        vm.expectRevert(IDKGRegistry.NotRegistered.selector);
        registry.updateKey(THIS_PUBX, THIS_PUBY, THIS_AX, THIS_AY, THIS_Z);
    }
}
