// SPDX-License-Identifier: AGPL-3.0-or-later
pragma solidity 0.8.28;

import {Test} from "forge-std/Test.sol";
import {DKGRegistry} from "../src/DKGRegistry.sol";
import {IDKGRegistry} from "../src/interfaces/IDKGRegistry.sol";

/// @title DKGRegistryTest
/// @notice Lifecycle tests for DKGRegistry. The Schnorr-PoK happy/error paths
///         live in DKGRegistrySchnorr.t.sol; here we exercise reap, reactivate,
///         heartbeat, manager wiring, and activeCount churn. All `registerKey`
///         calls use the canonical Schnorr vectors generated by
///         `cmd/operator-schnorr-vectors` (one per test address).
contract DKGRegistryTest is Test {
    uint64 internal constant WINDOW = 1_000;

    DKGRegistry public registry;
    // Match the addresses fed to cmd/operator-schnorr-vectors verbatim:
    // 0xA11CE and 0xB0B as uint160 literals.
    address internal alice = address(0xA11CE);
    address internal bob = address(0xB0B);
    address internal fakeManager = address(0xBEEF);

    // ─── Schnorr vectors (cmd/operator-schnorr-vectors) ─────────────────────
    // ALICE: secret=4147, witness=8261
    uint256 internal constant ALICE_PUBX =
        14666979294172776374634275498241310759674509575452256743546893482427808967539;
    uint256 internal constant ALICE_PUBY =
        16568773859060023308888034681483224034881825787861296311803627274237556869649;
    uint256 internal constant ALICE_AX =
        206825796546323573150801242605652465781823711295602898923500400375891572685;
    uint256 internal constant ALICE_AY =
        14223109950820609858208501628131627333362274908883166606890781114024603385194;
    uint256 internal constant ALICE_Z =
        66458635765473073512777717039878111580187214052638150485757113243289885172;

    // BOB: secret=4164, witness=8284
    uint256 internal constant BOB_PUBX =
        15808864409125743623158347959567088069558702978719665925779366439337047883532;
    uint256 internal constant BOB_PUBY =
        10393796518077176589394647112270228307611805147467321584192748934641013045092;
    uint256 internal constant BOB_AX =
        1031141500146150815800412449905028929756770195584712790143493778783321106841;
    uint256 internal constant BOB_AY =
        9715605471543439389811216456914304030827505649477665293662959132237367289009;
    uint256 internal constant BOB_Z =
        212598820789966985197462179874677615540451920603148373515126349397495800566;

    // THIS: secret=4096, witness=8192 (default Foundry test address).
    uint256 internal constant THIS_PUBX =
        17765672829315743641357949553430354448961270408100494783209553303687184365803;
    uint256 internal constant THIS_PUBY =
        13591243454297365848719372676992908085762757043204242277513940025707896351954;
    uint256 internal constant THIS_AX =
        8735331066154608227876753674818247062971894554643955333501578253334124637538;
    uint256 internal constant THIS_AY =
        21272836954776476886917169960736847641993451090581680169106828110848349153636;
    uint256 internal constant THIS_Z =
        634991905351915179466021589793371740337503603889079247266319766701163909122;

    function setUp() public {
        registry = new DKGRegistry(WINDOW);
    }

    function _registerAlice() internal {
        vm.prank(alice);
        registry.registerKey(ALICE_PUBX, ALICE_PUBY, ALICE_AX, ALICE_AY, ALICE_Z);
    }

    function _registerBob() internal {
        vm.prank(bob);
        registry.registerKey(BOB_PUBX, BOB_PUBY, BOB_AX, BOB_AY, BOB_Z);
    }

    function _updateAlice() internal {
        vm.prank(alice);
        // Re-prove with the same key — exercises updateKey's Schnorr path
        // without needing a second key vector.
        registry.updateKey(ALICE_PUBX, ALICE_PUBY, ALICE_AX, ALICE_AY, ALICE_Z);
    }

    // ── registration ──────────────────────────────────────────────────────

    function test_RegisterKey_DefaultIsNone() public view {
        IDKGRegistry.NodeKey memory key = registry.getNode(address(this));
        assertEq(uint256(key.pubX), 0);
        assertEq(uint256(key.pubY), 0);
        assertEq(uint8(key.status), uint8(IDKGRegistry.NodeStatus.NONE));
    }

    function test_RegisterKey_PersistsCoordinates() public {
        registry.registerKey(THIS_PUBX, THIS_PUBY, THIS_AX, THIS_AY, THIS_Z);

        IDKGRegistry.NodeKey memory key = registry.getNode(address(this));

        assertEq(key.operator, address(this));
        assertEq(key.pubX, THIS_PUBX);
        assertEq(key.pubY, THIS_PUBY);
        assertEq(uint8(key.status), uint8(IDKGRegistry.NodeStatus.ACTIVE));
    }

    function test_RegisterKey_RejectsDuplicateRegistration() public {
        registry.registerKey(THIS_PUBX, THIS_PUBY, THIS_AX, THIS_AY, THIS_Z);

        vm.expectRevert(IDKGRegistry.AlreadyRegistered.selector);
        registry.registerKey(THIS_PUBX, THIS_PUBY, THIS_AX, THIS_AY, THIS_Z);
    }

    function test_UpdateKey_PersistsNewKey() public {
        registry.registerKey(THIS_PUBX, THIS_PUBY, THIS_AX, THIS_AY, THIS_Z);
        // Update with the same key (re-prove). Schnorr path is exercised by
        // DKGRegistrySchnorr.t.sol; here we only verify the lifecycle update.
        registry.updateKey(THIS_PUBX, THIS_PUBY, THIS_AX, THIS_AY, THIS_Z);

        IDKGRegistry.NodeKey memory key = registry.getNode(address(this));
        assertEq(key.pubX, THIS_PUBX);
    }

    // ── liveness ──────────────────────────────────────────────────────────

    function test_RegisterKey_InitialisesLiveness() public {
        vm.roll(123);
        _registerAlice();

        IDKGRegistry.NodeKey memory key = registry.getNode(alice);
        assertEq(uint8(key.status), uint8(IDKGRegistry.NodeStatus.ACTIVE));
        assertEq(key.lastActiveBlock, 123);
        assertEq(registry.activeCount(), 1);
        assertEq(registry.nodeCount(), 1);
        assertTrue(registry.isActive(alice));
    }

    function test_Reap_RejectsFreshNode() public {
        _registerAlice();

        vm.expectRevert(IDKGRegistry.StillActive.selector);
        registry.reap(alice);
    }

    function test_Reap_RejectsCooldownBoundary() public {
        vm.roll(100);
        _registerAlice();

        vm.roll(100 + WINDOW);
        vm.expectRevert(IDKGRegistry.StillActive.selector);
        registry.reap(alice);
    }

    function test_Reap_SucceedsAfterWindow() public {
        vm.roll(100);
        _registerAlice();

        vm.roll(100 + WINDOW + 1);
        registry.reap(alice);

        IDKGRegistry.NodeKey memory key = registry.getNode(alice);
        assertEq(uint8(key.status), uint8(IDKGRegistry.NodeStatus.INACTIVE));
        assertEq(registry.activeCount(), 0);
        assertEq(registry.nodeCount(), 1);
        assertFalse(registry.isActive(alice));
    }

    function test_Reap_RejectsAlreadyInactive() public {
        _registerAlice();
        vm.roll(block.number + WINDOW + 1);
        registry.reap(alice);

        vm.expectRevert(IDKGRegistry.NotActive.selector);
        registry.reap(alice);
    }

    function test_Reap_RejectsUnregisteredOperator() public {
        vm.expectRevert(IDKGRegistry.NotActive.selector);
        registry.reap(alice);
    }

    function test_Reactivate_RestoresActiveRow() public {
        _registerAlice();
        vm.roll(block.number + WINDOW + 1);
        registry.reap(alice);

        vm.roll(block.number + 5);
        vm.prank(alice);
        registry.reactivate();

        IDKGRegistry.NodeKey memory key = registry.getNode(alice);
        assertEq(uint8(key.status), uint8(IDKGRegistry.NodeStatus.ACTIVE));
        assertEq(key.lastActiveBlock, uint64(block.number));
        assertEq(registry.activeCount(), 1);
    }

    function test_Reactivate_RejectsActiveCaller() public {
        _registerAlice();

        vm.expectRevert(IDKGRegistry.NotInactive.selector);
        vm.prank(alice);
        registry.reactivate();
    }

    function test_UpdateKey_ReactivatesInactive() public {
        _registerAlice();
        vm.roll(block.number + WINDOW + 1);
        registry.reap(alice);
        assertEq(registry.activeCount(), 0);

        _updateAlice();

        IDKGRegistry.NodeKey memory key = registry.getNode(alice);
        assertEq(uint8(key.status), uint8(IDKGRegistry.NodeStatus.ACTIVE));
        assertEq(key.lastActiveBlock, uint64(block.number));
        assertEq(registry.activeCount(), 1);
    }

    function test_Heartbeat_UpdatesLastActiveBlock() public {
        vm.roll(100);
        _registerAlice();
        assertEq(registry.getNode(alice).lastActiveBlock, 100);

        vm.roll(200);
        vm.prank(alice);
        registry.heartbeat();
        assertEq(registry.getNode(alice).lastActiveBlock, 200);
    }

    function test_Heartbeat_RejectsInactive() public {
        _registerAlice();
        vm.roll(block.number + WINDOW + 1);
        registry.reap(alice);

        vm.expectRevert(IDKGRegistry.NotActive.selector);
        vm.prank(alice);
        registry.heartbeat();
    }

    // ── manager wiring ────────────────────────────────────────────────────

    function test_SetManager_LocksAfterFirstCall() public {
        registry.setManager(fakeManager);
        assertEq(registry.manager(), fakeManager);

        vm.expectRevert(IDKGRegistry.ManagerAlreadySet.selector);
        registry.setManager(address(0xDEAD));
    }

    function test_SetManager_RejectsZero() public {
        vm.expectRevert(IDKGRegistry.InvalidAddress.selector);
        registry.setManager(address(0));
    }

    function test_SetManager_RejectsNonDeployer() public {
        vm.expectRevert(IDKGRegistry.Unauthorized.selector);
        vm.prank(alice);
        registry.setManager(fakeManager);
    }

    function test_MarkActive_OnlyManager() public {
        registry.setManager(fakeManager);
        _registerAlice();

        vm.expectRevert(IDKGRegistry.NotManager.selector);
        registry.markActive(alice);

        vm.roll(500);
        vm.prank(fakeManager);
        registry.markActive(alice);
        assertEq(registry.getNode(alice).lastActiveBlock, 500);
    }

    function test_MarkActive_RequiresManagerSet() public {
        _registerAlice();

        vm.expectRevert(IDKGRegistry.ManagerNotSet.selector);
        vm.prank(fakeManager);
        registry.markActive(alice);
    }

    function test_MarkActive_NoOpOnInactive() public {
        registry.setManager(fakeManager);

        vm.roll(10);
        _registerAlice();

        vm.roll(10 + WINDOW + 1);
        registry.reap(alice);
        uint64 frozen = registry.getNode(alice).lastActiveBlock;

        vm.roll(block.number + 5);
        vm.prank(fakeManager);
        registry.markActive(alice);

        assertEq(registry.getNode(alice).lastActiveBlock, frozen);
        assertEq(
            uint8(registry.getNode(alice).status),
            uint8(IDKGRegistry.NodeStatus.INACTIVE)
        );
    }

    function test_ActiveCount_TracksChurn() public {
        registry.setManager(fakeManager);

        _registerAlice();
        _registerBob();
        assertEq(registry.activeCount(), 2);

        vm.roll(block.number + WINDOW + 1);
        registry.reap(alice);
        assertEq(registry.activeCount(), 1);

        vm.prank(alice);
        registry.reactivate();
        assertEq(registry.activeCount(), 2);
    }
}
