// SPDX-License-Identifier: AGPL-3.0-or-later
pragma solidity 0.8.28;

import {Test} from "forge-std/Test.sol";
import {PoseidonT2} from "poseidon-solidity/PoseidonT2.sol";
import {PoseidonT3} from "poseidon-solidity/PoseidonT3.sol";
import {PoseidonT6} from "poseidon-solidity/PoseidonT6.sol";

/// @title PoseidonTest
/// @notice Tests cross-impl Poseidon agreement: vendored
///         `chancehudson/poseidon-solidity` (T2, T3, T6) must produce the
///         same outputs as `iden3/go-iden3-crypto/poseidon` (used by the
///         Go DKG node and by `circomlibjs` in the TS SDK).
///
///         The vectors below were generated by `/tmp/poseidon_vectors.go`.
///         Cross-impl consistency for these primitives is the foundation
///         the DLEQ and Schnorr challenge derivations build on; if it
///         breaks, every signature path silently disagrees on the hash.
contract PoseidonTest is Test {
    function test_T2_HashOfZero() public pure {
        uint256[1] memory inp = [uint256(0)];
        uint256 got = PoseidonT2.hash(inp);
        assertEq(
            got,
            19014214495641488759237505126948346942972912379615652741039992445865937985820
        );
    }

    function test_T2_HashOf123() public pure {
        uint256[1] memory inp = [uint256(123)];
        uint256 got = PoseidonT2.hash(inp);
        assertEq(
            got,
            9904028930859697121695025471312564917337032846528014134060777877259199866166
        );
    }

    function test_T3_HashOf1And2() public pure {
        uint256[2] memory inp = [uint256(1), uint256(2)];
        uint256 got = PoseidonT3.hash(inp);
        assertEq(
            got,
            7853200120776062878684798364095072458815029376092732009249414926327459813530
        );
    }

    function test_T6_HashOf1Through5() public pure {
        uint256[5] memory inp = [uint256(1), uint256(2), uint256(3), uint256(4), uint256(5)];
        uint256 got = PoseidonT6.hash(inp);
        assertEq(
            got,
            6183221330272524995739186171720101788151706631170188140075976616310159254464
        );
    }
}
