// Complete ABI for the DKG Manager and Registry contracts.
// Includes all functions (read and write), events, and custom errors.

export const dkgManagerAbi = [
  // ── write functions ───────────────────────────────────────────────────────
  {
    type: 'function',
    name: 'createRound',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'threshold', type: 'uint16' },
      { name: 'committeeSize', type: 'uint16' },
      { name: 'minValidContributions', type: 'uint16' },
      { name: 'lotteryAlphaBps', type: 'uint16' },
      { name: 'seedDelay', type: 'uint16' },
      { name: 'registrationDeadlineBlock', type: 'uint64' },
      { name: 'contributionDeadlineBlock', type: 'uint64' },
      { name: 'finalizeNotBeforeBlock', type: 'uint64' },
      { name: 'disclosureAllowed', type: 'bool' },
      {
        name: 'decryptionPolicy',
        type: 'tuple',
        components: [
          { name: 'ownerOnly', type: 'bool' },
          { name: 'maxDecryptions', type: 'uint16' },
          { name: 'notBeforeBlock', type: 'uint64' },
          { name: 'notBeforeTimestamp', type: 'uint64' },
          { name: 'notAfterBlock', type: 'uint64' },
          { name: 'notAfterTimestamp', type: 'uint64' },
        ],
      },
    ],
    outputs: [{ name: '', type: 'bytes12' }],
  },
  {
    type: 'function',
    name: 'submitCiphertext',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'roundId', type: 'bytes12' },
      { name: 'ciphertextIndex', type: 'uint16' },
      { name: 'c1x', type: 'uint256' },
      { name: 'c1y', type: 'uint256' },
      { name: 'c2x', type: 'uint256' },
      { name: 'c2y', type: 'uint256' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'claimSlot',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'roundId', type: 'bytes12' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'extendRegistration',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'roundId', type: 'bytes12' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'submitContribution',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'roundId', type: 'bytes12' },
      { name: 'contributorIndex', type: 'uint16' },
      { name: 'commitmentsHash', type: 'bytes32' },
      { name: 'encryptedSharesHash', type: 'bytes32' },
      { name: 'commitment0X', type: 'uint256' },
      { name: 'commitment0Y', type: 'uint256' },
      { name: 'transcript', type: 'bytes' },
      { name: 'proof', type: 'bytes' },
      { name: 'input', type: 'bytes' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'getCollectivePublicKey',
    stateMutability: 'view',
    inputs: [{ name: 'roundId', type: 'bytes12' }],
    outputs: [
      {
        name: '',
        type: 'tuple',
        components: [
          { name: 'x', type: 'uint256' },
          { name: 'y', type: 'uint256' },
        ],
      },
    ],
  },
  {
    type: 'function',
    name: 'finalizeRound',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'roundId', type: 'bytes12' },
      { name: 'aggregateCommitmentsHash', type: 'bytes32' },
      { name: 'collectivePublicKeyHash', type: 'bytes32' },
      { name: 'shareCommitmentHash', type: 'bytes32' },
      { name: 'transcript', type: 'bytes' },
      { name: 'proof', type: 'bytes' },
      { name: 'input', type: 'bytes' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'submitPartialDecryption',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'roundId', type: 'bytes12' },
      { name: 'participantIndex', type: 'uint16' },
      { name: 'ciphertextIndex', type: 'uint16' },
      { name: 'deltaHash', type: 'bytes32' },
      { name: 'proof', type: 'bytes' },
      { name: 'input', type: 'bytes' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'combineDecryption',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'roundId', type: 'bytes12' },
      { name: 'ciphertextIndex', type: 'uint16' },
      { name: 'combineHash', type: 'bytes32' },
      { name: 'plaintext', type: 'uint256' },
      { name: 'transcript', type: 'bytes' },
      { name: 'proof', type: 'bytes' },
      { name: 'input', type: 'bytes' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'submitRevealedShare',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'roundId', type: 'bytes12' },
      { name: 'participantIndex', type: 'uint16' },
      { name: 'shareValue', type: 'uint256' },
      { name: 'proof', type: 'bytes' },
      { name: 'input', type: 'bytes' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'reconstructSecret',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'roundId', type: 'bytes12' },
      { name: 'disclosureHash', type: 'bytes32' },
      { name: 'reconstructedSecretHash', type: 'bytes32' },
      { name: 'transcript', type: 'bytes' },
      { name: 'proof', type: 'bytes' },
      { name: 'input', type: 'bytes' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'abortRound',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'roundId', type: 'bytes12' }],
    outputs: [],
  },

  // ── view functions ────────────────────────────────────────────────────────
  {
    type: 'function',
    name: 'roundNonce',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint64' }],
  },
  {
    type: 'function',
    name: 'CHAIN_ID',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint32' }],
  },
  {
    type: 'function',
    name: 'ROUND_PREFIX',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint32' }],
  },
  {
    type: 'function',
    name: 'REGISTRY',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'function',
    name: 'getRound',
    stateMutability: 'view',
    inputs: [{ name: 'roundId', type: 'bytes12' }],
    outputs: [
      {
        name: '',
        type: 'tuple',
        components: [
          { name: 'organizer', type: 'address' },
          {
            name: 'policy',
            type: 'tuple',
            components: [
              { name: 'threshold', type: 'uint16' },
              { name: 'committeeSize', type: 'uint16' },
              { name: 'minValidContributions', type: 'uint16' },
              { name: 'lotteryAlphaBps', type: 'uint16' },
              { name: 'seedDelay', type: 'uint16' },
              { name: 'registrationDeadlineBlock', type: 'uint64' },
              { name: 'contributionDeadlineBlock', type: 'uint64' },
              { name: 'finalizeNotBeforeBlock', type: 'uint64' },
              { name: 'disclosureAllowed', type: 'bool' },
            ],
          },
          {
            name: 'decryptionPolicy',
            type: 'tuple',
            components: [
              { name: 'ownerOnly', type: 'bool' },
              { name: 'maxDecryptions', type: 'uint16' },
              { name: 'notBeforeBlock', type: 'uint64' },
              { name: 'notBeforeTimestamp', type: 'uint64' },
              { name: 'notAfterBlock', type: 'uint64' },
              { name: 'notAfterTimestamp', type: 'uint64' },
            ],
          },
          { name: 'status', type: 'uint8' },
          { name: 'nonce', type: 'uint64' },
          { name: 'seedBlock', type: 'uint64' },
          { name: 'seed', type: 'bytes32' },
          { name: 'lotteryThreshold', type: 'uint256' },
          { name: 'claimedCount', type: 'uint16' },
          { name: 'contributionCount', type: 'uint16' },
          { name: 'partialDecryptionCount', type: 'uint16' },
          { name: 'revealedShareCount', type: 'uint16' },
          { name: 'ciphertextCount', type: 'uint16' },
        ],
      },
    ],
  },
  {
    type: 'function',
    name: 'selectedParticipants',
    stateMutability: 'view',
    inputs: [{ name: 'roundId', type: 'bytes12' }],
    outputs: [{ name: '', type: 'address[]' }],
  },
  {
    type: 'function',
    name: 'getContribution',
    stateMutability: 'view',
    inputs: [
      { name: 'roundId', type: 'bytes12' },
      { name: 'contributor', type: 'address' },
    ],
    outputs: [
      {
        name: '',
        type: 'tuple',
        components: [
          { name: 'contributor', type: 'address' },
          { name: 'contributorIndex', type: 'uint16' },
          { name: 'commitmentsHash', type: 'bytes32' },
          { name: 'encryptedSharesHash', type: 'bytes32' },
          { name: 'commitmentVectorDigest', type: 'bytes32' },
          { name: 'accepted', type: 'bool' },
        ],
      },
    ],
  },
  {
    type: 'function',
    name: 'getPartialDecryption',
    stateMutability: 'view',
    inputs: [
      { name: 'roundId', type: 'bytes12' },
      { name: 'participant', type: 'address' },
      { name: 'ciphertextIndex', type: 'uint16' },
    ],
    outputs: [
      {
        name: '',
        type: 'tuple',
        components: [
          { name: 'participant', type: 'address' },
          { name: 'participantIndex', type: 'uint16' },
          { name: 'ciphertextIndex', type: 'uint16' },
          { name: 'deltaHash', type: 'bytes32' },
          {
            name: 'delta',
            type: 'tuple',
            components: [
              { name: 'x', type: 'uint256' },
              { name: 'y', type: 'uint256' },
            ],
          },
          { name: 'accepted', type: 'bool' },
        ],
      },
    ],
  },
  {
    type: 'function',
    name: 'getCombinedDecryption',
    stateMutability: 'view',
    inputs: [
      { name: 'roundId', type: 'bytes12' },
      { name: 'ciphertextIndex', type: 'uint16' },
    ],
    outputs: [
      {
        name: '',
        type: 'tuple',
        components: [
          { name: 'ciphertextIndex', type: 'uint16' },
          { name: 'completed', type: 'bool' },
          { name: 'plaintext', type: 'uint256' },
        ],
      },
    ],
  },
  {
    type: 'function',
    name: 'getCiphertextHash',
    stateMutability: 'view',
    inputs: [
      { name: 'roundId', type: 'bytes12' },
      { name: 'ciphertextIndex', type: 'uint16' },
    ],
    outputs: [{ name: '', type: 'bytes32' }],
  },
  {
    type: 'function',
    name: 'getPlaintext',
    stateMutability: 'view',
    inputs: [
      { name: 'roundId', type: 'bytes12' },
      { name: 'ciphertextIndex', type: 'uint16' },
    ],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'getDecryptionPolicy',
    stateMutability: 'view',
    inputs: [{ name: 'roundId', type: 'bytes12' }],
    outputs: [
      {
        name: '',
        type: 'tuple',
        components: [
          { name: 'ownerOnly', type: 'bool' },
          { name: 'maxDecryptions', type: 'uint16' },
          { name: 'notBeforeBlock', type: 'uint64' },
          { name: 'notBeforeTimestamp', type: 'uint64' },
          { name: 'notAfterBlock', type: 'uint64' },
          { name: 'notAfterTimestamp', type: 'uint64' },
        ],
      },
    ],
  },
  {
    type: 'function',
    name: 'getRevealedShare',
    stateMutability: 'view',
    inputs: [
      { name: 'roundId', type: 'bytes12' },
      { name: 'participant', type: 'address' },
    ],
    outputs: [
      {
        name: '',
        type: 'tuple',
        components: [
          { name: 'participant', type: 'address' },
          { name: 'participantIndex', type: 'uint16' },
          { name: 'shareValue', type: 'uint256' },
          { name: 'shareHash', type: 'bytes32' },
          { name: 'accepted', type: 'bool' },
        ],
      },
    ],
  },
  {
    type: 'function',
    name: 'getShareCommitmentHash',
    stateMutability: 'view',
    inputs: [
      { name: 'roundId', type: 'bytes12' },
      { name: 'participantIndex', type: 'uint16' },
    ],
    outputs: [{ name: '', type: 'bytes32' }],
  },
  {
    type: 'function',
    name: 'getContributionVerifierVKeyHash',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'bytes32' }],
  },
  {
    type: 'function',
    name: 'getPartialDecryptVerifierVKeyHash',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'bytes32' }],
  },
  {
    type: 'function',
    name: 'getFinalizeVerifierVKeyHash',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'bytes32' }],
  },
  {
    type: 'function',
    name: 'getDecryptCombineVerifierVKeyHash',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'bytes32' }],
  },
  {
    type: 'function',
    name: 'getRevealSubmitVerifierVKeyHash',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'bytes32' }],
  },
  {
    type: 'function',
    name: 'getRevealShareVerifierVKeyHash',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'bytes32' }],
  },

  // ── events ────────────────────────────────────────────────────────────────
  {
    type: 'event',
    name: 'RoundCreated',
    inputs: [
      { name: 'roundId', type: 'bytes12', indexed: true },
      { name: 'organizer', type: 'address', indexed: true },
      { name: 'seedBlock', type: 'uint64', indexed: false },
      { name: 'lotteryThreshold', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'SeedResolved',
    inputs: [
      { name: 'roundId', type: 'bytes12', indexed: true },
      { name: 'seed', type: 'bytes32', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'SlotClaimed',
    inputs: [
      { name: 'roundId', type: 'bytes12', indexed: true },
      { name: 'claimer', type: 'address', indexed: true },
      { name: 'slot', type: 'uint16', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'RegistrationClosed',
    inputs: [{ name: 'roundId', type: 'bytes12', indexed: true }],
  },
  {
    type: 'event',
    name: 'ContributionSubmitted',
    inputs: [
      { name: 'roundId', type: 'bytes12', indexed: true },
      { name: 'contributor', type: 'address', indexed: true },
      { name: 'contributorIndex', type: 'uint16', indexed: false },
      { name: 'commitmentsHash', type: 'bytes32', indexed: false },
      { name: 'encryptedSharesHash', type: 'bytes32', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'RoundFinalized',
    inputs: [
      { name: 'roundId', type: 'bytes12', indexed: true },
      { name: 'aggregateCommitmentsHash', type: 'bytes32', indexed: false },
      { name: 'collectivePublicKeyHash', type: 'bytes32', indexed: false },
      { name: 'shareCommitmentHash', type: 'bytes32', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'PartialDecryptionSubmitted',
    inputs: [
      { name: 'roundId', type: 'bytes12', indexed: true },
      { name: 'participant', type: 'address', indexed: true },
      { name: 'participantIndex', type: 'uint16', indexed: false },
      { name: 'ciphertextIndex', type: 'uint16', indexed: false },
      { name: 'deltaHash', type: 'bytes32', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'CiphertextSubmitted',
    inputs: [
      { name: 'roundId', type: 'bytes12', indexed: true },
      { name: 'ciphertextIndex', type: 'uint16', indexed: true },
      { name: 'submitter', type: 'address', indexed: true },
      { name: 'c1x', type: 'uint256', indexed: false },
      { name: 'c1y', type: 'uint256', indexed: false },
      { name: 'c2x', type: 'uint256', indexed: false },
      { name: 'c2y', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'DecryptionCombined',
    inputs: [
      { name: 'roundId', type: 'bytes12', indexed: true },
      { name: 'ciphertextIndex', type: 'uint16', indexed: true },
      { name: 'combineHash', type: 'bytes32', indexed: false },
      { name: 'plaintext', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'RevealedShareSubmitted',
    inputs: [
      { name: 'roundId', type: 'bytes12', indexed: true },
      { name: 'participant', type: 'address', indexed: true },
      { name: 'participantIndex', type: 'uint16', indexed: false },
      { name: 'shareHash', type: 'bytes32', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'SecretReconstructed',
    inputs: [
      { name: 'roundId', type: 'bytes12', indexed: true },
      { name: 'disclosureHash', type: 'bytes32', indexed: false },
      { name: 'reconstructedSecretHash', type: 'bytes32', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'RoundEvicted',
    inputs: [{ name: 'roundId', type: 'bytes12', indexed: true }],
  },
  {
    type: 'event',
    name: 'RoundAborted',
    inputs: [{ name: 'roundId', type: 'bytes12', indexed: true }],
  },

  // ── errors ────────────────────────────────────────────────────────────────
  { type: 'error', name: 'InvalidPolicy', inputs: [] },
  { type: 'error', name: 'InvalidRound', inputs: [] },
  { type: 'error', name: 'InvalidPhase', inputs: [] },
  { type: 'error', name: 'NotEligible', inputs: [] },
  { type: 'error', name: 'AlreadyClaimed', inputs: [] },
  { type: 'error', name: 'SlotsFull', inputs: [] },
  { type: 'error', name: 'SeedNotReady', inputs: [] },
  { type: 'error', name: 'SeedExpired', inputs: [] },
  { type: 'error', name: 'NotRegistered', inputs: [] },
  { type: 'error', name: 'NotSelectedParticipant', inputs: [] },
  { type: 'error', name: 'AlreadyContributed', inputs: [] },
  { type: 'error', name: 'AlreadyFinalized', inputs: [] },
  { type: 'error', name: 'AlreadyPartiallyDecrypted', inputs: [] },
  { type: 'error', name: 'InvalidCommitteeSize', inputs: [] },
  { type: 'error', name: 'InvalidContribution', inputs: [] },
  { type: 'error', name: 'InvalidFinalization', inputs: [] },
  { type: 'error', name: 'InvalidPartialDecryption', inputs: [] },
  { type: 'error', name: 'InsufficientContributions', inputs: [] },
  { type: 'error', name: 'InvalidVerifier', inputs: [] },
  { type: 'error', name: 'Unauthorized', inputs: [] },
  { type: 'error', name: 'AlreadyCombined', inputs: [] },
  { type: 'error', name: 'AlreadyRevealed', inputs: [] },
  { type: 'error', name: 'InvalidCombinedDecryption', inputs: [] },
  { type: 'error', name: 'InvalidRevealedShare', inputs: [] },
  { type: 'error', name: 'InvalidReconstruction', inputs: [] },
  { type: 'error', name: 'InsufficientPartialDecryptions', inputs: [] },
  { type: 'error', name: 'InsufficientRevealedShares', inputs: [] },
  { type: 'error', name: 'DisclosureDisabled', inputs: [] },
  { type: 'error', name: 'InvalidProofInput', inputs: [] },
  { type: 'error', name: 'NotOwner', inputs: [] },
  { type: 'error', name: 'InvalidDecryptionPolicy', inputs: [] },
  { type: 'error', name: 'DecryptionNotYetAllowed', inputs: [] },
  { type: 'error', name: 'DecryptionExpired', inputs: [] },
  { type: 'error', name: 'DecryptionLimitReached', inputs: [] },
  { type: 'error', name: 'CiphertextAlreadySubmitted', inputs: [] },
  { type: 'error', name: 'CiphertextNotSubmitted', inputs: [] },
  { type: 'error', name: 'InvalidCiphertext', inputs: [] },
] as const;

export const dkgRegistryAbi = [
  // ── write functions ───────────────────────────────────────────────────────
  {
    type: 'function',
    name: 'registerKey',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'pubX', type: 'uint256' },
      { name: 'pubY', type: 'uint256' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'updateKey',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'pubX', type: 'uint256' },
      { name: 'pubY', type: 'uint256' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'reactivate',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    type: 'function',
    name: 'heartbeat',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    type: 'function',
    name: 'reap',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'operator', type: 'address' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'markActive',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'operator', type: 'address' }],
    outputs: [],
  },

  // ── view functions ────────────────────────────────────────────────────────
  {
    type: 'function',
    name: 'nodeCount',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint64' }],
  },
  {
    type: 'function',
    name: 'activeCount',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint64' }],
  },
  {
    type: 'function',
    name: 'INACTIVITY_WINDOW',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint64' }],
  },
  {
    type: 'function',
    name: 'isActive',
    stateMutability: 'view',
    inputs: [{ name: 'operator', type: 'address' }],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    type: 'function',
    name: 'manager',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'function',
    name: 'getNode',
    stateMutability: 'view',
    inputs: [{ name: 'operator', type: 'address' }],
    outputs: [
      {
        name: '',
        type: 'tuple',
        components: [
          { name: 'operator', type: 'address' },
          { name: 'pubX', type: 'uint256' },
          { name: 'pubY', type: 'uint256' },
          { name: 'status', type: 'uint8' },
          { name: 'lastActiveBlock', type: 'uint64' },
        ],
      },
    ],
  },

  // ── events ────────────────────────────────────────────────────────────────
  {
    type: 'event',
    name: 'NodeRegistered',
    inputs: [
      { name: 'operator', type: 'address', indexed: true },
      { name: 'pubX', type: 'uint256', indexed: false },
      { name: 'pubY', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'NodeUpdated',
    inputs: [
      { name: 'operator', type: 'address', indexed: true },
      { name: 'pubX', type: 'uint256', indexed: false },
      { name: 'pubY', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'NodeMarkedActive',
    inputs: [
      { name: 'operator', type: 'address', indexed: true },
      { name: 'atBlock', type: 'uint64', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'NodeReaped',
    inputs: [
      { name: 'operator', type: 'address', indexed: true },
      { name: 'lastActiveBlock', type: 'uint64', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'NodeReactivated',
    inputs: [{ name: 'operator', type: 'address', indexed: true }],
  },
  {
    type: 'event',
    name: 'ManagerSet',
    inputs: [{ name: 'manager', type: 'address', indexed: true }],
  },

  // ── errors ────────────────────────────────────────────────────────────────
  { type: 'error', name: 'InvalidKey', inputs: [] },
  { type: 'error', name: 'AlreadyRegistered', inputs: [] },
  { type: 'error', name: 'NotRegistered', inputs: [] },
  { type: 'error', name: 'NotManager', inputs: [] },
  { type: 'error', name: 'ManagerAlreadySet', inputs: [] },
  { type: 'error', name: 'ManagerNotSet', inputs: [] },
  { type: 'error', name: 'NotActive', inputs: [] },
  { type: 'error', name: 'StillActive', inputs: [] },
  { type: 'error', name: 'NotInactive', inputs: [] },
] as const;
