// SPDX-License-Identifier: AGPL-3.0-or-later
pragma solidity 0.8.28;

/// @title BabyJubJub
/// @notice Twisted Edwards elliptic curve arithmetic over the BN254 scalar field
///         in the REDUCED form (A = -1) used by gnark-crypto's
///         `bn254/twistededwards` curve and by the davinci-dkg ZK circuits.
///         Adapted from https://github.com/yondonfu/sol-baby-jubjub (MIT) —
///         the original implementation used the iden3/circomlib chart
///         (A = 168700, D = 168696). It was switched to the reduced chart
///         because contributions emit `commitment0X/Y` in reduced form
///         (`group.Encode(...)` -> gnark `PointAffine`), and the on-chain
///         accumulator must use the same chart or the resulting point is
///         meaningless in either form.
///
/// Curve equation: a·x² + y² = 1 + d·x²·y²
///   a = -1 (encoded as Q - 1)
///   d = 12181644023421730124874158521699555681764249180949974110617291017600649128846
///   Q = 21888242871839275222246405745257275088548364400416034343698204186575808495617
///       (BN254 scalar field prime)
///
/// Identity element: (0, 1)  (unchanged across the two charts).
///
/// The addition formula
///   x3 = (x1·y2 + y1·x2) / (1 + d·x1·x2·y1·y2)
///   y3 = (y1·y2 - a·x1·x2) / (1 - d·x1·x2·y1·y2)
/// is shape-identical for any (a, d) twisted-Edwards pair, so the function
/// signature and body below need no change beyond the constants.
library BabyJubJub {
    error NotCanonical();
    error NotOnCurve();
    error IsIdentity();
    error NotInPrimeSubgroup();

    /// @dev BN254 scalar field prime Q
    uint256 internal constant Q =
        21888242871839275222246405745257275088548364400416034343698204186575808495617;
    /// @dev Curve parameter a = -1 (mod Q)
    uint256 internal constant A =
        21888242871839275222246405745257275088548364400416034343698204186575808495616;
    /// @dev Curve parameter d (reduced-form value matching gnark BabyJubJub)
    uint256 internal constant D =
        12181644023421730124874158521699555681764249180949974110617291017600649128846;

    /// @dev Generator point X coordinate (gnark canonical reduced form).
    uint256 internal constant GENERATOR_X =
        9671717474070082183213120605117400219616337014328744928644933853176787189663;
    /// @dev Generator point Y coordinate (gnark canonical reduced form).
    uint256 internal constant GENERATOR_Y =
        16950150798460657717958625567821834550301663161624707787222815936182638968203;
    /// @dev Subgroup (prime-order) cardinality. The full curve has 8·L points;
    ///      the prime-order subgroup generated by `(GENERATOR_X, GENERATOR_Y)`
    ///      has order `SUBGROUP_ORDER`. Scalars for `scalarMul` should be
    ///      reduced mod this value.
    uint256 internal constant SUBGROUP_ORDER =
        2736030358979909402780800718157159386076813972158567259200215660948447373041;
    /// @dev Cofactor h = 8.
    uint256 internal constant COFACTOR = 8;

    // ─── Point validation ──────────────────────────────────────────────────────

    /// @notice Test whether `(x, y)` satisfies the twisted-Edwards equation
    ///         `a·x² + y² = 1 + d·x²·y²` with `a = -1`.
    /// @dev    Pure (no precompile use). Returns true for the identity (0, 1).
    function isOnCurve(uint256 x, uint256 y) internal pure returns (bool) {
        if (x >= Q || y >= Q) return false;
        uint256 x2 = mulmod(x, x, Q);
        uint256 y2 = mulmod(y, y, Q);
        // lhs = a·x² + y² = (Q - x²) + y² (mod Q)  (since a = -1)
        uint256 lhs = addmod(_submod(0, x2), y2, Q);
        // rhs = 1 + d·x²·y²
        uint256 rhs = addmod(1, mulmod(D, mulmod(x2, y2, Q), Q), Q);
        return lhs == rhs;
    }

    /// @notice Whether the encoding is canonical: both coordinates lie in [0, Q).
    function isCanonical(uint256 x, uint256 y) internal pure returns (bool) {
        return x < Q && y < Q;
    }

    /// @notice Whether `(x, y)` is the identity element (0, 1).
    function isIdentity(uint256 x, uint256 y) internal pure returns (bool) {
        return x == 0 && y == 1;
    }

    /// @notice Whether `(x, y)` lies in the prime-order subgroup.
    /// @dev    Implemented as `[L]P == identity`. This costs one full scalar
    ///         multiplication (~250 doubles + ~125 adds) and is intended only
    ///         for entry points where prime-subgroup membership is otherwise
    ///         not enforced. Most call sites in this codebase derive their
    ///         points from a Schnorr proof of knowledge of a discrete log
    ///         relative to the prime-subgroup generator, which implicitly
    ///         constrains the result to the prime subgroup; in those cases an
    ///         explicit subgroup check is redundant and `requireValidPoint`
    ///         (without the subgroup check) is sufficient.
    function isInPrimeSubgroup(uint256 x, uint256 y) internal view returns (bool) {
        (uint256 lpx, uint256 lpy) = scalarMul(SUBGROUP_ORDER, x, y);
        return lpx == 0 && lpy == 1;
    }

    /// @notice Validate that `(x, y)` is a canonical, on-curve, non-identity
    ///         point on BabyJubJub. Reverts with one of `NotCanonical`,
    ///         `NotOnCurve`, or `IsIdentity` on failure.
    /// @dev    Does NOT enforce prime-subgroup membership; see
    ///         `isInPrimeSubgroup` for that check. Callers that need the
    ///         stronger guarantee (i.e. those that do not separately prove
    ///         knowledge of a discrete log) should additionally call
    ///         `isInPrimeSubgroup`.
    function requireValidPoint(uint256 x, uint256 y) internal pure {
        if (!isCanonical(x, y)) revert NotCanonical();
        if (x == 0 && y == 1) revert IsIdentity();
        if (!isOnCurve(x, y)) revert NotOnCurve();
    }

    /// @notice Add two points on the Baby JubJub curve.
    ///         Implements the unified twisted Edwards addition formula:
    ///           x3 = (x1·y2 + y1·x2) / (1 + d·x1·x2·y1·y2)
    ///           y3 = (y1·y2 - a·x1·x2) / (1 - d·x1·x2·y1·y2)
    /// @dev The formula is complete (works for all points including the identity).
    ///      The identity element is (0, 1).
    /// @param _x1 x-coordinate of point P1
    /// @param _y1 y-coordinate of point P1
    /// @param _x2 x-coordinate of point P2
    /// @param _y2 y-coordinate of point P2
    /// @return x3 x-coordinate of P1 + P2
    /// @return y3 y-coordinate of P1 + P2
    function pointAdd(
        uint256 _x1,
        uint256 _y1,
        uint256 _x2,
        uint256 _y2
    ) internal view returns (uint256 x3, uint256 y3) {
        // Identity shortcuts: (0,1) is the neutral element
        if (_x1 == 0 && _y1 == 1) {
            return (_x2, _y2);
        }
        if (_x2 == 0 && _y2 == 1) {
            return (_x1, _y1);
        }

        uint256 x1x2 = mulmod(_x1, _x2, Q);
        uint256 y1y2 = mulmod(_y1, _y2, Q);
        uint256 dx1x2y1y2 = mulmod(D, mulmod(x1x2, y1y2, Q), Q);

        uint256 x3Num = addmod(mulmod(_x1, _y2, Q), mulmod(_y1, _x2, Q), Q);
        uint256 y3Num = _submod(y1y2, mulmod(A, x1x2, Q));

        x3 = mulmod(x3Num, _inverse(addmod(1, dx1x2y1y2, Q)), Q);
        y3 = mulmod(y3Num, _inverse(_submod(1, dx1x2y1y2)), Q);
    }

    /// @notice Point doubling: P + P. Implemented via `pointAdd`; the
    ///         twisted-Edwards addition formula is unified, so the same
    ///         code path is correct for distinct points and equal points.
    /// @dev    Kept as a named entry point for clarity at call sites and to
    ///         allow a future optimization that uses the dedicated
    ///         doubling formula (saves one `mulmod` per double).
    function pointDouble(uint256 x, uint256 y)
        internal
        view
        returns (uint256, uint256)
    {
        return pointAdd(x, y, x, y);
    }

    /// @notice Scalar multiplication `[s] (x, y)` on BabyJubJub.
    /// @dev    Binary double-and-add, LSB-first. The scalar is reduced
    ///         modulo `SUBGROUP_ORDER` first; this is sound for points in
    ///         the prime-order subgroup (every honest call site) and
    ///         saves an average of ~2 doublings versus the unreduced loop.
    ///
    ///         Cost: ~`bitlen(s % L)` doublings + popcount adds, each
    ///         dominated by one bigModExp precompile call (the inverse in
    ///         `pointAdd`). For a uniformly random scalar this works out to
    ///         ~250 + ~125 ≈ 375 group operations.
    function scalarMul(uint256 s, uint256 x, uint256 y)
        internal
        view
        returns (uint256, uint256)
    {
        uint256 k = s % SUBGROUP_ORDER;
        if (k == 0) return (0, 1); // identity

        // Identity addend, generator-of-result
        uint256 rx = 0;
        uint256 ry = 1;
        uint256 px = x;
        uint256 py = y;

        while (k != 0) {
            if (k & 1 == 1) {
                (rx, ry) = pointAdd(rx, ry, px, py);
            }
            k >>= 1;
            if (k != 0) {
                (px, py) = pointAdd(px, py, px, py);
            }
        }
        return (rx, ry);
    }

    /// @notice Convenience: `[s] · G` where G is the canonical generator.
    function scalarMulBase(uint256 s) internal view returns (uint256, uint256) {
        return scalarMul(s, GENERATOR_X, GENERATOR_Y);
    }

    // ─── Private helpers ───────────────────────────────────────────────────────

    /// @dev Modular subtraction: (a - b) mod Q, handling underflow.
    function _submod(uint256 _a, uint256 _b) private pure returns (uint256) {
        return addmod(_a, Q - (_b % Q), Q);
    }

    /// @dev Q - 2, used as the Fermat exponent for modular inverse (a^(Q-2) mod Q).
    ///      Stored as a constant so the assembly block can reference it via mload.
    uint256 private constant Q_MINUS_2 =
        21888242871839275222246405745257275088548364400416034343698204186575808495615;

    /// @dev Modular multiplicative inverse via Fermat's little theorem.
    ///      Returns a^(Q-2) mod Q using the bigModExp precompile (0x05).
    function _inverse(uint256 _a) private view returns (uint256 o) {
        uint256 exponent = Q_MINUS_2;
        uint256 modulus = Q;
        assembly {
            let memPtr := mload(0x40)
            mstore(memPtr, 0x20)               // length of base
            mstore(add(memPtr, 0x20), 0x20)    // length of exponent
            mstore(add(memPtr, 0x40), 0x20)    // length of modulus
            mstore(add(memPtr, 0x60), _a)      // base
            mstore(add(memPtr, 0x80), exponent) // exponent = Q - 2
            mstore(add(memPtr, 0xa0), modulus)  // modulus = Q
            // bigModExp precompile at 0x05
            let success := staticcall(gas(), 0x05, memPtr, 0xc0, memPtr, 0x20)
            if iszero(success) { revert(0, 0) }
            o := mload(memPtr)
        }
    }
}
