// Cross-impl vector tests. Reads tests/vectors/*.json (generated by
// `cmd/protocol-vectors`) and asserts the SDK reproduces every value
// byte-for-byte. The same files are consumed by the Foundry suite so a
// drift in any layer breaks CI in all of them.


import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import {
  DomainOperatorRegisterV1,
  DomainOrganizerRegisterV1,
  DomainDLEQV1,
  DomainOrganizerShareV1,
} from '../src/protocol';
import {
  verifyOperatorSchnorr,
  verifyOrganizerSchnorr,
  verifyDleq,
  dleqChallenge,
  operatorSchnorrChallenge,
  organizerSchnorrChallenge,
  DOMAIN_PARTIAL_DECRYPT,
  BN254_Q,
  SUBGROUP_ORDER,
} from '../src/schnorr';
import {
  organizerShareChallenge,
  proveOrganizerShare,
  verifyOrganizerShare,
} from '../src/dleq';
import { fromRTEtoTE, fromTEtoRTE } from '../src/crypto/babyjub-form';
import type { BabyJubPoint } from '../src/types';
import { Base8, mulPointEscalar } from '@zk-kit/baby-jubjub';
import type { Hex } from 'viem';
import type { Point } from '@zk-kit/baby-jubjub';

const VECTORS_DIR = resolve(__dirname, '../../tests/vectors');

function load<T>(name: string): T {
  return JSON.parse(readFileSync(resolve(VECTORS_DIR, name), 'utf8')) as T;
}

// ─── protocol.json ─────────────────────────────────────────────────────────

interface OrganizerShareVector {
  label: string;
  domain: string;
  skOrg: string;
  w: string;
  epochId: string;
  aid: string;
  ctIdx: number;
  pkOrgX: string;
  pkOrgY: string;
  c1x: string;
  c1y: string;
  deltaX: string;
  deltaY: string;
  a1x: string;
  a1y: string;
  a2x: string;
  a2y: string;
  e: string;
  z: string;
}

interface ProtocolFile {
  domains: Record<string, { preimage: string; keccak256: string; bn254Reduced: string }>;
  bn254Q: string;
  subgroupOrderL: string;
  organizerShare: OrganizerShareVector;
}

describe('vectors / protocol.json', () => {
  const f = load<ProtocolFile>('protocol.json');

  it('domain digests match', () => {
    expect(DomainOperatorRegisterV1).toBe(f.domains.OperatorRegisterV1.keccak256);
    expect(DomainOrganizerRegisterV1).toBe(f.domains.OrganizerRegisterV1.keccak256);
    expect(DomainDLEQV1).toBe(f.domains.DLEQV1.keccak256);
  });

  it('OrganizerShareV1 domain digest matches', () => {
    const d = f.domains.OrganizerShareV1;
    expect(d.preimage).toBe('davinci-dkg:organizer-share:v1');
    expect(DomainOrganizerShareV1).toBe(d.keccak256);
  });

  it('PartialDecrypt domain reduction matches', () => {
    expect(DOMAIN_PARTIAL_DECRYPT.toString()).toBe(
      f.domains.PartialDecryptCircuit.bn254Reduced,
    );
  });

  it('BN254 Q matches', () => {
    expect(BN254_Q.toString()).toBe(f.bn254Q);
  });

  it('BabyJubJub subgroup order matches', () => {
    expect(SUBGROUP_ORDER.toString()).toBe(f.subgroupOrderL);
  });
});

// ─── protocol.json → organizer share (spec §3) ─────────────────────────────

describe('vectors / organizer share', () => {
  const v = load<ProtocolFile>('protocol.json').organizerShare;

  const epochId = v.epochId as Hex;
  const aid = v.aid as Hex;
  const skOrg = BigInt(v.skOrg);
  const w = BigInt(v.w);
  const pkOrg: BabyJubPoint = [BigInt(v.pkOrgX), BigInt(v.pkOrgY)];
  const c1: BabyJubPoint = [BigInt(v.c1x), BigInt(v.c1y)];
  const delta: BabyJubPoint = [BigInt(v.deltaX), BigInt(v.deltaY)];
  const a1: BabyJubPoint = [BigInt(v.a1x), BigInt(v.a1y)];
  const a2: BabyJubPoint = [BigInt(v.a2x), BigInt(v.a2y)];

  it('binds the OrganizerShareV1 domain', () => {
    expect(v.domain).toBe(DomainOrganizerShareV1);
  });

  it('PK_org in the vector is sk_org·G in on-chain (RTE) form', () => {
    const pkTE = mulPointEscalar(Base8, skOrg) as Point<bigint>;
    expect(fromTEtoRTE(pkTE[0], pkTE[1])).toEqual(pkOrg);
  });

  it('reproduces the Go challenge e byte for byte', () => {
    expect(
      organizerShareChallenge(epochId, aid, v.ctIdx, pkOrg, c1, delta, a1, a2).toString(),
    ).toBe(v.e);
  });

  it('verifies the Go-produced proof', () => {
    expect(
      verifyOrganizerShare(epochId, aid, v.ctIdx, pkOrg, c1, delta, { a1, a2, z: BigInt(v.z) }),
    ).toBe(true);
  });

  it('the SDK prover reproduces every word given the same secret and witness', () => {
    // This is what catches a coordinate-form or reduction drift: the prover
    // does the curve arithmetic in TE and emits RTE, and every one of those
    // words has to land on the Go value.
    const c1TE = fromRTEtoTE(c1[0], c1[1]) as BabyJubPoint;
    const share = proveOrganizerShare(epochId, aid, v.ctIdx, skOrg, c1TE, w);
    expect(share.delta).toEqual(delta);
    expect(share.a1).toEqual(a1);
    expect(share.a2).toEqual(a2);
    expect(share.z.toString()).toBe(v.z);
  });

  it('rejects the vector under a tampered response or a foreign ciphertext index', () => {
    expect(
      verifyOrganizerShare(epochId, aid, v.ctIdx, pkOrg, c1, delta, {
        a1, a2, z: BigInt(v.z) + 1n,
      }),
    ).toBe(false);
    expect(
      verifyOrganizerShare(epochId, aid, v.ctIdx + 1, pkOrg, c1, delta, { a1, a2, z: BigInt(v.z) }),
    ).toBe(false);
  });
});

// ─── schnorr.json ──────────────────────────────────────────────────────────

interface SchnorrFile {
  operator: Array<{
    label: string;
    operator: string;
    pubX: string;
    pubY: string;
    ax: string;
    ay: string;
    z: string;
  }>;
  organizer: Array<{
    label: string;
    epochId: string;
    aid: string;
    pkOrgX: string;
    pkOrgY: string;
    ax: string;
    ay: string;
    z: string;
  }>;
}

describe('vectors / schnorr.json', () => {
  const f = load<SchnorrFile>('schnorr.json');

  it.each(f.operator)('operator vector "$label" — challenge + verify', (v) => {
    // Verify is the load-bearing assertion: it both rederives `c` over the
    // keccak transcript and runs the curve equation (z·G == A + c·PK).
    const ok = verifyOperatorSchnorr(v.operator as Hex, BigInt(v.pubX), BigInt(v.pubY), {
      ax: BigInt(v.ax), ay: BigInt(v.ay), z: BigInt(v.z),
    });
    expect(ok).toBe(true);
    // Tamper one bit and confirm rejection.
    const bad = verifyOperatorSchnorr(v.operator as Hex, BigInt(v.pubX), BigInt(v.pubY), {
      ax: BigInt(v.ax), ay: BigInt(v.ay), z: BigInt(v.z) + 1n,
    });
    expect(bad).toBe(false);
  });

  it.each(f.organizer)('organizer vector "$label" — challenge + verify', (v) => {
    const ok = verifyOrganizerSchnorr(
      v.epochId as Hex, v.aid as Hex,
      BigInt(v.pkOrgX), BigInt(v.pkOrgY),
      { ax: BigInt(v.ax), ay: BigInt(v.ay), z: BigInt(v.z) },
    );
    expect(ok).toBe(true);
  });

  it('operator challenge is deterministic', () => {
    const v = f.operator[0]!;
    const c = operatorSchnorrChallenge(
      v.operator as Hex, BigInt(v.pubX), BigInt(v.pubY), BigInt(v.ax), BigInt(v.ay),
    );
    expect(operatorSchnorrChallenge(
      v.operator as Hex, BigInt(v.pubX), BigInt(v.pubY), BigInt(v.ax), BigInt(v.ay),
    )).toBe(c);
  });

  it('organizer challenge is sensitive to aid', () => {
    const v = f.organizer[0]!;
    const c = organizerSchnorrChallenge(
      v.epochId as Hex, v.aid as Hex,
      BigInt(v.pkOrgX), BigInt(v.pkOrgY), BigInt(v.ax), BigInt(v.ay),
    );
    const cOther = organizerSchnorrChallenge(
      v.epochId as Hex,
      ('0x' + '00'.repeat(31) + 'ff') as Hex,
      BigInt(v.pkOrgX), BigInt(v.pkOrgY), BigInt(v.ax), BigInt(v.ay),
    );
    expect(c).not.toBe(cOther);
  });
});

// ─── dleq.json (committee partial decryptions) ─────────────────────────────

interface DleqFile {
  partialDecryptDomainBn254: string;
  vectors: Array<{
    label: string;
    epochId: string;
    aid: string;
    ctIdx: number;
    participantIndex: number;
    baseX: string; baseY: string;
    pubX: string; pubY: string;
    deltaX: string; deltaY: string;
    a1x: string; a1y: string;
    a2x: string; a2y: string;
    challenge: string;
    response: string;
  }>;
}

describe('vectors / dleq.json', () => {
  const f = load<DleqFile>('dleq.json');

  it('PartialDecrypt domain matches Go', () => {
    expect(DOMAIN_PARTIAL_DECRYPT.toString()).toBe(f.partialDecryptDomainBn254);
  });

  it.each(f.vectors)('DLEQ vector "$label" — challenge + verify', (v) => {
    const transcript = {
      epochId: v.epochId as Hex,
      aid: v.aid as Hex,
      ctIdx: v.ctIdx,
      participantIndex: v.participantIndex,
      points: {
        base: [BigInt(v.baseX), BigInt(v.baseY)] as Point<bigint>,
        publicKey: [BigInt(v.pubX), BigInt(v.pubY)] as Point<bigint>,
        delta: [BigInt(v.deltaX), BigInt(v.deltaY)] as Point<bigint>,
        a1: [BigInt(v.a1x), BigInt(v.a1y)] as Point<bigint>,
        a2: [BigInt(v.a2x), BigInt(v.a2y)] as Point<bigint>,
      },
    };
    const c = dleqChallenge(transcript);
    expect(c.toString()).toBe(v.challenge);
    expect(verifyDleq(transcript, BigInt(v.response))).toBe(true);
  });
});
