// Cross-impl vector tests. Reads tests/vectors/*.json (generated by
// `cmd/protocol-vectors`) and asserts the SDK reproduces every value
// byte-for-byte. The same files are consumed by the Foundry suite so a
// drift in any layer breaks CI in all of them.

import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import {
  AppMode,
  Role,
  DomainOperatorRegisterV1,
  DomainOrganizerRegisterV1,
  DomainDLEQV1,
} from '../src/protocol';
import { computeS, SUBGROUP_ORDER } from '../src/derive';
import {
  verifyOperatorSchnorr,
  verifyOrganizerSchnorr,
  verifyDleq,
  dleqChallenge,
  operatorSchnorrChallenge,
  organizerSchnorrChallenge,
  DOMAIN_PARTIAL_DECRYPT,
  BN254_Q,
} from '../src/schnorr';
import type { Hex } from 'viem';
import type { Point } from '@zk-kit/baby-jubjub';

const VECTORS_DIR = resolve(__dirname, '../../tests/vectors');

function load<T>(name: string): T {
  return JSON.parse(readFileSync(resolve(VECTORS_DIR, name), 'utf8')) as T;
}

// ─── protocol.json ─────────────────────────────────────────────────────────

interface ProtocolFile {
  appMode: { PublicDerivation: number; OrganizerCoDec: number };
  role: { Committee: number; Organizer: number };
  domains: Record<string, { preimage: string; keccak256: string; bn254Reduced: string }>;
  bn254Q: string;
}

describe('vectors / protocol.json', () => {
  const f = load<ProtocolFile>('protocol.json');

  it('AppMode matches', () => {
    expect(AppMode.PublicDerivation).toBe(f.appMode.PublicDerivation);
    expect(AppMode.OrganizerCoDec).toBe(f.appMode.OrganizerCoDec);
  });

  it('Role matches', () => {
    expect(Role.Committee).toBe(f.role.Committee);
    expect(Role.Organizer).toBe(f.role.Organizer);
  });

  it('domain digests match', () => {
    expect(DomainOperatorRegisterV1).toBe(f.domains.OperatorRegisterV1.keccak256);
    expect(DomainOrganizerRegisterV1).toBe(f.domains.OrganizerRegisterV1.keccak256);
    expect(DomainDLEQV1).toBe(f.domains.DLEQV1.keccak256);
    // (DerivationV1 removed — DEEPSEEK §2.3.)
  });

  it('PartialDecrypt domain reduction matches', () => {
    expect(DOMAIN_PARTIAL_DECRYPT.toString()).toBe(
      f.domains.PartialDecryptCircuit.bn254Reduced,
    );
  });

  it('BN254 Q matches', () => {
    expect(BN254_Q.toString()).toBe(f.bn254Q);
  });
});

// ─── derivation.json ───────────────────────────────────────────────────────

interface DerivationFile {
  subgroupOrderL: string;
  vectors: Array<{
    label: string;
    epochId: string;
    pkEpX: string;
    pkEpY: string;
    aid: string;
    s: string;
  }>;
}

describe('vectors / derivation.json', () => {
  const f = load<DerivationFile>('derivation.json');

  it('subgroup order matches', () => {
    expect(SUBGROUP_ORDER.toString()).toBe(f.subgroupOrderL);
  });

  it.each(f.vectors)('S vector "$label"', (v) => {
    const got = computeS(v.epochId as Hex, BigInt(v.pkEpX), BigInt(v.pkEpY), v.aid as Hex);
    expect(got.toString()).toBe(v.s);
  });
});

// ─── schnorr.json ──────────────────────────────────────────────────────────

interface SchnorrFile {
  operator: Array<{
    label: string;
    operator: string;
    pubX: string;
    pubY: string;
    ax: string;
    ay: string;
    z: string;
  }>;
  organizer: Array<{
    label: string;
    epochId: string;
    aid: string;
    pkOrgX: string;
    pkOrgY: string;
    ax: string;
    ay: string;
    z: string;
  }>;
}

describe('vectors / schnorr.json', () => {
  const f = load<SchnorrFile>('schnorr.json');

  it.each(f.operator)('operator vector "$label" — challenge + verify', (v) => {
    // Verify is the load-bearing assertion: it both rederives `c` via
    // Poseidon (transcript correctness) and runs the curve equation
    // (z·G == A + c·PK).
    const ok = verifyOperatorSchnorr(v.operator as Hex, BigInt(v.pubX), BigInt(v.pubY), {
      ax: BigInt(v.ax), ay: BigInt(v.ay), z: BigInt(v.z),
    });
    expect(ok).toBe(true);
    // Tamper one bit and confirm rejection.
    const bad = verifyOperatorSchnorr(v.operator as Hex, BigInt(v.pubX), BigInt(v.pubY), {
      ax: BigInt(v.ax), ay: BigInt(v.ay), z: BigInt(v.z) + 1n,
    });
    expect(bad).toBe(false);
  });

  it.each(f.organizer)('organizer vector "$label" — challenge + verify', (v) => {
    const ok = verifyOrganizerSchnorr(
      v.epochId as Hex, v.aid as Hex,
      BigInt(v.pkOrgX), BigInt(v.pkOrgY),
      { ax: BigInt(v.ax), ay: BigInt(v.ay), z: BigInt(v.z) },
    );
    expect(ok).toBe(true);
  });

  it('operator challenge matches Go for one vector', () => {
    const v = f.operator[0]!;
    const c = operatorSchnorrChallenge(
      v.operator as Hex, BigInt(v.pubX), BigInt(v.pubY), BigInt(v.ax), BigInt(v.ay),
    );
    // The challenge is implicit in z = w + c·sk; we don't ship c in the
    // vector, but we can confirm two SDK runs agree.
    expect(operatorSchnorrChallenge(
      v.operator as Hex, BigInt(v.pubX), BigInt(v.pubY), BigInt(v.ax), BigInt(v.ay),
    )).toBe(c);
  });

  it('organizer challenge is sensitive to aid', () => {
    const v = f.organizer[0]!;
    const c = organizerSchnorrChallenge(
      v.epochId as Hex, v.aid as Hex,
      BigInt(v.pkOrgX), BigInt(v.pkOrgY), BigInt(v.ax), BigInt(v.ay),
    );
    const cOther = organizerSchnorrChallenge(
      v.epochId as Hex,
      ('0x' + '00'.repeat(31) + 'ff') as Hex,
      BigInt(v.pkOrgX), BigInt(v.pkOrgY), BigInt(v.ax), BigInt(v.ay),
    );
    expect(c).not.toBe(cOther);
  });
});

// ─── dleq.json ─────────────────────────────────────────────────────────────

interface DleqFile {
  partialDecryptDomainBn254: string;
  vectors: Array<{
    label: string;
    epochId: string;
    aid: string;
    ctIdx: number;
    role: number;
    participantIndex: number;
    baseX: string; baseY: string;
    pubX: string; pubY: string;
    deltaX: string; deltaY: string;
    a1x: string; a1y: string;
    a2x: string; a2y: string;
    challenge: string;
    response: string;
  }>;
}

describe('vectors / dleq.json', () => {
  const f = load<DleqFile>('dleq.json');

  it('PartialDecrypt domain matches Go', () => {
    expect(DOMAIN_PARTIAL_DECRYPT.toString()).toBe(f.partialDecryptDomainBn254);
  });

  it.each(f.vectors)('DLEQ vector "$label" — challenge + verify', (v) => {
    const transcript = {
      epochId: v.epochId as Hex,
      aid: v.aid as Hex,
      ctIdx: v.ctIdx,
      role: v.role as 1 | 2,
      participantIndex: v.participantIndex,
      points: {
        base: [BigInt(v.baseX), BigInt(v.baseY)] as Point<bigint>,
        publicKey: [BigInt(v.pubX), BigInt(v.pubY)] as Point<bigint>,
        delta: [BigInt(v.deltaX), BigInt(v.deltaY)] as Point<bigint>,
        a1: [BigInt(v.a1x), BigInt(v.a1y)] as Point<bigint>,
        a2: [BigInt(v.a2x), BigInt(v.a2y)] as Point<bigint>,
      },
    };
    const c = dleqChallenge(transcript);
    expect(c.toString()).toBe(v.challenge);
    expect(verifyDleq(transcript, BigInt(v.response))).toBe(true);
  });
});
